### ISSUE TITLE
Thumbor missing dependencies when installed using list compiled by `pip-compile` 

### ISSUE THREAD

**Issue by adnrs96** [thumbor/thumbor#1006]
When we use `pip-compile` to get a comprehensive list of dependencies for thumbor, the dependencies in the list doesn't cover all of those required by thumbor. For eg. if we use the list generated to install stuff and try run thumbor, we end up with an error which is resolved by installing `singledispatch` and `certifi`.  

### Expected behaviour
Installing stuff using the list generated by `pip-compile` should have resulted in a working thumbor app.

### Actual behaviour
Error occurs:
```
Traceback (most recent call last):
  File "./thumbor", line 7, in <module>
    from thumbor.server import main
  File "/srv/zulip-venv-cache/05ed90ee0fa406871033375ce03c74a9f4b4917a/zulip-thumbor-venv/local/lib/python2.7/site-packages/thumbor/server.py", line 20, in <module>
    from tornado.httpserver import HTTPServer
  File "/srv/zulip-venv-cache/05ed90ee0fa406871033375ce03c74a9f4b4917a/zulip-thumbor-venv/local/lib/python2.7/site-packages/tornado/httpserver.py", line 34, in <module>
    from tornado.http1connection import HTTP1ServerConnection, HTTP1ConnectionParameters
  File "/srv/zulip-venv-cache/05ed90ee0fa406871033375ce03c74a9f4b4917a/zulip-thumbor-venv/local/lib/python2.7/site-packages/tornado/http1connection.py", line 28, in <module>
    from tornado import gen
  File "/srv/zulip-venv-cache/05ed90ee0fa406871033375ce03c74a9f4b4917a/zulip-thumbor-venv/local/lib/python2.7/site-packages/tornado/gen.py", line 99, in <module>
    from singledispatch import singledispatch  # backport
ImportError: No module named singledispatch
```
### Operating system
Ubuntu 14.04 Trusty vagrant container.

We are trying to use this project in [Zulip](https://github.com/zulip/zulip/) would be happy to help fix this if someone could provide insights about where the problem likely is. For the timing we are augmenting our requirements file manually with the missing requirements.

**Comment by masom** [comment]
This seems like a bug in pip-compile, not thumbor.

`singledispatch` is used by Tornado, a thumbor dependency.

**Comment by masom** [comment]
A quick way to get all python dependencies is to build a new virtual environment and running `pip freeze` on it:

```
virtualenv --python=python2.7 ~/thumbor-venv
source ~/thumbor-venv/bin/activate
pip install thumbor
pip freeze
```

```
backports-abc==0.5
certifi==2017.11.5
derpconf==0.8.1
futures==3.1.1
libthumbor==1.3.2
pexif==0.15
Pillow==3.4.2
pip==9.0.1
pycrypto==2.6.1
pycurl==7.43.0
pytz==2017.3
setuptools==36.7.0
singledispatch==3.4.0.3
six==1.11.0
statsd==3.2.1
thumbor==6.3.2
tornado==4.5.2
wheel==0.30.0
```

**Comment by heynemann** [comment]
If you have any further questions on this subject, please reopen this issue.
