### ISSUE TITLE
TypeError: _convert_to_request_dict() takes exactly 3 arguments (4 given)

### ISSUE THREAD

**Issue by utsav2307** [thumbor/thumbor#1045]
I dont know exactly what is the issue but thumbor suddenly stopped working for me. 

I get the following error when i try to use thumbor:
2018-02-20 10:04:33 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 144, in get_image
    self.context.request.image_url
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 578, in _fetch
    loader_result = yield self.context.modules.loader.load(self.context, url)
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 483, in wrapper
    future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 471, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tc_aws/loaders/s3_loader.py", line 49, in load
    bucket_loader.get(key, callback=handle_data)
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 483, in wrapper
    future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 471, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tc_aws/aws/bucket.py", line 48, in get
    Key=self._clean_key(path),
  File "/usr/local/lib/python2.7/site-packages/tornado_botocore/base.py", line 157, in call
    callback=callback
  File "/usr/local/lib/python2.7/site-packages/tornado_botocore/base.py", line 109, in _make_api_call
    request_dict = self.client._convert_to_request_dict(api_params, operation_model, {})
TypeError: _convert_to_request_dict() takes exactly 3 arguments (4 given)

**Comment by heynemann** [comment]
Looks like a tc_aws issue, doesn't it?

**Comment by utsav2307** [comment]
I have no clue what happened here, do you have any idea how to resolve this?

**Comment by heynemann** [comment]
I'm not an user of tc_aws, maybe someone else can help you there.

**Comment by utsav2307** [comment]
Thanks for giving the right direction. 
I figured out the problem, somehow "tc_aws.loaders.s3_loader" is messed up and not working, when i changed it to tc_aws.loaders.presigning_loader, everythng started working again.

**Comment by heynemann** [comment]
NP glad to help! I think you should file a ticket in the tc_aws project, though. Closing this.
