### ISSUE TITLE
ValueError when opening a tiff

### ISSUE THREAD

**Issue by thielmann-fc** [thumbor/thumbor#1060]
### Thumbor request URL
http://thumbor-server/unsafe/200x200/current/4007360222253/RHG002/19869207.tiff

### Image file:
[19869207.tiff.zip](https://github.com/thumbor/thumbor/files/1969993/19869207.tiff.zip)

### Expected behaviour
The image should be shown in a browser

### Actual behaviour
Code 500 error with message "string size must be a multiple of element size"

> 2018-05-03 07:14:30 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 153, in get_image
    self.context.request.image_url
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 613, in _fetch
    self.context.request.engine.load(fetch_result.buffer, extension)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/engines/pil.py", line 342, in load
    buffer = self.convert_tif_to_png(buffer)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/engines/pil.py", line 326, in convert_tif_to_png
    test = numpy.fromstring(buffer, dtype='uint16')
ValueError: string size must be a multiple of element size
2018-05-03 07:14:30 thumbor:ERROR [BaseHandler] get_image failed for url `current/4007360222253/RHG002/19869207.tiff`. error: `string size must be a multiple of element size`
2018-05-03 07:14:30 tornado.access:ERROR 500 GET /unsafe/200x200/current/4007360222253/RHG002/19869207.tiff (xx.xxx.xxx.xxx) 2.17ms

### Operating system
Ubuntu 16.04.4 LTS

### Your thumbor.conf
>MAX_PIXELS = 150000000.0
LOADER = 'thumbor.loaders.file_loader'
FILE_LOADER_ROOT_PATH = '/var/www/media'

Rest of the conf is default

If fixed the issue by replacing this:
`img = cv2.imdecode(numpy.fromstring(buffer, dtype='uint16'), -1)`
by this:
`img = cv2.imdecode(numpy.fromstring(buffer, dtype='uint8'), -1)`
in line 326 of thumbor/engines/pil.py

Not sure, if this is correct or if I destroyed something else with it

**Comment by kkopachev** [comment]
This code was added, because pillow prior to version 4.3.0 [could not open](https://pillow.readthedocs.io/en/latest/releasenotes/4.3.0.html#loading-16-bit-tiff-images) 16 bit tiff images. 
I think it's now safe to remove the workaround now.
