### ISSUE TITLE
Cannot Identify Image-tif format

### ISSUE THREAD

**Issue by anask1104** [thumbor/thumbor#1077]
Traceback (most recent call last):
  File "C:\Users\Anas\PycharmProjects\Minorproject\venv\lib\site-packages\keras\utils\data_utils.py", line 578, in get
    inputs = self.queue.get(block=True).get()
  File "C:\Users\Anas\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 608, in get
    raise self._value
  File "C:\Users\Anas\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Anas\PycharmProjects\Minorproject\venv\lib\site-packages\keras\utils\data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "C:\Users\Anas\PycharmProjects\Minorproject\venv\lib\site-packages\keras\preprocessing\image.py", line 1034, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)
  File "C:\Users\Anas\PycharmProjects\Minorproject\venv\lib\site-packages\keras\preprocessing\image.py", line 1438, in _get_batches_of_transformed_samples
    interpolation=self.interpolation)
  File "C:\Users\Anas\PycharmProjects\Minorproject\venv\lib\site-packages\keras\preprocessing\image.py", line 387, in load_img
    img = pil_image.open(path)
  File "C:\Users\Anas\PycharmProjects\Minorproject\venv\lib\site-packages\PIL\Image.py", line 2590, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'E:\\dataset/train\\notslum\\T21HUB_1248_1280_2208_2240.tif'
The above exception was the direct cause of the following exception:

This is showing this error.
I am using Pillow. Please help me out!

**Comment by heynemann** [comment]
@anask1104 you are not even using thumbor (as evidenced by the stack above). Please open an issue with PIL instead.
