### ISSUE TITLE
Unsupported header value None

### ISSUE THREAD

**Issue by altendorfme** [thumbor/thumbor#1191]
### Log Error:
```
usage: /usr/local/bin/cjpeg [switches] [inputfile]
Switches (names may be abbreviated):
  -copy none     Copy no extra markers from source file
  -copy comments Copy only comment markers (default)
  -copy all      Copy all extra markers
  -optimize      Optimize Huffman table (smaller file, but slow compression, enabled by default)
  -progressive   Create progressive JPEG file (enabled by default)
  -revert        Revert to standard defaults (instead of mozjpeg defaults)
  -fastcrush     Disable progressive scan optimization
Switches for modifying the image:
  -crop WxH+X+Y  Crop to a rectangular subarea
  -grayscale     Reduce to grayscale (omit color data)
  -flip [horizontal|vertical]  Mirror image (left-right or top-bottom)
  -perfect       Fail if there is non-transformable edge blocks
  -rotate [90|180|270]         Rotate image (degrees clockwise)
  -transpose     Transpose image
  -transverse    Transverse transpose image
  -trim          Drop non-transformable edge blocks
Switches for advanced users:
  -icc FILE      Embed ICC profile contained in FILE
  -restart N     Set restart interval in rows, or in blocks with B
  -maxmemory N   Maximum memory to use (in kbytes)
  -outfile name  Specify name for output file
  -verbose  or  -debug   Emit debug output
  -version       Print version information and exit
Switches for wizards:
  -scans FILE    Create multi-scan JPEG per script FILE
2019-04-17 13:37:26 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 436, in finish_request
    callback=inner,
  File "/usr/local/lib/python2.7/dist-packages/thumbor/context.py", line 292, in queue
    self._execute_in_foreground(operation, callback)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/context.py", line 283, in _execute_in_foreground
    callback(result)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 429, in inner
    self._write_results_to_client(results, content_type)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 453, in _write_results_to_client
    self.set_header('Content-Type', content_type)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 342, in set_header
    self._headers[name] = self._convert_header_value(value)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 387, in _convert_header_value
    raise TypeError("Unsupported header value %r" % value)
TypeError: Unsupported header value None
```

I am using Mozjpeg by default and not setup set as follows:
```
ln -s /opt/mozjpeg/lib64/ /opt/mozjpeg/lib
ln -s /opt/mozjpeg/bin/jpegtran /usr/local/bin/cjpeg
```

### Operating system
Ubuntu 16.04 LTS
NGINX
Supervisor
Python 2.7
Thumbor 6.7.0

### Your thumbor.conf
```
SECURITY_KEY = 'XYZ'

DETECTORS = [
'thumbor.detectors.face_detector',
'thumbor.detectors.feature_detector'
]

FILTERS = [
'thumbor.filters.brightness',
'thumbor.filters.colorize',
'thumbor.filters.contrast',
'thumbor.filters.rgb',
'thumbor.filters.round_corner',
'thumbor.filters.quality',
'thumbor.filters.noise',
'thumbor.filters.watermark',
'thumbor.filters.equalize',
'thumbor.filters.fill',
'thumbor.filters.sharpen',
'thumbor.filters.strip_exif',
'thumbor.filters.strip_icc',
'thumbor.filters.frame',
'thumbor.filters.grayscale',
'thumbor.filters.rotate',
'thumbor.filters.format',
'thumbor.filters.max_bytes',
'thumbor.filters.convolution',
'thumbor.filters.blur',
'thumbor.filters.extract_focal',
'thumbor.filters.focal',
'thumbor.filters.no_upscale',
'thumbor.filters.saturation',
'thumbor.filters.max_age',
'thumbor.filters.curve',
'thumbor.filters.background_color',
'thumbor.filters.upscale',
'thumbor.filters.proportion',
'thumbor.filters.stretch'
]

OPTIMIZERS = [
'thumbor_plugins.optimizers.pngquant',
'thumbor_plugins.optimizers.mozjpeg'
]

MAX_WIDTH = 0
MAX_HEIGHT = 0
MIN_WIDTH = 1
MIN_HEIGHT = 1
USE_GIFSICLE_ENGINE = True
PNGQUANT_PATH = '/usr/bin/pngquant'
GIFSICLE_PATH = '/usr/bin/gifsicle'
JPEGRECOMPRESS_PATH = '/usr/local/bin/jpeg-recompress'
MAX_AGE = 360 * 60 * 24 * 365
AUTO_WEBP = True
QUALITY = 60
WEBP_QUALITY = 80
ALLOW_UNSAFE_URL = False
ALLOW_OLD_URLS = False
STORAGE_EXPIRATION_SECONDS = 60 * 60 * 24 * 365
RESULT_STORAGE_EXPIRATION_SECONDS = 60 * 60 * 24 * 365
HEALTHCHECK_ROUTE = '/healthcheck'
AUTO_PNG_TO_JPG = False
RESPECT_ORIENTATION = True
ALLOW_ANIMATED_GIFS = True
ALLOW_UNSAFE_URL = False

TC_AWS_ENDPOINT = 'https://sfo2.digitaloceanspaces.com'

STORAGE = 'tc_aws.storages.s3_storage'
TC_AWS_STORAGE_BUCKET = 'XYZ'
TC_AWS_STORAGE_ROOT_PATH = '/i/s'
TC_AWS_STORAGE_SSE = False
TC_AWS_STORAGE_RRS = False

RESULT_STORAGE = 'tc_aws.result_storages.s3_storage'
TC_AWS_RESULT_STORAGE_BUCKET = 'XYZ'
TC_AWS_RESULT_STORAGE_ROOT_PATH = '/i/r'

TC_AWS_MAX_RETRY = 0
TC_AWS_STORE_METADATA = True
TC_AWS_RANDOMIZE_KEYS = True
TC_AWS_ROOT_IMAGE_NAME = 'root_image'
```

**Comment by altendorfme** [comment]
Fixed reinstalling Mozjpeg.
