### ISSUE TITLE
Error with running thumbor

### ISSUE THREAD

**Issue by JohnHenryEden** [thumbor/thumbor#1216]
I tried to start thumbor but turns up with error: pkg_resources.DistributionNotFound: thumbor==6.5.2

**Comment by JohnHenryEden** [comment]
I run on centos 6 and I have upgraded python to 2.7

**Comment by JohnHenryEden** [comment]
full stacktrace:
```
Traceback (most recent call last):
  File "/usr/bin/thumbor", line 6, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2793, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 673, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 576, in resolve
pkg_resources.DistributionNotFound: thumbor==6.5.2
```

**Comment by okor** [comment]
^ As indicated by the comment above, the issue seems have been solved. The solution being `install thumbor via pip or use a prebuilt docker image`.
