### ISSUE TITLE
Error when using filter:fill(blur)

### ISSUE THREAD

**Issue by ekapratama93** [thumbor/thumbor#1223]
### Thumbor request URL
http://example:8888/unsafe/fit-in/300x300/filters:fill(auto)/https://github.com/thumbor/thumbor/wiki/tom_before_brightness.jpg

### Expected behaviour
Should be able to return as the [doc](https://thumbor.readthedocs.io/en/latest/filling.html)

### Actual behaviour
Got Error 
2019-10-07 09:20:28 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python2.7/site-packages/thumbor/transformer.py", line 138, in smart_detect
    self.do_image_operations()
  File "/usr/local/lib/python2.7/site-packages/thumbor/transformer.py", line 232, in do_image_operations
    callback=inner
  File "/usr/local/lib/python2.7/site-packages/thumbor/context.py", line 292, in queue
    self._execute_in_foreground(operation, callback)
  File "/usr/local/lib/python2.7/site-packages/thumbor/context.py", line 283, in _execute_in_foreground
    callback(result)
  File "/usr/local/lib/python2.7/site-packages/thumbor/transformer.py", line 228, in inner
    self.done_callback()
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 263, in after_transform
    self.filters_runner.apply_filters(thumbor.filters.PHASE_POST_TRANSFORM, self.finish_request)
  File "/usr/local/lib/python2.7/site-packages/thumbor/filters/__init__.py", line 91, in apply_filters
    exec_one_filter()
  File "/usr/local/lib/python2.7/site-packages/thumbor/filters/__init__.py", line 90, in exec_one_filter
    f.run(exec_one_filter)
  File "/usr/local/lib/python2.7/site-packages/thumbor/filters/__init__.py", line 202, in run
    results.append(self.runnable_method(*self.params))
  File "/usr/local/lib/python2.7/site-packages/thumbor/filters/__init__.py", line 23, in wrapper
    return fn(self, *args2)
  File "/usr/local/lib/python2.7/site-packages/thumbor/filters/fill.py", line 37, in fill
    self.fill_engine.image = self.fill_engine.gen_image((bx, by), '#%s' % color)
  File "/usr/local/lib/python2.7/site-packages/thumbor/engines/pil.py", line 64, in gen_image
    img = Image.new("RGBA", size, color)
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 2384, in new
    color = ImageColor.getcolor(color, mode)
  File "/usr/local/lib/python2.7/site-packages/PIL/ImageColor.py", line 148, in getcolor
    color, alpha = getrgb(color), 255
  File "/usr/local/lib/python2.7/site-packages/PIL/ImageColor.py", line 133, in getrgb
    raise ValueError("unknown color specifier: %r" % color)
ValueError: unknown color specifier: u'#blur'

### Operating system
Thumbor version 6.7.0 on Debian Docker

**Comment by ekapratama93** [comment]
We use 6.7.0 and not realize that fill with blur is not yet released.
