### ISSUE TITLE
Windows 10/Python neophyte:  Can't even install

### ISSUE THREAD

**Issue by TigersWay** [thumbor/thumbor#1286]
### Thumbor request URL
NA
### Expected behaviour
A nice and working thumbor instance :-)

### Actual behaviour
Python just installed, nothing done with it.
```
> python -V
Python 3.7.7
```
```
> pip install thumbor
...
Successfully installed Pillow-6.2.2 argparse-1.4.0 derpconf-0.8.3 futures-3.1.1 libthumbor-2.0.1 pycurl-7.43.0.5 pytz-2019.3 six-1.14.0 statsd-3.3.0 thumbor-6.7.5 tornado-5.1.1 webcolors-1.11.1
```
```
> thumbor
Traceback (most recent call last):
  File "D:\Python\Python37\Scripts\thumbor-script.py", line 11, in <module>
    load_entry_point('thumbor==6.7.5', 'console_scripts', 'thumbor')()
  File "d:\python\python37\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "d:\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "d:\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "d:\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "d:\python\python37\lib\site-packages\thumbor\server.py", line 22, in <module>
    from tornado.netutil import bind_unix_socket
ImportError: cannot import name 'bind_unix_socket' from 'tornado.netutil' (d:\python\python37\lib\site-packages\tornado\netutil.py)
```
### Operating system
Windows 10 (1903)

### Your thumbor.conf
NA

**Comment by kkopachev** [comment]
Few things.
Python3 supported only in thumbor 7 (alpha currently)
Windows as a host OS was never supported

Just run in docker if windows is a must.

**Comment by TigersWay** [comment]
Thanks for your answers, even if I believe that a little warning in your README about platform(s) would be nice.

And for Python 3, the exact quote is:
> Thumbor v7.0.0 and later only supports python 3.7+

which - in my English - means Thumbor 7 does not support Python 2.x, not that Thumbor 6.x does not support Python 3.
