### ISSUE TITLE
Test suite failures on Debian Buster + python3

### ISSUE THREAD

**Issue by gi11es** [thumbor/thumbor#1326]
I'm trying to get Thumbor running under this environment (Buster and only Python 3), and with the following Dockerfile I still have errors and failures (listed below):

```
FROM debian:buster

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y python3 libssl-dev libcurl4-openssl-dev redis memcached imagemagick build-essential cython3 webp ffmpeg gifsicle exiftool libjpeg-turbo-progs libcairo2 python3-distutils curl git
WORKDIR /root
RUN git clone https://github.com/thumbor/thumbor
WORKDIR /root/thumbor
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3 get-pip.py
RUN pip3 install pycurl sentry_sdk celery remotecv colorama setuptools pytest pyssim cairosvg preggy mock nose
RUN pip3 install .
RUN python3 setup.py build_ext -i
RUN make redis && python3 -m "nose"
```

```
............/usr/lib/python3.7/asyncio/events.py:88: RuntimeWarning: coroutine 'QueuedDetector.detect' was never awaited
  self._context.run(self._callback, *self._args)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
.......FE...............................S...............................................................................................................F.F.......................gifsicle: warning: trivial adaptive palette (only 199 colors in source)
.......gifsicle: warning: trivial adaptive palette (only 199 colors in source)
.gifsicle: warning: trivial adaptive palette (only 199 colors in source)
.gifsicle: warning: trivial adaptive palette (only 199 colors in source)
....................................................................................................................................................................................................................................................../usr/local/lib/python3.7/dist-packages/nose/case.py:198: RuntimeWarning: coroutine 'test_can_get_threadpool_instance' was never awaited
  self.test(*self.arg)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
./usr/local/lib/python3.7/dist-packages/nose/case.py:198: RuntimeWarning: coroutine 'test_can_run_task_in_foreground' was never awaited
  self.test(*self.arg)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
./usr/local/lib/python3.7/dist-packages/nose/case.py:198: RuntimeWarning: coroutine 'test_can_run_task_in_foreground_and_exception_happens' was never awaited
  self.test(*self.arg)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
./usr/local/lib/python3.7/dist-packages/nose/case.py:198: RuntimeWarning: coroutine 'test_queueing_task_when_no_pool_runs_sync' was never awaited
  self.test(*self.arg)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
./usr/local/lib/python3.7/dist-packages/nose/case.py:198: RuntimeWarning: coroutine 'test_queueing_task_when_no_pool_runs_sync_and_exception_happens' was never awaited
  self.test(*self.arg)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
./usr/local/lib/python3.7/dist-packages/nose/case.py:198: RuntimeWarning: coroutine 'test_can_run_async' was never awaited
  self.test(*self.arg)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
./usr/local/lib/python3.7/dist-packages/nose/case.py:198: RuntimeWarning: coroutine 'test_can_run_async_with_queue' was never awaited
  self.test(*self.arg)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
./usr/local/lib/python3.7/dist-packages/nose/case.py:198: RuntimeWarning: coroutine 'test_can_cleanup_pool' was never awaited
  self.test(*self.arg)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
..................................
======================================================================
ERROR: test_convert_svg_already_converted_to_png (tests.engines.test_base_engine.BaseEngineTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 1630, in feed
    self.parser.Parse(data, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/thumbor/tests/engines/test_base_engine.py", line 163, in test_convert_svg_already_converted_to_png
    png_buffer_dupe = self.engine.convert_svg_to_png(png_buffer)
  File "/root/thumbor/thumbor/engines/__init__.py", line 161, in convert_svg_to_png
    bytestring=buffer, dpi=self.context.config.SVG_DPI
  File "/usr/local/lib/python3.7/dist-packages/cairosvg/__init__.py", line 60, in svg2png
    output_width=output_width, output_height=output_height)
  File "/usr/local/lib/python3.7/dist-packages/cairosvg/surface.py", line 129, in convert
    **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/cairosvg/parser.py", line 392, in __init__
    forbid_external=not unsafe)
  File "/usr/local/lib/python3.7/dist-packages/defusedxml/common.py", line 131, in fromstring
    parser.feed(text)
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 1632, in feed
    self._raiseerror(v)
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 1531, in _raiseerror
    raise err
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

======================================================================
FAIL: test_convert_not_well_formed_svg_to_png (tests.engines.test_base_engine.BaseEngineTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 1630, in feed
    self.parser.Parse(data, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/thumbor/tests/engines/test_base_engine.py", line 173, in test_convert_not_well_formed_svg_to_png
    self.engine.convert_svg_to_png(buffer)
  File "/root/thumbor/thumbor/engines/__init__.py", line 161, in convert_svg_to_png
    bytestring=buffer, dpi=self.context.config.SVG_DPI
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/thumbor/tests/engines/test_base_engine.py", line 173, in test_convert_not_well_formed_svg_to_png
    self.engine.convert_svg_to_png(buffer)
  File "/usr/local/lib/python3.7/dist-packages/preggy/core.py", line 169, in __exit__
    exc_type.__name__
AssertionError: Expected "xml.etree.ElementTree.ParseError" to happen but "xml.etree.ElementTree.ParseError" happened during execution of with block.

======================================================================
FAIL: test_should_exec_other_operations_on_error_on_engine_exception (tests.handlers.test_base_handler.EngineLoadException)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tornado/testing.py", line 98, in __call__
    result = self.orig_method(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tornado/testing.py", line 600, in post_coroutine
    functools.partial(coro, self, *args, **kwargs), timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 530, in run_sync
    return future_cell[0].result()
  File "/root/thumbor/tests/handlers/test_base_handler.py", line 1251, in test_should_exec_other_operations_on_error_on_engine_exception
    expect(response.code).to_equal(200)
  File "/usr/local/lib/python3.7/dist-packages/preggy/core.py", line 285, in _assert_topic
    return _registered_assertions[method_name](self.topic, *args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/preggy/core.py", line 58, in wrapper
    func(*args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/preggy/core.py", line 126, in test_assertion
    raise AssertionError(err_msg)
AssertionError: Expected topic(500) to equal 200
-------------------- >> begin captured logging << --------------------
asyncio: DEBUG: Using selector: EpollSelector
thumbor: DEBUG: METRICS: inc: response.count:1
thumbor: DEBUG: METRICS: inc: storage.miss:1
PIL.PngImagePlugin: DEBUG: STREAM b'IHDR' 16 13
PIL.PngImagePlugin: DEBUG: STREAM b'gAMA' 41 4
PIL.PngImagePlugin: DEBUG: STREAM b'cHRM' 57 32
PIL.PngImagePlugin: DEBUG: STREAM b'bKGD' 101 6
PIL.PngImagePlugin: DEBUG: b'bKGD' 101 6 (unknown)
PIL.PngImagePlugin: DEBUG: STREAM b'IDAT' 119 37
PIL.PngImagePlugin: DEBUG: STREAM b'tEXt' 168 37
PIL.PngImagePlugin: DEBUG: STREAM b'tEXt' 217 37
thumbor: ERROR: ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/root/thumbor/thumbor/handlers/imaging.py", line 97, in get
    return await self.check_image(kw)
  File "/root/thumbor/thumbor/handlers/imaging.py", line 94, in check_image
    return await self.execute_image_operations()
  File "/root/thumbor/thumbor/handlers/__init__.py", line 173, in execute_image_operations
    await self.get_image()
  File "/root/thumbor/thumbor/handlers/__init__.py", line 259, in get_image
    await self.context.transformer.transform()
  File "/root/thumbor/thumbor/transformer.py", line 38, in transform
    await self.do_image_operations()
  File "/root/thumbor/thumbor/transformer.py", line 212, in do_image_operations
    await self.context.thread_pool.queue(operation=self.img_operation_worker,)
  File "/root/thumbor/thumbor/threadpool.py", line 52, in queue
    return await self._execute_in_foreground(operation, *args)
  File "/root/thumbor/thumbor/threadpool.py", line 44, in _execute_in_foreground
    return operation(*args)
  File "/root/thumbor/thumbor/transformer.py", line 229, in img_operation_worker
    self.fit_in_resize()
  File "/root/thumbor/thumbor/transformer.py", line 387, in fit_in_resize
    self.engine.resize(resize_width, resize_height)
  File "/root/thumbor/thumbor/engines/pil.py", line 151, in resize
    self.image = self.image.resize(size, resample)
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 1929, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be > 0

tornado.access: ERROR: 500 GET /unsafe/fit-in/134x134/filters:equalize()/940x2.png (127.0.0.1) 3.03ms
thumbor: DEBUG: METRICS: timing: response.time:2
thumbor: DEBUG: METRICS: timing: response.time.500:2
thumbor: DEBUG: METRICS: inc: response.status.500:1
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_should_release_ioloop_on_error_on_engine_exception (tests.handlers.test_base_handler.EngineLoadException)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tornado/testing.py", line 98, in __call__
    result = self.orig_method(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tornado/testing.py", line 600, in post_coroutine
    functools.partial(coro, self, *args, **kwargs), timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 530, in run_sync
    return future_cell[0].result()
  File "/root/thumbor/tests/handlers/test_base_handler.py", line 1238, in test_should_release_ioloop_on_error_on_engine_exception
    expect(response.code).to_equal(200)
  File "/usr/local/lib/python3.7/dist-packages/preggy/core.py", line 285, in _assert_topic
    return _registered_assertions[method_name](self.topic, *args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/preggy/core.py", line 58, in wrapper
    func(*args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/preggy/core.py", line 126, in test_assertion
    raise AssertionError(err_msg)
AssertionError: Expected topic(500) to equal 200
-------------------- >> begin captured logging << --------------------
asyncio: DEBUG: Using selector: EpollSelector
thumbor: DEBUG: METRICS: inc: response.count:1
thumbor: DEBUG: METRICS: inc: storage.miss:1
PIL.PngImagePlugin: DEBUG: STREAM b'IHDR' 16 13
PIL.PngImagePlugin: DEBUG: STREAM b'gAMA' 41 4
PIL.PngImagePlugin: DEBUG: STREAM b'cHRM' 57 32
PIL.PngImagePlugin: DEBUG: STREAM b'bKGD' 101 6
PIL.PngImagePlugin: DEBUG: b'bKGD' 101 6 (unknown)
PIL.PngImagePlugin: DEBUG: STREAM b'IDAT' 119 37
PIL.PngImagePlugin: DEBUG: STREAM b'tEXt' 168 37
PIL.PngImagePlugin: DEBUG: STREAM b'tEXt' 217 37
thumbor: ERROR: ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/root/thumbor/thumbor/handlers/imaging.py", line 97, in get
    return await self.check_image(kw)
  File "/root/thumbor/thumbor/handlers/imaging.py", line 94, in check_image
    return await self.execute_image_operations()
  File "/root/thumbor/thumbor/handlers/__init__.py", line 173, in execute_image_operations
    await self.get_image()
  File "/root/thumbor/thumbor/handlers/__init__.py", line 259, in get_image
    await self.context.transformer.transform()
  File "/root/thumbor/thumbor/transformer.py", line 38, in transform
    await self.do_image_operations()
  File "/root/thumbor/thumbor/transformer.py", line 212, in do_image_operations
    await self.context.thread_pool.queue(operation=self.img_operation_worker,)
  File "/root/thumbor/thumbor/threadpool.py", line 52, in queue
    return await self._execute_in_foreground(operation, *args)
  File "/root/thumbor/thumbor/threadpool.py", line 44, in _execute_in_foreground
    return operation(*args)
  File "/root/thumbor/thumbor/transformer.py", line 229, in img_operation_worker
    self.fit_in_resize()
  File "/root/thumbor/thumbor/transformer.py", line 387, in fit_in_resize
    self.engine.resize(resize_width, resize_height)
  File "/root/thumbor/thumbor/engines/pil.py", line 151, in resize
    self.image = self.image.resize(size, resample)
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 1929, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be > 0

tornado.access: ERROR: 500 GET /unsafe/fit-in/134x134/940x2.png (127.0.0.1) 1.76ms
thumbor: DEBUG: METRICS: timing: response.time:1
thumbor: DEBUG: METRICS: timing: response.time.500:1
thumbor: DEBUG: METRICS: inc: response.status.500:1
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 486 tests in 28.423s

FAILED (SKIP=1, errors=1, failures=3)
```

Maybe I'm still missing a dependency that indirectly causes the failures, but the errors encountered aren't pointing in any helpful direction.

**Comment by gi11es** [comment]
The last 2 errors about the tests/fixtures/images/940x2.png test file sound like they could be a rounding issue. The initial height is 2px, after asking Thumbor to fit it into 134x134, it might end up asking PIL for an image with 0px height.

It seems like there was an attempt to fix this for Python 3 but or some reason it doesn't work in my case:

https://github.com/thumbor/thumbor/blob/af7954b72c5585b0081e49fd4ae25036fae41806/thumbor/transformer.py#L356-L369

**Comment by gi11es** [comment]
Debian Buster runs Python 3.7.3.

I tried with Python 3.8.2 and 3.9.0 compiled from source and the same errors were still happening.

**Comment by gi11es** [comment]
I realize now that [Tornado 6.1](https://github.com/tornadoweb/tornado/releases/tag/v6.1.0), which this is picking up through pip, just came out. I'll check if downgrading Tornado helps.

**Comment by kkopachev** [comment]
try using `pytest` to run tests. Reproduced in dockerized buster and  `nose` fails, but `pytest` is just fine. Although I installed all test reqs from setup.py too.

**Comment by gi11es** [comment]
Ah, yes, good catch. The following runs the tests successfully. I had to tweak the Makefile slightly, PR incoming.

```
FROM debian:buster

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y python3 libssl-dev libcurl4-openssl-dev redis memcached imagemagick build-essential cython3 webp ffmpeg gifsicle exiftool libjpeg-turbo-progs libcairo2 python3-distutils curl git coreutils libexiv2-dev libboost-python-dev
WORKDIR /root
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3 get-pip.py
RUN git clone -b makefile-python-configurable https://github.com/gi11es/thumbor
WORKDIR /root/thumbor
RUN pip3 install setuptools
RUN pip3 install .[tests]
RUN make PYTHON=python3 test
```
