### ISSUE TITLE
Unable to properly stop Thumbor

### ISSUE THREAD

**Issue by fraenki** [thumbor/thumbor#1444]
### Thumbor request URL
not related to a URL

### Expected behaviour
When shutting down Thumbor using systemd, it should properly exit.

### Actual behaviour
When trying to shutdown down Thumbor it results in the following error message:

```
May 16 15:32:48 thumbor[83172]: 2022-05-16 15:32:48 thumbor:WARNING Caught signal: 15. Shutting down server.
May 16 15:32:58 thumbor[83172]: 2022-05-16 15:32:58 tornado.application:ERROR Exception in callback functools.partial(<function signal_handler.<locals>.stop_server at 0x7f4a5b15>
May 16 15:32:58 thumbor[83172]: Traceback (most recent call last):
May 16 15:32:58 thumbor[83172]:   File "/opt/thumbor/venv/lib64/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
May 16 15:32:58 thumbor[83172]:     ret = callback()
May 16 15:32:58 thumbor[83172]:   File "/opt/thumbor/venv/lib64/python3.8/site-packages/thumbor/signal_handler.py", line 38, in stop_server
May 16 15:32:58 thumbor[83172]:     stop_loop(now, now + config.MAX_WAIT_SECONDS_BEFORE_IO_SHUTDOWN)
May 16 15:32:58 thumbor[83172]:   File "/opt/thumbor/venv/lib64/python3.8/site-packages/thumbor/signal_handler.py", line 15, in stop_loop
May 16 15:32:58 thumbor[83172]:     io_loop._callbacks  # pylint: disable=protected-access
May 16 15:32:58 thumbor[83172]: AttributeError: 'AsyncIOMainLoop' object has no attribute '_callbacks'
```

I'm using [this systemd service file](https://github.com/markt-de/puppet-thumbor/blob/master/templates/thumbor.systemd.erb).

### Operating system
Rocky Linux 8.5 (rebuild of RHEL 8)
Python 3.8.8
Thumbor 7.0.9

### Your thumbor.conf
Your config file (WARNING: replace your SECURITY_KEY key with a dummy key or your key will become public)

```
ALLOW_OLD_URLS = 'False'
ALLOW_UNSAFE_URL = 'False'
AUTO_WEBP = 'True'
ENGINE_THREADPOOL_SIZE = 4
ERROR_FILE_LOGGER = 'none'
FILE_LOADER_ROOT_PATH = '/opt/foo/example/source'
FILE_STORAGE_ROOT_PATH = '/opt/foo/example/storage'
HTTP_LOADER_MAX_CLIENTS = 1024
LOADER = 'thumbor.loaders.file_loader'
MAX_WAIT_SECONDS_BEFORE_IO_SHUTDOWN = 10
MAX_WAIT_SECONDS_BEFORE_SERVER_SHUTDOWN = 10
RESPECT_ORIENTATION = 'True'
RESULT_STORAGE = 'thumbor.result_storages.file_storage'
RESULT_STORAGE_EXPIRATION_SECONDS = 0
RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '/opt/foo/example/result'
RESULT_STORAGE_STORES_UNSAFE = 'False'
STORAGE = 'thumbor.storages.file_storage'
STORAGE_EXPIRATION_SECONDS = 15552000
STORES_CRYPTO_KEY_FOR_EACH_IMAGE = 'False'
UPLOAD_DEFAULT_FILENAME = 'example_filename'
UPLOAD_DELETE_ALLOWED = 'False'
UPLOAD_ENABLED = 'False'
UPLOAD_MAX_SIZE = 512000
UPLOAD_PUT_ALLOWED = 'False'
```

**Comment by fraenki** [comment]
still relevant

**Comment by fraenki** [comment]
still relevant

**Comment by fraenki** [comment]
still relevant

**Comment by fraenki** [comment]
still relevant

**Comment by fraenki** [comment]
still relevant

**Comment by fraenki** [comment]
still relevant
