### ISSUE TITLE
Thumbor fails to deliver image: TypeError: write() argument must be str

### ISSUE THREAD

**Issue by fraenki** [thumbor/thumbor#1445]
### Thumbor request URL
https://thumbor.example.com/HASH/fit-in/750x589/path/to/testimage

### Expected behaviour
Thumbor should reply to this URL with a 200 HTTP code and deliver the requested image.

### Actual behaviour
When requesting the image for the _first time_, Thumbor logs the following error:

```
May 16 15:57:01 thumbor[804812]: 2022-05-16 15:57:01 thumbor:ERROR ERROR: Traceback (most recent call last):
May 16 15:57:01 thumbor[804812]:  File "/opt/thumbor/venv/lib64/python3.8/site-packages/thumbor/handlers/__init__.py", line 212, in get_image
May 16 15:57:01 thumbor[804812]:    result = await self._fetch(self.context.request.image_url)
May 16 15:57:01 thumbor[804812]:  File "/opt/thumbor/venv/lib64/python3.8/site-packages/thumbor/handlers/__init__.py", line 876, in _fetch
May 16 15:57:01 thumbor[804812]:    raise fetch_result.exception
May 16 15:57:01 thumbor[804812]:  File "/opt/thumbor/venv/lib64/python3.8/site-packages/thumbor/handlers/__init__.py", line 870, in _fetch
May 16 15:57:01 thumbor[804812]:    await storage.put_crypto(url)
May 16 15:57:01 thumbor[804812]:  File "/opt/thumbor/venv/lib64/python3.8/site-packages/thumbor/storages/file_storage.py", line 59, in put_crypto
May 16 15:57:01 thumbor[804812]:    _file.write(self.context.server.security_key)
May 16 15:57:01 thumbor[804812]: TypeError: write() argument must be str, not bytes
May 16 15:57:01 thumbor[804812]: 2022-05-16 15:57:01 thumbor:ERROR [BaseHandler] get_image failed for url `path/to/testimage`. error: `write() argument must be str, not bytes`
May 16 15:57:01 thumbor[804812]: 2022-05-16 15:57:01 tornado.access:ERROR 500 GET /HASH/fit-in/750x589/path/to/testimage (172.16.1.1) 78.97ms
```

As a result the HTTP request is answered with a 500 error code and an empty response (0 byte). However, the next attempt to get the image URL usually succeeds.

Everything is hosted on NFS storage: the source of the image (FILE_LOADER_ROOT_PATH), Thumbors storage (FILE_STORAGE_ROOT_PATH) and the result storage (RESULT_STORAGE_FILE_STORAGE_ROOT_PATH).

This was working great. However, after upgrading to Thumbor 7 it take at least two requests until Thumbor successfully delivers the requested image.

It looks like a timing issue to me, Thumbor tries to read the file from FILE_STORAGE_ROOT_PATH before it was (fully) saved. As already stated, this is NFS storage so the latency is higher.

### Operating system
Rocky Linux 8.5 (rebuild of RHEL 8)
Python 3.8.8
Thumbor 7.0.9

### Your thumbor.conf
```
ALLOW_OLD_URLS = 'False'
ALLOW_UNSAFE_URL = 'False'
AUTO_WEBP = 'True'
ENGINE_THREADPOOL_SIZE = 4
ERROR_FILE_LOGGER = 'none'
FILE_LOADER_ROOT_PATH = '/opt/foo/example/source'
FILE_STORAGE_ROOT_PATH = '/opt/foo/example/storage'
HTTP_LOADER_MAX_CLIENTS = 1024
LOADER = 'thumbor.loaders.file_loader'
MAX_WAIT_SECONDS_BEFORE_IO_SHUTDOWN = 10
MAX_WAIT_SECONDS_BEFORE_SERVER_SHUTDOWN = 10
RESPECT_ORIENTATION = 'True'
RESULT_STORAGE = 'thumbor.result_storages.file_storage'
RESULT_STORAGE_EXPIRATION_SECONDS = 0
RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '/opt/foo/example/result'
RESULT_STORAGE_STORES_UNSAFE = 'False'
STORAGE = 'thumbor.storages.file_storage'
STORAGE_EXPIRATION_SECONDS = 15552000
STORES_CRYPTO_KEY_FOR_EACH_IMAGE = 'False'
UPLOAD_DEFAULT_FILENAME = 'example_filename'
UPLOAD_DELETE_ALLOWED = 'False'
UPLOAD_ENABLED = 'False'
UPLOAD_MAX_SIZE = 512000
UPLOAD_PUT_ALLOWED = 'False'
```

**Comment by fraenki** [comment]
still relevant

**Comment by fraenki** [comment]
still relevant

**Comment by fraenki** [comment]
still relevant

**Comment by fraenki** [comment]
Still relevant, waiting for https://github.com/thumbor/thumbor/pull/1470 to be merged.
