### ISSUE TITLE
Thumbor 7.0.10: can't convert to WEBP

### ISSUE THREAD

**Issue by ook** [thumbor/thumbor#1458]
Using **thumbor 7.0.10**

### Thumbor request URL

http://localhost:8888/P5cyKZeWZIYV9xIsULLkrDPOPUU=/516x516/filters:format(webp)/https://files.cults3d.com/uploaders/16290889/illustration-file/8840d4b0-5264-4cf2-abf1-5a5270ea9957/Circle_01.jpg

### Expected behaviour

Filters should be applied and the transformed image displayed

### Actual behaviour

Blank screen returned. Error in the logs:

```
thumbor_1  | 2022-06-21 12:00:30 thumbor:ERROR [BaseHander.finish_request] 'WEBP'
thumbor_1  | Traceback (most recent call last):
thumbor_1  |   File "/usr/local/lib/python3.10/site-packages/thumbor/handlers/__init__.py", line 566, in finish_request
thumbor_1  |     result = await self.context.thread_pool.queue(
thumbor_1  |   File "/usr/local/lib/python3.10/site-packages/thumbor/threadpool.py", line 53, in queue
thumbor_1  |     return await self._execute_in_foreground(operation, *args)
thumbor_1  |   File "/usr/local/lib/python3.10/site-packages/thumbor/threadpool.py", line 45, in _execute_in_foreground
thumbor_1  |     return operation(*args)
thumbor_1  |   File "/usr/local/lib/python3.10/site-packages/thumbor/handlers/__init__.py", line 486, in _load_results
thumbor_1  |     results = context.request.engine.read(image_extension, quality)
thumbor_1  |   File "/usr/local/lib/python3.10/site-packages/thumbor/engines/pil.py", line 304, in read
thumbor_1  |     self.image.save(img_buffer, self.image.format, **options)
thumbor_1  |   File "/usr/local/lib/python3.10/site-packages/PIL/Image.py", line 2201, in save
thumbor_1  |     save_handler = SAVE[format.upper()]
thumbor_1  | KeyError: 'WEBP'
thumbor_1  | 2022-06-21 12:00:30 thumbor:WARNING Error while trying to fetch the image: 'WEBP'
thumbor_1  | 2022-06-21 12:00:30 tornado.access:ERROR 500 GET /P5cyKZeWZIYV9xIsULLkrDPOPUU=/516x516/filters:format(webp)/https://files.cults3d.com/uploaders/16290889/illustration-file/8840d4b0-5264-4cf2-abf1-5a5270ea9957/Circle_01.jpg (172.22.0.1) 420.21ms
```

Please note that the Webp plugin is correctly detected:

```
thumbor_1  | 2022-06-21 14:12:54 thumbor:DEBUG Image format set by AUTO_WEBP as .webp.
thumbor_1  | 2022-06-21 14:12:54 thumbor:DEBUG Content Type of image/webp detected.
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing BlpImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing BmpImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing BufrStubImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing CurImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing DcxImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing DdsImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing EpsImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing FitsStubImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing FliImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing FpxImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Image: failed to import FpxImagePlugin: No module named 'olefile'
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing FtexImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing GbrImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing GifImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing GribStubImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing Hdf5StubImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing IcnsImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing IcoImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing ImImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing ImtImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing IptcImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing JpegImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing Jpeg2KImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing McIdasImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing MicImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Image: failed to import MicImagePlugin: No module named 'olefile'
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing MpegImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing MpoImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing MspImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing PalmImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing PcdImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing PcxImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing PdfImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing PixarImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing PngImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing PpmImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing PsdImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing SgiImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing SpiderImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing SunImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing TgaImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing TiffImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing WebPImagePlugin  <<<<------------
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing WmfImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing XbmImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing XpmImagePlugin
thumbor_1  | 2022-06-21 14:12:54 PIL.Image:DEBUG Importing XVThumbImagePlugin
```

### Operating system
Alpine 3.16 (docker image, thumbor-aws included)

### Your thumbor.conf
```
LOADER = "thumbor.loaders.https_loader"
AWS_LOADER_BUCKET_NAME = "loader"
AWS_LOADER_S3_ENDPOINT_URL = "http://minio:9000"
AWS_LOADER_S3_SECRET_ACCESS_KEY = "12345678"
AWS_LOADER_S3_ACCESS_KEY_ID = "admin"

STORAGE = "thumbor_aws.storage"
AWS_STORAGE_BUCKET_NAME = "storage"
AWS_STORAGE_S3_ENDPOINT_URL = "http://minio:9000"
AWS_STORAGE_S3_SECRET_ACCESS_KEY = "12345678"
AWS_STORAGE_S3_ACCESS_KEY_ID = "admin"

RESULT_STORAGE = "thumbor_aws.result_storage"
AWS_RESULT_STORAGE_BUCKET_NAME = "result"
AWS_RESULT_STORAGE_S3_ENDPOINT_URL = "http://minio:9000"
AWS_RESULT_STORAGE_S3_SECRET_ACCESS_KEY = "12345678"
AWS_RESULT_STORAGE_S3_ACCESS_KEY_ID = "admin"

ALLOWED_SOURCES = ['assets.cults3d.com', 'files.cults3d.com']
SECURITY_KEY = "<SNIPPED>"
RESPECT_ORIENTATION = "True"
RESULT_STORAGE_STORES_UNSAFE = "True"
ALLOW_UNSAFE_URL = "False"
AUTO_WEBP = "False"
MAX_AGE_TEMP_IMAGE = "31556952"
MAX_AGE = "31556952"
THUMBOR_PORT = "80"

USE_ENVIRONMENT = "False"
DEBUG_MODE = "True"
LOG_LEVEL = "debug"
```

**Comment by ook** [comment]
For debugging, here the Dockerfile:

```
FROM python:3.10-alpine3.16

RUN apk add --no-cache make automake gcc g++ python3-dev v4l-utils-dev linux-headers
RUN python -m pip install --upgrade pip
RUN pip install thumbor==7.0.10

# Install thumbor-aws
RUN apk add --no-cache curl-dev
RUN python -m pip install thumbor_aws

RUN pip uninstall -y pillow || true
RUN apk add --no-cache jpeg-dev zlib-dev
RUN CC="cc -mavx2" pip install -U --force-reinstall pillow-simd
RUN python -c "from PIL import Image; print(Image.__version__)" && pip list

RUN apk add tiff-dev jpeg-dev openjpeg-dev zlib-dev freetype-dev lcms2-dev \
    libwebp-dev tcl-dev tk-dev harfbuzz-dev fribidi-dev libimagequant-dev \
    libxcb-dev libpng-dev ca-certificates ffmpeg libwebp libwebp-tools gifsicle

ENTRYPOINT thumbor -d -p 80 -l debug -c /thumbor/thumbor.conf/thumbor.conf
```
