### ISSUE TITLE
500 for source JP2 images

### ISSUE THREAD

**Issue by Lathanderjk** [thumbor/thumbor#1467]
### Thumbor request URL
http://ip:8888/unsafe/fit-in/160x160/web/sub/domain/images/shop-active-images/fj_58075_02.jpg

### Expected behaviour
working image with 200 code

### Actual behaviour
500 code

### Operating system
RHEL 8.6

### Your thumbor.conf
THUMBOR_LOG_FORMAT = '%(name)s:%(levelname)s %(message)s'
QUALITY = 80
WEBP_QUALITY = 80
AUTO_WEBP = True
MAX_AGE = 7776000
ENGINE_THREADPOOL_SIZE = 2
METRICS = 'thumbor.metrics.statsd_metrics'
LOADER = 'thumbor.loaders.file_loader'
STORAGE = 'thumbor.storages.no_storage'
RESULT_STORAGE = None
STATSD_HOST = '127.0.0.1'
STATSD_PREFIX = 'thumbor'
FILE_LOADER_ROOT_PATH = '/data'

#### Error log
 thumbor:ERROR ERROR: Traceback (most recent call last):
   File "/usr/local/lib64/python3.9/site-packages/thumbor/handlers/__init__.py", line 212, in get_image
     result = await self._fetch(self.context.request.image_url)
   File "/usr/local/lib64/python3.9/site-packages/thumbor/handlers/__init__.py", line 876, in _fetch
     raise fetch_result.exception
   File "/usr/local/lib64/python3.9/site-packages/thumbor/handlers/__init__.py", line 844, in _fetch
     self.context.request.engine.load(fetch_result.buffer, extension)
   File "/usr/local/lib64/python3.9/site-packages/thumbor/engines/__init__.py", line 195, in load
     image_or_frames = self.create_image(buffer)
   File "/usr/local/lib64/python3.9/site-packages/thumbor/engines/pil.py", line 84, in create_image
     self.subsampling = JpegImagePlugin.get_sampling(img)
   File "/usr/local/lib64/python3.9/site-packages/PIL/JpegImagePlugin.py", line 624, in get_sampling
     sampling = im.layer[0][1:3] + im.layer[1][1:3] + im.layer[2][1:3]
   File "/usr/local/lib64/python3.9/site-packages/PIL/Image.py", line 548, in __getattr__
     raise AttributeError(name)
 AttributeError: layer
 thumbor:ERROR [BaseHandler] get_image failed for url `web/sub/golfuniverse.sk/images/shop-active-images/fj_58075_02.jpg`. error: `layer`
 tornado.access:ERROR 500 HEAD /unsafe/fit-in/160x160/web/sub/golfuniverse.sk/images/shop-active-images/fj_58075_02.jpg (10.1.1.84) 1.30ms

### Original image info
fj_58075_02.jpg JP2 1024x1024 1024x1024+0+0 8-bit sRGB 0.000u 0:00.000

**Comment by scorphus** [comment]
Thanks for reporting, @Lathanderjk. A fix is in the oven.
