### ISSUE TITLE
Unable to install thumbor 7.1.1 anymore

### ISSUE THREAD

**Issue by storm1er** [thumbor/thumbor#1549]
### Thumbor request URL
Not applicable

### Expected behaviour
```bash
# Running in docker so there's nothing outside that could create a side-effect
docker run -it --rm python:3.8-buster
pip3 install --upgrade pip && pip3 install pycurl && pip3 install thumbor===7.1.1
```

We expect a successful install

### Actual behaviour

![image](https://user-images.githubusercontent.com/9821946/217504386-f4734741-99b6-4c7e-add9-1f25b8ec57ae.png)

Full output:
<details>

```bash

Collecting thumbor===7.1.1
  Downloading thumbor-7.1.1.tar.gz (29.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.3/29.3 MB 3.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [70 lines of output]
      error in thumbor setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-d35n_v07/overlay/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 35, in __init__
          parsed = parse_requirement(requirement_string)
        File "/tmp/pip-build-env-d35n_v07/overlay/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 64, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
        File "/tmp/pip-build-env-d35n_v07/overlay/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 82, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokenizer)
        File "/tmp/pip-build-env-d35n_v07/overlay/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 126, in _parse_requirement_details
          marker = _parse_requirement_marker(
        File "/tmp/pip-build-env-d35n_v07/overlay/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 147, in _parse_requirement_marker
          tokenizer.raise_syntax_error(
        File "/tmp/pip-build-env-d35n_v07/overlay/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 163, in raise_syntax_error
          raise ParserSyntaxError(
      pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier)
          py3exiv2>=0.*,<0.7.2
                  ~~~^
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/tmp/pip-build-env-d35n_v07/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 291, in check_extras
          list(itertools.starmap(_check_extra, value.items()))
        File "/tmp/pip-build-env-d35n_v07/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 304, in _check_extra
          list(_reqs.parse(reqs))
        File "/tmp/pip-build-env-d35n_v07/overlay/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3095, in __init__
          super(Requirement, self).__init__(requirement_string)
        File "/tmp/pip-build-env-d35n_v07/overlay/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 37, in __init__
          raise InvalidRequirement(str(e)) from e
      pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
          py3exiv2>=0.*,<0.7.2
                  ~~~^
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/tmp/pip-build-env-d35n_v07/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-d35n_v07/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 475, in __init__
          _Distribution.__init__(
        File "/tmp/pip-build-env-d35n_v07/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-d35n_v07/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 904, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-d35n_v07/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 924, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-build-env-d35n_v07/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 293, in check_extras
          raise DistutilsSetupError(
      distutils.errors.DistutilsSetupError: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 158, in <module>
        File "<string>", line 90, in run_setup
        File "/tmp/pip-build-env-d35n_v07/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-d35n_v07/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 152, in setup
          raise SystemExit("error in {} setup command: {}".format(attrs['name'], msg))
      SystemExit: error in thumbor setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      
      
      ******************************************************************
      
      
      ******************************************************************
      Couldn't build one or more native extensions, skipping compilation.
      
      
      error in thumbor setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

</details>

### Operating system
Uses docker image `python:3.8-buster`

### Your thumbor.conf
Not applicable

**Comment by storm1er** [comment]
https://discuss.python.org/t/should-we-permit-with-more-comparision-operators-in-version-specifiers/22782

https://github.com/thumbor/thumbor/blob/7.1.1/setup.py#L50

Solution if you really need to stay with 7.1.1 (ar another):

```bash
docker run -it --rm python:3.8-buster
pip3 install --upgrade pip && pip3 install pycurl && pip3 download thumbor===7.1.1
# edit setup.py
pip3 install /path/to/custom/thumbor
```
