### ISSUE TITLE
thumbor-doctor error with default config

### ISSUE THREAD

**Issue by hp197** [thumbor/thumbor#1564]
### Issue

Thumbor-doctor should not produce an error with default config

### Actual behaviour
```Using configuration file found at /tmp/test.conf

Thumbor v7.4.7 (of 26-Jan-2023)

Thumbor doctor will analyze your install and verify if everything is working as expected.

Verifying libraries support...

✅ pycurl is installed correctly.
✅ cairosvg is installed correctly.

Verifying thumbor compiled extensions...

✅ _alpha
✅ _bounding_box
✅ _brightness
✅ _colorize
✅ _composite
✅ _contrast
✅ _convolution
✅ _curve
✅ _equalize
✅ _fill
✅ _nine_patch
✅ _noise
✅ _rgb
✅ _round_corner
✅ _saturation
✅ _sharpen

Verifying extensibility modules found in your thumbor.conf...

✅ thumbor.storages.file_storage
✅ thumbor.loaders.http_loader
Traceback (most recent call last):
  File "/usr/local/bin/thumbor-doctor", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/thumbor/doctor.py", line 483, in main
    run_doctor(options, print_version=True, exit_with_error=True)
  File "/usr/local/lib/python3.9/dist-packages/thumbor/doctor.py", line 472, in run_doctor
    warnings, errors = check_everything(cfg)
  File "/usr/local/lib/python3.9/dist-packages/thumbor/doctor.py", line 430, in check_everything
    errors += check_extensibility_modules(cfg)
  File "/usr/local/lib/python3.9/dist-packages/thumbor/doctor.py", line 165, in check_extensibility_modules
    import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 118, in import_module
    if name.startswith('.'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

### Operating system
Debian

### Steps to reproduce

```
thumbor-config > /tmp/test.conf
thumbor-doctor -c /tmp/test.conf
```

**Comment by gdegoulet** [comment]
https://github.com/thumbor/thumbor/pull/1568
