### ISSUE TITLE
Uploading files with 'umlauts' in filename not working

### ISSUE THREAD

**Issue by p4sI** [thumbor/thumbor#1613]
### Thumbor request URL
example.com/images

### Expected behaviour
Image with the name "grün.png" can be uploaded

### Actual behaviour
Thumbor throws an exception:
```
2023-10-31 15:58:37 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
    self.finish()
  File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 1234, in finish
    future = self.flush(include_footers=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 1171, in flush
    return self.request.connection.write_headers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tornado/http1connection.py", line 454, in write_headers
    lines.extend(line.encode("latin1") for line in header_lines)
  File "/usr/local/lib/python3.11/site-packages/tornado/http1connection.py", line 454, in <genexpr>
    lines.extend(line.encode("latin1") for line in header_lines)
                 ^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0308' in position 53: ordinal not in range(256)

2023-10-31 15:58:37 tornado.general:ERROR Cannot send error response after headers written
```

### Operating system
Thumbor is running in Docker using https://github.com/MinimalCompact/thumbor version 7.6.0 

### Your thumbor.conf
default

**Comment by marcelometal** [comment]
Hi @p4sI, I'm sorry for the very long delay in investigating and responding to this report. Thank you for reporting it and including the traceback.

I reproduced the problem and confirmed a bug in how Thumbor builds the `Location` response header: the filename is inserted without URL encoding. This breaks for characters such as the combining diaeresis (`U+0308`) shown in your traceback.

I've opened #1906 to fix this by URL-encoding the filename. The PR includes regression tests for Unicode filenames and reserved URL characters, checking both successful uploads and retrieval through the returned URL. The local unit suite and code-quality checks pass.

The PR is now awaiting review.
