### ISSUE TITLE
fit-in filter causing division by zero exception and HTTP status 500 in some cases

### ISSUE THREAD

**Issue by bondido** [thumbor/thumbor#1621]
Thumbor generates HTTP 500 error status in case the 'fit-in' filter is called on image with some "unusual" proportions - e.g. the attached image 1000px wide and 4px high to be fitted in 50x50 rectangle. Resulting resolution is 20 times smaller - giving 50px width and 0.2px height which rounds to 0, thus causing "ZeroDivisionError" while scaling

### Thumbor request URL
/unsafe/fit-in/50x50/localhost/image-1000x4.jpg

### Expected behaviour
Considering the image resolution (width/height ratio) it should be 50x1px image

### Actual behaviour
HTTP status 500

Thumbor log (from thumbor 7.6.0, but 7.7.1 behaves the same):
> thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/home/thumbor/venv/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/home/thumbor/venv/lib/python3.11/site-packages/thumbor/handlers/imaging.py", line 119, in get
    return await self.check_image(kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thumbor/venv/lib/python3.11/site-packages/thumbor/handlers/imaging.py", line 116, in check_image
    return await self.execute_image_operations()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thumbor/venv/lib/python3.11/site-packages/thumbor/handlers/__init__.py", line 205, in execute_image_operations
    await self.get_image()
  File "/home/thumbor/venv/lib/python3.11/site-packages/thumbor/handlers/__init__.py", line 305, in get_image
    await self.context.transformer.transform()
  File "/home/thumbor/venv/lib/python3.11/site-packages/thumbor/transformer.py", line 38, in transform
    await self.do_image_operations()
  File "/home/thumbor/venv/lib/python3.11/site-packages/thumbor/transformer.py", line 218, in do_image_operations
    await self.context.thread_pool.queue(
  File "/home/thumbor/venv/lib/python3.11/site-packages/thumbor/threadpool.py", line 53, in queue
    return await self._execute_in_foreground(operation, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thumbor/venv/lib/python3.11/site-packages/thumbor/threadpool.py", line 45, in _execute_in_foreground
    return operation(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/thumbor/venv/lib/python3.11/site-packages/thumbor/transformer.py", line 237, in img_operation_worker
    self.fit_in_resize()
  File "/home/thumbor/venv/lib/python3.11/site-packages/thumbor/transformer.py", line 422, in fit_in_resize
    self.engine.resize(resize_width, resize_height)
  File "/home/thumbor/venv/lib/python3.11/site-packages/thumbor/engines/pil.py", line 212, in resize
    self.image.draft(None, size)
  File "/home/thumbor/venv/lib/python3.11/site-packages/PIL/JpegImagePlugin.py", line 441, in draft
    scale = min(self.size[0] // size[0], self.size[1] // size[1])
                                         ~~~~~~~~~~~~~^^~~~~~~~~
ZeroDivisionError: integer division or modulo by zero
tornado.access:ERROR 500 GET ...

### Operating system
docker image built on debian bookworm OS

### Your thumbor.conf
I think it's irrelevant but tested it with my custom config, as well as with the default config generated by `thumbor-conf`

### Sample image
![image-1000x4](https://github.com/thumbor/thumbor/assets/19214089/4cd1c9de-2710-403e-a360-66e3ddfe9a95)


I tried to do some code analysis and found that there is 0px avoidance line in resize function:
https://github.com/thumbor/thumbor/blob/7c5d85435435d4a21c17862efef8afc3f54d0c11/thumbor/transformer.py#L355

...but there is no such avoidance in fit_in_resize function:
https://github.com/thumbor/thumbor/blob/7c5d85435435d4a21c17862efef8afc3f54d0c11/thumbor/transformer.py#L422


Shuldn't it be coded the same way in both cases?

What's more - shouldn't it respect the MIN_WIDTH/MIN_HEIGHT configuration parameters?
https://thumbor.readthedocs.io/en/latest/configuration.html#min-width-and-min-height

**Comment by bondido** [comment]
Still an issue
