### ISSUE TITLE
Thumbor startup error - module 'importlib' has no attribute 'util'

### ISSUE THREAD

**Issue by Manooj-DAZN** [thumbor/thumbor#1678]
### Thumbor request URL
http://localhost:808

### Expected behaviour
Thumbor server should start

### Actual behaviour
IN-W2WGDP7KY3:Downloads manooj.murali$ thumbor
Traceback (most recent call last):
  File "/Users/manooj.murali/Library/Python/3.9/bin/thumbor", line 8, in <module>
    sys.exit(main())
  File "/Users/manooj.murali/Library/Python/3.9/lib/python/site-packages/thumbor/server.py", line 151, in main
    config = get_config(
  File "/Users/manooj.murali/Library/Python/3.9/lib/python/site-packages/thumbor/server.py", line 45, in get_config
    return Config.load(
  File "/Users/manooj.murali/Library/Python/3.9/lib/python/site-packages/derpconf/config.py", line 79, in load
    return cls.__load_from_path(conf, path)
  File "/Users/manooj.murali/Library/Python/3.9/lib/python/site-packages/derpconf/config.py", line 98, in __load_from_path
    module = importlib.util.module_from_spec(spec)
AttributeError: module 'importlib' has no attribute 'util'

### Operating system
OSx (Sonoma 14.5)

### Your thumbor.conf
Not applicable

**Comment by Manooj-DAZN** [comment]
If a solution cannot be provided then please go ahead and close the ticket.
