### ISSUE TITLE
Thumbor not working on Windows 11

### ISSUE THREAD

**Issue by LAinox001** [thumbor/thumbor#1684]
### Thumbor request URL
No URL. Thumbor does just not launch at all.

### Expected behaviour
Should be working.

### Actual behaviour
Not working.

### Operating system
Windows 11

### Your thumbor.conf
Default thumbor.conf

When i install thumbor with `pip install tumbor`, and then launch it with the command `thumbor`, i get the following error :

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Scripts\thumbor.exe\__main__.py", line 4, in <module>
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\thumbor\server.py", line 23, in <module>
    from tornado.netutil import bind_unix_socket
ImportError: cannot import name 'bind_unix_socket' from 'tornado.netutil' (C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\tornado\netutil.py)
```

When doing `thumbor-doctor`, i get the following error :
```
Thumbor v7.7.4 (of 04-Mar-2024)

Thumbor doctor will analyze your install and verify if everything is working as expected.

Verifying libraries support...

✅ pycurl is installed correctly.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\luc.antoni\AppData\Local\Programs\Python\Python311\Scripts\thumbor-doctor.exe\__main__.py", line 7, in <module>
  File "C:\Users\luc.antoni\AppData\Local\Programs\Python\Python311\Lib\site-packages\thumbor\doctor.py", line 486, in main
    run_doctor(options, print_version=True, exit_with_error=True)
  File "C:\Users\luc.antoni\AppData\Local\Programs\Python\Python311\Lib\site-packages\thumbor\doctor.py", line 475, in run_doctor
    warnings, errors = check_everything(cfg)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luc.antoni\AppData\Local\Programs\Python\Python311\Lib\site-packages\thumbor\doctor.py", line 431, in check_everything
    warnings, errors = check_modules()
                       ^^^^^^^^^^^^^^^
  File "C:\Users\luc.antoni\AppData\Local\Programs\Python\Python311\Lib\site-packages\thumbor\doctor.py", line 283, in check_modules
    import_module(module)  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luc.antoni\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\luc.antoni\AppData\Local\Programs\Python\Python311\Lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luc.antoni\AppData\Local\Programs\Python\Python311\Lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Users\luc.antoni\AppData\Local\Programs\Python\Python311\Lib\site-packages\cairocffi\__init__.py", line 60, in <module>
    cairo = dlopen(
            ^^^^^^^
  File "C:\Users\luc.antoni\AppData\Local\Programs\Python\Python311\Lib\site-packages\cairocffi\__init__.py", line 57, in dlopen
    raise OSError(error_message)  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.so.2'
cannot load library 'libcairo.2.dylib': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.2.dylib'
cannot load library 'libcairo-2.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo-2.dll'
```

I tried with python 3.12 and 3.11

**Comment by LAinox001** [comment]
Hello @RaphaelVRossi, i tried, as mentionned in the ticket, with version 3.12 and 3.11

**Comment by RaphaelVRossi** [comment]
@LAinox001 @OK-Diamond I reviewed the logs again, and it looks like Thumbor is complaining about a missing cairo library.
Could you please install cairo using this link (https://www.cairographics.org/download/) and try again?

Sorry for the delay in responding.

**Comment by FelipeSales18** [comment]
Hi @LArox001 👋

I’ve just opened PR #1773 to address this issue.
The fix adds a fallback to standard TCP binding on Windows environments where bind_unix_socket is not available, preventing Thumbor from crashing on startup.

Tested on Windows 11 (PowerShell + WSL2) and Thumbor runs successfully.

Let me know if any adjustments are needed!
