### ISSUE TITLE
Thumbor started returning 404s for images that exist in thumbor/GridFS collections

### ISSUE THREAD

**Issue by cristiangraz** [thumbor/thumbor#229]
I have a production website running thumbor that recently started returning 404 errors for a portion of the images, while the remaining images continue to work.

I've done some debugging and things seem to look okay - the images that return 404s exist in the thumbor and GridFS collections in Mongo - but I can't figure out what's causing the 404's. There haven't been any changes to the server, configurations, or codebase. Any ideas on what the issue might be? Below are the details:

**Versions**:
Debian Wheezy (7.2)
Mongo: 2.0.6-1.1
Thumbor: 3.14.6
python-pymongo: 2.2-4+deb7u1

Here are the two URLs I debugged (note the non-working URL was previously working up until 1-2 days ago):

**Working URL**:
http://site.com/2NF_GAU3DEu1rDcGTzkKcaEw8VI=/525x350/smart/3025cc3bbfcb4528b53b9f440325ef7e/jalapeno-popper-bombs-title.jpg

**Non-Working URL**:
http://site.com/zCg5FizTHeYK_uSFLIZyDJfbq_4=/525x350/smart/bf550b6853b54adaa769443ce4a22960/mac-and-cheese-bombs-title.jpg

Here is the error I see in the thumbor logs for the broken image. The WARNING ERROR seems odd but the url in the second line is correct:

```
2013-12-05 18:52:32 thumbor:WARNING ERROR retrieving image http://bf550b6853b54adaa769443ce4a22960/mac-and-cheese-bombs-title.jpg: [Errno -2] Name or service not known
2013-12-05 18:52:32 tornado.access:WARNING 404 GET /zCg5FizTHeYK_uSFLIZyDJfbq_4=/525x350/smart/bf550b6853b54adaa769443ce4a22960/mac-and-cheese-bombs-title.jpg (127.0.0.1) 18.39ms
2013-12-05 18:52:36 tornado.general:WARNING uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 239, in wrapped
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 158, in <lambda>
    lambda future: callback(future.result()))
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 129, in result
    raise_exc_info(self.__exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 138, in submit
    future.set_result(fn(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/tornado/netutil.py", line 211, in resolve
    addrinfo = socket.getaddrinfo(host, port, family)
gaierror: [Errno -2] Name or service not known
```

I went into Mongo to see the results for the two files. Both seem to be in the thumbor and GridFS Mongo collections and look correct as far as I can tell. Here is the output:

For the file that worked:

``` javascript
> db.images.find({ path : '3025cc3bbfcb4528b53b9f440325ef7e' }, {created_at:1, file_id:1, path:1, _id:0}).pretty()
{
        "created_at" : ISODate("2013-11-06T14:31:00.924Z"),
        "file_id" : ObjectId("527ac32463b07e109f000490"),
        "path" : "3025cc3bbfcb4528b53b9f440325ef7e"
}
> db.fs.files.find({ _id : ObjectId("527ac32463b07e109f000490") }).pretty()
{
        "_id" : ObjectId("527ac32463b07e109f000490"),
        "chunkSize" : 262144,
        "created_at" : ISODate("2013-11-06T14:31:00.924Z"),
        "length" : 2064291,
        "uploadDate" : ISODate("2013-11-06T22:31:01.153Z"),
        "path" : "3025cc3bbfcb4528b53b9f440325ef7e",
        "md5" : "157f40b9ea807dae2d8c894d97204837"
}
> db.fs.chunks.find({ files_id : ObjectId("527ac32463b07e109f000490") }).count()
8
```

For the file that returns a 404:

``` javascript
> db.images.find({ path : 'bf550b6853b54adaa769443ce4a22960' }, {created_at:1, file_id:1, path:1, _id:0}).pretty()
{
        "created_at" : ISODate("2013-11-05T09:10:37.036Z"),
        "file_id" : ObjectId("5279268d63b07e109f0003c6"),
        "path" : "bf550b6853b54adaa769443ce4a22960"
}
> db.fs.files.find({ _id : ObjectId("5279268d63b07e109f0003c6") }).pretty()
{
        "_id" : ObjectId("5279268d63b07e109f0003c6"),
        "chunkSize" : 262144,
        "created_at" : ISODate("2013-11-05T09:10:37.036Z"),
        "length" : 2357325,
        "uploadDate" : ISODate("2013-11-05T17:10:37.420Z"),
        "path" : "bf550b6853b54adaa769443ce4a22960",
        "md5" : "c22354ed72d5eee84c3c934b4e8c4d9e"
}
> db.fs.chunks.find({ files_id : ObjectId("5279268d63b07e109f0003c6") }).count()
9
```

At this point I'm stuck. Things were previously working, the files are in mongo, but one returns a 404 and the other works. I restarted mongo and thumbor just to be sure, but that made no difference.

Any help is greatly appreciated! Here is my thumbor config for reference:

```
################################### Imaging ####################################

## Quality index used for generated JPEG images
## Defaults to: 80
QUALITY = 75

## Max AGE sent as a header for the image served by thumbor in seconds
## Defaults to: 86400
MAX_AGE = 86400

## Indicates whether thumbor should enable the EXPERIMENTAL support for animated
## gifs.
## Defaults to: True
ALLOW_ANIMATED_GIFS = False

################################################################################


################################ Extensibility #################################

## The loader thumbor should use to load the original image. This must be the
## full name of a python module (python must be able to import it)
## Defaults to: thumbor.loaders.http_loader
#LOADER = 'thumbor.loaders.http_loader'

## The file storage thumbor should use to store original images. This must be the
## full name of a python module (python must be able to import it)
## Defaults to: thumbor.storages.file_storage
STORAGE = 'thumbor.storages.mongo_storage'

## The result storage thumbor should use to store generated images. This must be
## the full name of a python module (python must be able to import it)
## Defaults to: None
#RESULT_STORAGE = None

## The imaging engine thumbor should use to perform image operations. This must
## be the full name of a python module (python must be able to import it)
## Defaults to: thumbor.engines.pil
#ENGINE = 'thumbor.engines.pil'

################################################################################


################################### Security ###################################

## The security key thumbor uses to sign image URLs
## Defaults to: MY_SECURE_KEY
SECURITY_KEY = '--REMOVED--'

## Indicates if the /unsafe URL should be available
## Defaults to: True
ALLOW_UNSAFE_URL = False

## Indicates if encrypted (old style) URLs should be allowed
## Defaults to: True
ALLOW_OLD_URLS = False

################################################################################

#################################### Upload ####################################

## Indicates whether thumbor should enable File uploads
## Aliases: ENABLE_ORIGINAL_PHOTO_UPLOAD
## Defaults to: False
UPLOAD_ENABLED = True

## The type of storage to store uploaded images with
## Aliases: ORIGINAL_PHOTO_STORAGE
## Defaults to: thumbor.storages.file_storage
UPLOAD_PHOTO_STORAGE = 'thumbor.storages.mongo_storage'

## Indicates whether image deletion should be allowed
## Aliases: ALLOW_ORIGINAL_PHOTO_DELETION
## Defaults to: False
UPLOAD_DELETE_ALLOWED = True

## Indicates whether image overwrite should be allowed
## Aliases: ALLOW_ORIGINAL_PHOTO_PUTTING
## Defaults to: False
UPLOAD_PUT_ALLOWED = True

################################################################################


############################### MongoDB Storage ################################

## MongoDB storage server host
## Defaults to: localhost
MONGO_STORAGE_SERVER_HOST = '--REMOVED--'

## MongoDB storage server port
## Defaults to: 27017
MONGO_STORAGE_SERVER_PORT = --REMOVED--

## MongoDB storage server database name
## Defaults to: thumbor
MONGO_STORAGE_SERVER_DB = '--REMOVED--'

## MongoDB storage image collection
## Defaults to: images
MONGO_STORAGE_SERVER_COLLECTION = '--REMOVED--'

################################################################################


################################## Detection ###################################

## List of detectors that thumbor should use to find faces and/or features. All
## of them must be full names of python modules (python must be able to import
## it)
## Defaults to: []
DETECTORS = [
    'thumbor.detectors.feature_detector',
]
################################################################################


################################### Filters ####################################

## List of filters that thumbor will allow to be used in generated images. All of
## them must be full names of python modules (python must be able to import
## it)
## Defaults to: []
FILTERS = [
    'thumbor.filters.quality',
    'thumbor.filters.watermark',
]

################################################################################
```

**Comment by bhpark-mdp** [comment]
> From what u're saying this is a bug on thumbor's mongo storage. It should
> load the image again instead of throwing a 404
> 
> On Friday, December 6, 2013, cristiangraz wrote:
> 
> > @rafaelcaricio https://github.com/rafaelcaricio ,
> > As a follow up I was able to determine what was causing the issue. The
> > STORAGE_EXPIRATION_SECONDS setting defaults to 1 month, and the images that
> > stopped working were uploaded at least 1 month ago. I saw this in lines
> > 86-89 of mongo_storage.py
> > stored = storage.find_one({'path': path})
> > if not stored or self.__is_expired(stored):
> > return None
> > That explains why the image existed in mongo but was returning a 404. I
> > changed the setting to 50 years and that resolved the issue. However, I'm
> > not sure if I'm understanding the use of this setting or if it's not
> > intended behavior. What would be the use case for wanting your original
> > thumbor storage to expire? I understand why you would want an expiration on
> > cached items, but not sure what the use case is for storage expirations.
> > Hopefully this helps others who come across this issue. Thanks for all
> > your help!
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/[/issues/229](https://github.com/thumbor/thumbor/issues/229)#issuecomment-30031225
> > .
> 
> Fábio Miranda Costa
> _twitter:_ @fabioMiranda
> _github:_ fabiomcosta

**Very Very Thank you!**
key point STORAGE_EXPIRATION_SECONDS

**Comment by hknguyenvu** [comment]
@cristiangraz I have this issue at https://github.com/thumbor/thumbor/issues/1379

Is this as same as your issue? Do you face this issue on new version.

Thanks so much

**Comment by hknguyenvu** [comment]
I found it.

In the default config, we do not have STORAGE_EXPIRATION_SECONDS value. We must add it.

STORAGE_EXPIRATION_SECONDS = None

Thanks
