### ISSUE TITLE
Modules not importing

### ISSUE THREAD

**Issue by tholder** [thumbor/thumbor#256]
Hi, I've installed thumbor on Redhat through yum (not my preference but Redhat is all I have at present).

Everything seemed to go ok, but when I load thumbor I get:

2014-02-06 10:02:30 thumbor:WARNING Module thumbor.filters.brightness could not be imported.
2014-02-06 10:02:30 thumbor:WARNING Module thumbor.filters.contrast could not be imported.
2014-02-06 10:02:30 thumbor:WARNING Module thumbor.filters.rgb could not be imported.
2014-02-06 10:02:30 thumbor:WARNING Module thumbor.filters.round_corner could not be imported.
2014-02-06 10:02:30 thumbor:WARNING Module thumbor.filters.noise could not be imported.
2014-02-06 10:02:30 thumbor:WARNING Module thumbor.filters.watermark could not be imported.
2014-02-06 10:02:30 thumbor:WARNING Module thumbor.filters.equalize could not be imported.
2014-02-06 10:02:30 thumbor:WARNING Module thumbor.filters.fill could not be imported.
2014-02-06 10:02:30 thumbor:WARNING Module thumbor.filters.sharpen could not be imported.
2014-02-06 10:02:30 thumbor:WARNING Module thumbor.filters.frame could not be imported.
2014-02-06 10:02:30 thumbor:WARNING Error importing bounding_box filter, trimming won't work

**Comment by AizazAZ** [comment]
I have downloaded and installed but I am getting this error with I try to bind thumbor with ip address


[root@ip-172-31-2-176 bin]# thumbor --ip 54.255.183.121
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.brightness could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.colorize could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.contrast could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.rgb could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.round_corner could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.noise could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.watermark could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.equalize could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.fill could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.sharpen could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.frame could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.convolution could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.blur could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.saturation could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.curve could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Error importing bounding_box filter, trimming won't work
Traceback (most recent call last):
  File "/usr/bin/thumbor", line 9, in <module>
    load_entry_point('thumbor==4.12.2', 'console_scripts', 'thumbor')()
  File "/usr/lib/python2.6/site-packages/thumbor/server.py", line 95, in main
    server.bind(context.server.port, context.server.ip)
  File "/usr/lib64/python2.6/site-packages/tornado/tcpserver.py", line 162, in bind
    backlog=backlog)
  File "/usr/lib64/python2.6/site-packages/tornado/netutil.py", line 104, in bind_sockets
    sock.bind(sockaddr)
  File "<string>", line 1, in bind
socket.error: [Errno 99] Cannot assign requested address

**Comment by ysadiq** [comment]
@AizazAZ have you fixed it, i'm having the same error

**Comment by AizazAZ** [comment]
NO, I have installed Python 3.3 but still getting the same error :-1:

**Comment by dhardy92** [comment]
Thumbor support python 2.7
