### ISSUE TITLE
Error message in log when processing URL

### ISSUE THREAD

**Issue by dfraser** [thumbor/thumbor#317]
2014-06-26 15:14:43 thumbor:ERROR ERROR: Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1115, in stack_context_handle_exception
raise_exc_info((type, value, traceback))
File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 302, in wrapped
ret = fn(_args, *_kwargs)
File "/usr/lib/python2.7/dist-packages/thumbor/loaders/http_loader.py", line 49, in return_contents
callback(response.body)
File "/usr/lib/python2.7/dist-packages/thumbor/handlers/__init_.py", line 299, in handle_loader_loaded
storage.put(url, buffer)
File "/usr/lib/python2.7/dist-packages/thumbor/storages/file_storage.py", line 25, in put
file_abspath = self.path_on_filesystem(path)
File "/usr/lib/python2.7/dist-packages/thumbor/storages/file_storage.py", line 97, in path_on_filesystem
return join(self.context.config.FILE_STORAGE_ROOT_PATH.rstrip('/'), digest[:2] + '/' + digest[2:])
File "/usr/lib/python2.7/posixpath.py", line 74, in join
for b in p:
TypeError: an integer is required

2014-06-26 15:14:43 tornado.access:ERROR 500 GET /unsafe/http://placekitten.com/200/500 (192.168.4.37) 295.94ms

System information:

Linux thumbor 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

root@thumbor:/var/log/upstart# dpkg -s thumbor
Package: thumbor
Status: install ok installed
Priority: optional
Section: python
Installed-Size: 9757
Maintainer: Wichert Akkerman wichert@wiggy.net
Architecture: amd64
Version: 3.15.0-0ubuntu1ppa1~saucy

**Comment by trungkhong** [comment]
@sytolk Thank you, you saved my day 💯
