### ISSUE TITLE
too many error messages on thumbor webp 

### ISSUE THREAD

**Issue by supergrilo** [thumbor/thumbor#330]
```
2014-07-29 17:28:24 thumbor:ERROR Image format not found in PIL: .webp
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thumbor/engines/pil.py", line 136, in read
    self.image.save(img_buffer, FORMATS[ext], **options)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1459, in save
    save_handler = SAVE[format.upper()] # unknown format
KeyError: 'WEBP'
2014-07-29 17:28:24 thumbor:ERROR Image format not found in PIL: .webp
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thumbor/engines/pil.py", line 136, in read
    self.image.save(img_buffer, FORMATS[ext], **options)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1459, in save
    save_handler = SAVE[format.upper()] # unknown format
KeyError: 'WEBP'
2014-07-29 17:28:25 thumbor:ERROR Image format not found in PIL: .webp
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thumbor/engines/pil.py", line 136, in read
    self.image.save(img_buffer, FORMATS[ext], **options)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1459, in save
    save_handler = SAVE[format.upper()] # unknown format
KeyError: 'WEBP'
```

```
# pip list
argparse (1.2.1)
backports.ssl-match-hostname (3.4.0.2)
boto (2.3.0)
Cheetah (2.4.4)
cloud-init (0.7.2)
configobj (4.7.2)
derpconf (0.6.0)
GnuPGInterface (0.3.2)
oauth (1.0.1)
Pillow (2.3.1)
pip (1.5.6)
prettytable (0.6.1)
pycrypto (2.6.1)
pycurl (7.19.0)
python-apt (0.8.8.2)
python-magic (0.4.6)
PyYAML (3.10)
requests (0.12.1)
setuptools (5.4.1)
six (1.1.0)
thumbor (4.2.1)
thumbor-pexif (0.14)
tornado (3.2.2)
unattended-upgrades (0.1)
wsgiref (0.1.2)
```

**Comment by AizazAZ** [comment]
[root@ip-172-31-2-176 ~]# pip install thumbor
Collecting thumbor
  Using cached thumbor-4.12.2.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-g21rqj/thumbor

**Comment by minhdtb** [comment]
I also get this error in latest version of thumbor. I don't know why. Please fix this!!!!

**Comment by guilhermef** [comment]
that still happens on Thumbor's 5.0 version ?

**Comment by minhdtb** [comment]
Yes, it still gives error on 5.0 version. I'm using thumbor for converting from png to webp. I have already installed libwebp on my Centos server

**Comment by guilhermef** [comment]
@minhdtb Do you mind logging on your Pillow's installation which save handlers it's supporting ?
It will be on https://github.com/python-pillow/Pillow/blob/master/PIL/Image.py#L1684.

**Comment by amadofelipe** [comment]
@minhdtb I was facing the same issue. It got fixed after:
yum install libwebp-devel 
pip uninstall pillow
python setup.py install (inside Pillow 2.3.1 version)

and then reinstalled thumbor.

To check, run pilconvert.py -f and see if WEBP* shows up.

**Comment by heynemann** [comment]
Any news here?
