### ISSUE TITLE
Error with pycurl while installing thumbor on a virtualenv

### ISSUE THREAD

**Issue by jeancarlozapata** [thumbor/thumbor#338]
python --version
`Python 2.7.6`

pip --version
`pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)`

Doing a `pip install thumbor` inside a terminal with an active virtual environment, it starts installing but it fails when downloading pycurl. Is it related to the virtual environment, or is it something I should report to pycurl?

Error goes like this:

```
Downloading/unpacking pycurl>=7.19.0,<7.20.0 (from thumbor)
  Running setup.py (path:/home/caramba/code/python/thumbor-test/env/build/pycurl/setup.py) egg_info for package pycurl
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/caramba/code/python/thumbor-test/env/build/pycurl/setup.py", line 634, in <module>
        ext = get_extension(split_extension_source=split_extension_source)
      File "/home/caramba/code/python/thumbor-test/env/build/pycurl/setup.py", line 392, in get_extension
        ext_config = ExtensionConfiguration()
      File "/home/caramba/code/python/thumbor-test/env/build/pycurl/setup.py", line 65, in __init__
        self.configure()
      File "/home/caramba/code/python/thumbor-test/env/build/pycurl/setup.py", line 100, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/caramba/code/python/thumbor-test/env/build/pycurl/setup.py", line 634, in <module>

    ext = get_extension(split_extension_source=split_extension_source)

  File "/home/caramba/code/python/thumbor-test/env/build/pycurl/setup.py", line 392, in get_extension

    ext_config = ExtensionConfiguration()

  File "/home/caramba/code/python/thumbor-test/env/build/pycurl/setup.py", line 65, in __init__

    self.configure()

  File "/home/caramba/code/python/thumbor-test/env/build/pycurl/setup.py", line 100, in configure_unix

    raise ConfigurationError(msg)

__main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory
```

Any help is appreciated. Thanks and keep up the good work! :+1:

**Comment by mramu111** [comment]
__main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory

by mistake , set this environment variable.
export PYCURL_CURL_CONFIG=/usr/local/bin/curl-config

after unsetting it worked .

with this command
sudo apt-get install libcurl4-openssl-dev

Thanks
