### ISSUE TITLE
Error using memcache_storage

### ISSUE THREAD

**Issue by lucasmendes2105** [thumbor/thumbor#351]
When I use memcache_storage an error occurs.
STORAGE = 'thumbor.storages.memcache_storage'
MEMCACHE_STORAGE_SERVERS = ['#####.hl0jmh.cfg.sae1.cache.amazonaws.com:11211']

>2014-09-18 13:12:38 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/opt/python/run/venv/lib/python2.7/site-packages/tornado/web.py", line 1320, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/opt/python/run/venv/lib/python2.7/site-packages/tornado/web.py", line 1503, in wrapper
    result = method(self, *args, **kwargs)
  File "/opt/python/run/venv/lib/python2.7/site-packages/thumbor/handlers/imaging.py", line 25, in get
    if self.context.modules.storage.exists(kw['image'][:32]):
  File "/opt/python/run/venv/lib/python2.7/site-packages/thumbor/storages/memcache_storage.py", line 77, in exists
    return self.storage.get(path) is not None
TypeError: key must be an instance of str
2014-09-18 13:12:38 tornado.access:ERROR 500 GET /favicon.ico (201.17.245.74) 3.08ms

Can you help me?

**Comment by heynemann** [comment]
Are you still having this issue? I'm fixing the memcached storage right now. Sorry it took so long.
