### ISSUE TITLE
pkg_resources.DistributionNotFound: statsd>=3.0.1

### ISSUE THREAD

**Issue by rosscdh** [thumbor/thumbor#404]
Hi there

Great app thanks!

Encountering a problem

```
thumbor
Traceback (most recent call last):
  File "/usr/local/bin/thumbor", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: statsd>=3.0.1
```

```
pip freeze
Pillow==2.7.0
backports.ssl-match-hostname==3.4.0.2
derpconf==0.7.2
pycrypto==2.6.1
pycurl==7.19.5.1
python-magic==0.4.6
six==1.9.0
statsd==3.0.1
thumbor==4.8.2
thumbor-pexif==0.14.1
tornado==3.2.2
wsgiref==0.1.2
```

Any thoughts?

**Comment by guilhermef** [comment]
could you run:
```
  python -c 'import statsd'
```

**Comment by rosscdh** [comment]
Hi sure!

```
python -c 'import statsd'
(thumbdor)┌[rosscdh@Rosss] [/dev/ttys001] 
```

**Comment by guilhermef** [comment]
I used to have this problem on my Mac after I've moved to virtualenv.
It was a strange collision between the system site-packages and the virtualenv one.

**Comment by rosscdh** [comment]
right you are.. exited the virtualenv and uninstalled statsd and its all good again!

Thanks for your time and the exceptional app

**Comment by guilhermef** [comment]
\o/

**Comment by sunil05** [comment]
I has the same issue and I was not having virtualenv installed apparently.
Later on I observed that I installed it using pip and I am not sure if pip maintains its on env.

So I installed thumbor using easy_install and kudos it solved the issue for me. :)

**Comment by guilhermef** [comment]
@sunil05 Try removing statsd from your system's PYTHONPATH.
Then start a new virtualenv, that should work too.
