### ISSUE TITLE
OpenCV crash with some PNG Files

### ISSUE THREAD

**Issue by xkobal** [thumbor/thumbor#408]
Hello, 

We are using Thumbor for some resizing on Overblog (https://www.over-blog.com/) and it works very well, but we encounter problems with some PNG files.

We are using OpenCV engine because of its speed and smart detection, and we fallback on PIL when OpenCV crash.

Here is the version we use:
Pillow==2.3.2
opencv-engine==1.0.0
pgmagick==0.5.8
thumbor==4.8.2
thumbor-pexif==0.14.1
tornado==3.2.2

Works on Debian 7 with bundled OpenCV 2.4.10.

Here is an example of a PNG: http://img.over-blog-kiwi.com/0/88/72/24/20150107/ob_f75a17_jescharlie.png 

We resize with this command:
/unsafe/568x568/http://img.over-blog-kiwi.com/0/88/72/24/20150107/ob_f75a17_jescharlie.png
(I know it's an upscale)

It's the same with downscale: /unsafe/100x50/http://img.over-blog-kiwi.com/0/88/72/24/20150107/ob_f75a17_jescharlie.png

```
thumbor_opencv OpenCV Error: Assertion failed (src.depth() == dst.depth() && src.size == dst.size) in cvCopy, file /tmp/opencv-2.4.10/modules/core/src/copy.cpp, line 556
thumbor_opencv 2015-01-14 09:57:34 thumbor:ERROR ERROR: Traceback (most recent call last):
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1320, in _stack_context_handle_exception
thumbor_opencv     raise_exc_info((type, value, traceback))
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 302, in wrapped
thumbor_opencv     ret = fn(*args, **kwargs)
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/thumbor/loaders/http_loader.py", line 54, in return_contents
thumbor_opencv     callback(response.body)
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 373, in handle_loader_loaded
thumbor_opencv     callback(normalized, engine=self.context.request.engine)
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 110, in callback
thumbor_opencv     self.filters_runner.apply_filters(thumbor.filters.PHASE_AFTER_LOAD, transform)
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/thumbor/filters/__init__.py", line 81, in apply_filters
thumbor_opencv     callback()
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 108, in transform
thumbor_opencv     Transformer(self.context).transform(after_transform_cb)
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/thumbor/transformer.py", line 88, in transform
thumbor_opencv     self.smart_detect()
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/thumbor/transformer.py", line 123, in smart_detect
thumbor_opencv     self.do_image_operations()
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/thumbor/transformer.py", line 195, in do_image_operations
thumbor_opencv     self.auto_crop()
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/thumbor/transformer.py", line 247, in auto_crop
thumbor_opencv     self.engine.crop(crop_left, crop_top, crop_right, crop_bottom)
thumbor_opencv   File "/usr/local/lib/python2.7/dist-packages/opencv_engine/engine.py", line 95, in crop
thumbor_opencv     cv.Copy(src_region, cropped)
thumbor_opencv error: src.depth() == dst.depth() && src.size == dst.size
```

Works very well with PIL.

Thanks for your work and your help.

**Comment by heynemann** [comment]
Can you close this issue here and open it at [opencv-engine](https://github.com/thumbor/opencv-engine)?

**Comment by xkobal** [comment]
Done: https://github.com/thumbor/opencv-engine/issues/13
