### ISSUE TITLE
Getting socket.error: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by kartikluke** [thumbor/thumbor#418]
```
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/usr/bin/thumbor", line 9, in <module>
    load_entry_point('thumbor==4.10.0', 'console_scripts', 'thumbor')()
  File "/usr/lib64/python2.6/site-packages/thumbor/server.py", line 90, in main
    server.bind(context.server.port, context.server.ip)
  File "/usr/lib64/python2.6/site-packages/tornado/tcpserver.py", line 162, in bind
    backlog=backlog)
  File "/usr/lib64/python2.6/site-packages/tornado/netutil.py", line 104, in bind_sockets
    sock.bind(sockaddr)
  File "<string>", line 1, in bind
```

**Comment by kartikluke** [comment]
Coming from thumbor_aws. Sorry.
