### ISSUE TITLE
Thumb AUTO_WEBP causes 'cv2.cv.iplimage' object has no attribute 'size'

### ISSUE THREAD

**Issue by bjoernhaeuser** [thumbor/thumbor#427]
Hey, when trying to use AUTO_WEBP with an JPEG. I am getting a `AttributeError`.

This is the stacktrace:

```
2015-03-07 16:18:40 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/home/vagrant/thumbor/lib/python2.7/site-packages/tornado/web.py", line 1320, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/home/vagrant/thumbor/lib/python2.7/site-packages/tornado/stack_context.py", line 302, in wrapped
    ret = fn(*args, **kwargs)
  File "/home/vagrant/thumbor/lib/python2.7/site-packages/thumbor/loaders/http_loader.py", line 54, in return_contents
    callback(response.body)
  File "/home/vagrant/thumbor/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 382, in handle_loader_loaded
    callback(normalized, engine=self.context.request.engine)
  File "/home/vagrant/thumbor/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 112, in callback
    self.filters_runner.apply_filters(thumbor.filters.PHASE_AFTER_LOAD, transform)
  File "/home/vagrant/thumbor/lib/python2.7/site-packages/thumbor/filters/__init__.py", line 81, in apply_filters
    callback()
  File "/home/vagrant/thumbor/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 110, in transform
    Transformer(self.context).transform(after_transform_cb)
  File "/home/vagrant/thumbor/lib/python2.7/site-packages/thumbor/transformer.py", line 88, in transform
    self.smart_detect()
  File "/home/vagrant/thumbor/lib/python2.7/site-packages/thumbor/transformer.py", line 156, in smart_detect
    self.do_image_operations()
  File "/home/vagrant/thumbor/lib/python2.7/site-packages/thumbor/transformer.py", line 199, in do_image_operations
    self.done_callback()
  File "/home/vagrant/thumbor/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 154, in after_transform
    self.filters_runner.apply_filters(thumbor.filters.PHASE_POST_TRANSFORM, finish_callback)
  File "/home/vagrant/thumbor/lib/python2.7/site-packages/thumbor/filters/__init__.py", line 81, in apply_filters
    callback()
  File "/home/vagrant/thumbor/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 189, in finish_request
    image_extension, content_type = self.define_image_type(context, result)
  File "/home/vagrant/thumbor/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 170, in define_image_type
    elif self.is_webp(context):
  File "/home/vagrant/thumbor/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 160, in is_webp
    context.request.engine.can_convert_to_webp())
  File "/home/vagrant/thumbor/lib/python2.7/site-packages/thumbor/engines/__init__.py", line 116, in can_convert_to_webp
    return self.image.size[0] <= WEBP_SIDE_LIMIT and self.image.size[1] <= WEBP_SIDE_LIMIT
AttributeError: 'cv2.cv.iplimage' object has no attribute 'size'
```

Versions:
```
$ pip freeze
backports.ssl-match-hostname==3.4.0.2
colour==0.0.6
configobj==4.7.2
decorator==3.4.0
derpconf==0.7.3
iniparse==0.4
libthumbor==1.0.1
nose==1.3.0
numpy==1.7.1
-e git+https://github.com/thumbor/opencv-engine.git@ac9dcbaed8c6008bfa44ddc3e64beb92b3a44ed4#egg=opencv_engine-master
pexif==0.15
Pillow==2.7.0
pycrypto==2.6.1
pycurl==7.19.0
pygobject==3.8.2
pygpgme==0.3
pyliblzma==0.5.3
python-magic==0.4.6
pyudev==0.15
pyxattr==0.5.1
six==1.9.0
slip==0.4.0
slip.dbus==0.4.0
statsd==3.0.1
thumbor==4.10.3
tornado==3.2.2
urlgrabber==3.10
virtualenv==12.0.7
yum-metadata-parser==1.1.4

$ python --version
Python 2.7.5

$ yum info opencv
Installed Packages
Name        : opencv
Arch        : x86_64
Version     : 2.4.5
Release     : 3.el7
Size        : 25 M
Repo        : installed
From repo   : base
Summary     : Collection of algorithms for computer vision
URL         : http://opencv.org
License     : BSD
Description : OpenCV means Intel® Open Source Computer Vision Library. It is a collection of
            : C functions and a few C++ classes that implement some popular Image Processing
            : and Computer Vision algorithms.


$ yum info opencv-python
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: artfiles.org
 * extras: artfiles.org
 * updates: artfiles.org
Installed Packages
Name        : opencv-python
Arch        : x86_64
Version     : 2.4.5
Release     : 3.el7
Size        : 1.4 M
Repo        : installed
From repo   : base
Summary     : Python bindings for apps which use OpenCV
URL         : http://opencv.org
License     : BSD
Description : This package contains Python bindings for the OpenCV library.
```

Thanks
Björn

**Comment by guilhermef** [comment]
@bjoernhaeuser can you test with the current master ?

**Comment by bjoernhaeuser** [comment]
Works, thanks :)
