### ISSUE TITLE
Sphinx / reST

### ISSUE THREAD

**Issue by masom** [thumbor/thumbor#438]
Would the Thumbor project be willing to accept PRs that only add docstrings ?

We've been developing a few extensions / patches to thumbor and the lack of documentation makes it a little bit harder to figure out what each functions must return / what they receive.

**Comment by heynemann** [comment]
Definitely! If they add value to understanding the codebase, it would help the whole community!

Thanks for all your hard work.

One of our devs is trying to compile thumbor docs in a sphinx doc - @ricardodani 

Maybe you can work together?

**Comment by masom** [comment]
@ricardodani There's a few documentation PR that will get the technical docs rolling. ( https://github.com/thumbor/thumbor/pull/443, https://github.com/thumbor/thumbor/pull/444, https://github.com/thumbor/thumbor/pull/445 )

It would be awesome if the technical + general docs would be merged into the same sphinx structure and hosted on readthedocs.

**Comment by ricardodani** [comment]
Hi @masom, I exeperienced these issues building the docs on a clean virtualenv after an make setup:

```
(thumbor)➜  docs git:(x-docstring-importer) make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3.1
making output directory...
loading pickled environment... not yet created
WARNING: 'default' html theme has been renamed to 'classic'. Please change your html_theme setting either to the new 'alabaster' default theme, or to 'classic' to keep using the old default.
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 23 source files that are out of date
updating environment: 23 added, 0 changed, 0 removed
No handlers could be found for logger "thumbor"                                                                                                                                                                    
reading sources... [100%] thumbor.storages                                                                                                                                                                         
/Users/ricardo.dani/Development/thumbor/docs/thumbor.detectors.rst:22: WARNING: autodoc: failed to import module u'thumbor.detectors.local_detector'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/detectors/local_detector.py", line 16, in <module>
    import cv2.cv as cv
ImportError: No module named cv2.cv
/Users/ricardo.dani/Development/thumbor/docs/thumbor.detectors.face_detector.rst:7: WARNING: autodoc: failed to import module u'thumbor.detectors.face_detector'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/detectors/face_detector/__init__.py", line 11, in <module>
    from thumbor.detectors.local_detector import CascadeLoaderDetector
  File "/Users/ricardo.dani/Development/thumbor/thumbor/detectors/local_detector.py", line 16, in <module>
    import cv2.cv as cv
ImportError: No module named cv2.cv
/Users/ricardo.dani/Development/thumbor/docs/thumbor.detectors.feature_detector.rst:7: WARNING: autodoc: failed to import module u'thumbor.detectors.feature_detector'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/detectors/feature_detector/__init__.py", line 14, in <module>
    import cv2.cv as cv
ImportError: No module named cv2.cv
/Users/ricardo.dani/Development/thumbor/docs/thumbor.detectors.glasses_detector.rst:7: WARNING: autodoc: failed to import module u'thumbor.detectors.glasses_detector'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/detectors/glasses_detector/__init__.py", line 13, in <module>
    from thumbor.detectors.local_detector import CascadeLoaderDetector
  File "/Users/ricardo.dani/Development/thumbor/thumbor/detectors/local_detector.py", line 16, in <module>
    import cv2.cv as cv
ImportError: No module named cv2.cv
/Users/ricardo.dani/Development/thumbor/docs/thumbor.detectors.profile_detector.rst:7: WARNING: autodoc: failed to import module u'thumbor.detectors.profile_detector'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/detectors/profile_detector/__init__.py", line 13, in <module>
    from thumbor.detectors.local_detector import CascadeLoaderDetector
  File "/Users/ricardo.dani/Development/thumbor/thumbor/detectors/local_detector.py", line 16, in <module>
    import cv2.cv as cv
ImportError: No module named cv2.cv
/Users/ricardo.dani/Development/thumbor/docs/thumbor.detectors.queued_detector.rst:10: WARNING: autodoc: failed to import module u'thumbor.detectors.queued_detector.queued_complete_detector'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/detectors/queued_detector/__init__.py", line 13, in <module>
    from remotecv.unique_queue import UniqueQueue
ImportError: No module named remotecv.unique_queue
/Users/ricardo.dani/Development/thumbor/docs/thumbor.detectors.queued_detector.rst:18: WARNING: autodoc: failed to import module u'thumbor.detectors.queued_detector.queued_face_detector'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/detectors/queued_detector/__init__.py", line 13, in <module>
    from remotecv.unique_queue import UniqueQueue
ImportError: No module named remotecv.unique_queue
/Users/ricardo.dani/Development/thumbor/docs/thumbor.detectors.queued_detector.rst:26: WARNING: autodoc: failed to import module u'thumbor.detectors.queued_detector.queued_feature_detector'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/detectors/queued_detector/__init__.py", line 13, in <module>
    from remotecv.unique_queue import UniqueQueue
ImportError: No module named remotecv.unique_queue
/Users/ricardo.dani/Development/thumbor/docs/thumbor.detectors.queued_detector.rst:35: WARNING: autodoc: failed to import module u'thumbor.detectors.queued_detector'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/detectors/queued_detector/__init__.py", line 13, in <module>
    from remotecv.unique_queue import UniqueQueue
ImportError: No module named remotecv.unique_queue
/Users/ricardo.dani/Development/thumbor/docs/thumbor.detectors.queued_sqs_detector.rst:7: WARNING: autodoc: failed to import module u'thumbor.detectors.queued_sqs_detector'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/detectors/queued_sqs_detector/__init__.py", line 12, in <module>
    from remotecv.celery_tasks import CeleryTasks
ImportError: No module named remotecv.celery_tasks
/Users/ricardo.dani/Development/thumbor/thumbor/engines/extensions/pil.py:docstring of thumbor.engines.extensions.pil:16: ERROR: Unexpected indentation.
/Users/ricardo.dani/Development/thumbor/thumbor/engines/extensions/pil.py:docstring of thumbor.engines.extensions.pil:17: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/ricardo.dani/Development/thumbor/thumbor/engines/extensions/pil.py:docstring of thumbor.engines.extensions.pil.GifWriter.getGraphicsControlExt:5: SEVERE: Unexpected section title.

Dispose
-------
/Users/ricardo.dani/Development/thumbor/thumbor/engines/extensions/pil.py:docstring of thumbor.engines.extensions.pil.writeGif:7: SEVERE: Unexpected section title.

Parameters
----------
/Users/ricardo.dani/Development/thumbor/docs/thumbor.filters.rst:10: WARNING: autodoc: failed to import module u'thumbor.filters.blur'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/filters/blur.py", line 13, in <module>
    from thumbor.ext.filters import _convolution
ImportError: cannot import name _convolution
/Users/ricardo.dani/Development/thumbor/docs/thumbor.filters.rst:18: WARNING: autodoc: failed to import module u'thumbor.filters.brightness'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/filters/brightness.py", line 12, in <module>
    from thumbor.ext.filters import _brightness
ImportError: cannot import name _brightness
/Users/ricardo.dani/Development/thumbor/docs/thumbor.filters.rst:26: WARNING: autodoc: failed to import module u'thumbor.filters.colorize'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/filters/colorize.py", line 12, in <module>
    from thumbor.ext.filters import _colorize
ImportError: cannot import name _colorize
/Users/ricardo.dani/Development/thumbor/docs/thumbor.filters.rst:34: WARNING: autodoc: failed to import module u'thumbor.filters.contrast'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/filters/contrast.py", line 12, in <module>
    from thumbor.ext.filters import _contrast
ImportError: cannot import name _contrast
/Users/ricardo.dani/Development/thumbor/docs/thumbor.filters.rst:42: WARNING: autodoc: failed to import module u'thumbor.filters.convolution'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/filters/convolution.py", line 11, in <module>
    from thumbor.ext.filters import _convolution
ImportError: cannot import name _convolution
/Users/ricardo.dani/Development/thumbor/docs/thumbor.filters.rst:50: WARNING: autodoc: failed to import module u'thumbor.filters.curve'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/filters/curve.py", line 12, in <module>
    from thumbor.ext.filters import _curve
ImportError: cannot import name _curve
/Users/ricardo.dani/Development/thumbor/docs/thumbor.filters.rst:58: WARNING: autodoc: failed to import module u'thumbor.filters.equalize'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/filters/equalize.py", line 12, in <module>
    from thumbor.ext.filters import _equalize
ImportError: cannot import name _equalize
/Users/ricardo.dani/Development/thumbor/docs/thumbor.filters.rst:74: WARNING: autodoc: failed to import module u'thumbor.filters.fill'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/filters/fill.py", line 12, in <module>
    from thumbor.ext.filters import _fill
ImportError: cannot import name _fill
/Users/ricardo.dani/Development/thumbor/docs/thumbor.filters.rst:90: WARNING: autodoc: failed to import module u'thumbor.filters.frame'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/filters/frame.py", line 11, in <module>
    from thumbor.ext.filters import _nine_patch
ImportError: cannot import name _nine_patch
/Users/ricardo.dani/Development/thumbor/docs/thumbor.filters.rst:130: WARNING: autodoc: failed to import module u'thumbor.filters.noise'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/filters/noise.py", line 12, in <module>
    from thumbor.ext.filters import _noise
ImportError: cannot import name _noise
/Users/ricardo.dani/Development/thumbor/docs/thumbor.filters.rst:146: WARNING: autodoc: failed to import module u'thumbor.filters.redeye'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/filters/redeye.py", line 13, in <module>
    import cv
ImportError: No module named cv
/Users/ricardo.dani/Development/thumbor/docs/thumbor.filters.rst:154: WARNING: autodoc: failed to import module u'thumbor.filters.rgb'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/filters/rgb.py", line 12, in <module>
    from thumbor.ext.filters import _rgb
ImportError: cannot import name _rgb
/Users/ricardo.dani/Development/thumbor/docs/thumbor.filters.rst:170: WARNING: autodoc: failed to import module u'thumbor.filters.round_corner'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/filters/round_corner.py", line 12, in <module>
    from thumbor.ext.filters import _round_corner
ImportError: cannot import name _round_corner
/Users/ricardo.dani/Development/thumbor/docs/thumbor.filters.rst:178: WARNING: autodoc: failed to import module u'thumbor.filters.saturation'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/filters/saturation.py", line 12, in <module>
    from thumbor.ext.filters import _saturation
ImportError: cannot import name _saturation
/Users/ricardo.dani/Development/thumbor/docs/thumbor.filters.rst:186: WARNING: autodoc: failed to import module u'thumbor.filters.sharpen'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/filters/sharpen.py", line 12, in <module>
    from thumbor.ext.filters import _sharpen
ImportError: cannot import name _sharpen
/Users/ricardo.dani/Development/thumbor/docs/thumbor.filters.rst:202: WARNING: autodoc: failed to import module u'thumbor.filters.watermark'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/filters/watermark.py", line 11, in <module>
    from thumbor.ext.filters import _alpha
ImportError: cannot import name _alpha
/Users/ricardo.dani/Development/thumbor/docs/thumbor.storages.rst:18: WARNING: autodoc: failed to import module u'thumbor.storages.memcache_storage'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/ricardo.dani/.virtualenvs/thumbor/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/Users/ricardo.dani/Development/thumbor/thumbor/storages/memcache_storage.py", line 13, in <module>
    import pylibmc
ImportError: No module named pylibmc
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/ricardo.dani/Development/thumbor/docs/modules.rst:: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] thumbor.storages                                                                                                                                                                          
generating indices... genindex py-modindex
highlighting module code... [100%] thumbor.transformer                                                                                                                                                             
writing additional pages... search
copying static files... WARNING: html_static_path entry u'/Users/ricardo.dani/Development/thumbor/docs/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 34 warnings.
```

**Comment by masom** [comment]
@ricardodani It seems like your virtualenv is not referencing opencv
### cv2
```
 File "/Users/ricardo.dani/Development/thumbor/thumbor/detectors/local_detector.py", line 16, in <module>
    import cv2.cv as cv
```
I had the same issue on OS X and add to install opencv + set my python path:

`export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH`
( http://stackoverflow.com/questions/19876079/opencv-cannot-find-module-cv2 )

### pylibmc
If the memcache storage is loaded the memcache package must be installed. Not currently referenced in setup.py/requirements.txt


The problem with pylibmc and opencv is they require/come-from third-party packages not managed by pip.

**Comment by masom** [comment]
@ricardodani ex: http://ntraft.com/opencv-in-a-virtualenv/
