### ISSUE TITLE
Corrupted result storage crash request

### ISSUE THREAD

**Issue by masom** [thumbor/thumbor#447]
We just hit a few issues with some files that ended up being corrupted on disk.

Thumbor tries to load the result and determine the mime type. If the byffer contains invalid data the entire request is aborted.

Ideally thumbor should continue without the result storage result.

```
» 19 Mar 2015 15:41:40.764 2015-03-19 19:41:41 thumbor:ERROR ERROR: Traceback (most recent call last):
» 19 Mar 2015 15:41:40.764 File "/var/projects/popkey-thumbor/local/lib/python2.7/site-packages/tornado/web.py", line 1320, in _stack_context_handle_exception
» 19 Mar 2015 15:41:40.764 raise_exc_info((type, value, traceback))
» 19 Mar 2015 15:41:40.764 File "/var/projects/popkey-thumbor/local/lib/python2.7/site-packages/tornado/web.py", line 1503, in wrapper
» 19 Mar 2015 15:41:40.764 result = method(self, *args, **kwargs)
» 19 Mar 2015 15:41:40.764 File "/var/projects/popkey-thumbor/local/lib/python2.7/site-packages/thumbor/handlers/imaging.py", line 100, in get
» 19 Mar 2015 15:41:40.764 self.check_image(kw)
» 19 Mar 2015 15:41:40.764 File "/var/projects/popkey-thumbor/local/lib/python2.7/site-packages/thumbor/handlers/imaging.py", line 96, in check_image
» 19 Mar 2015 15:41:40.764 return self.execute_image_operations()
» 19 Mar 2015 15:41:40.764 File "/var/projects/popkey-thumbor/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 97, in execute_image_operations
» 19 Mar 2015 15:41:40.764 self.filters_runner.apply_filters(thumbor.filters.PHASE_PRE_LOAD, self.get_image)
» 19 Mar 2015 15:41:40.764 File "/var/projects/popkey-thumbor/local/lib/python2.7/site-packages/thumbor/filters/__init__.py", line 81, in apply_filters
» 19 Mar 2015 15:41:40.764 callback()
» 19 Mar 2015 15:41:40.764 File "/var/projects/popkey-thumbor/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 122, in get_image
» 19 Mar 2015 15:41:40.764 self._fetch(self.context.request.image_url, self.context.request.extension, callback)
» 19 Mar 2015 15:41:40.764 File "/var/projects/popkey-thumbor/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 372, in _fetch
» 19 Mar 2015 15:41:40.764 callback(False, buffer=buffer)
» 19 Mar 2015 15:41:40.764 File "/var/projects/popkey-thumbor/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 109, in callback
» 19 Mar 2015 15:41:40.764 engine.load(buffer, req.extension)
» 19 Mar 2015 15:41:40.764 File "/var/projects/popkey-thumbor/local/lib/python2.7/site-packages/thumbor/engines/__init__.py", line 91, in load
» 19 Mar 2015 15:41:40.764 imageOrFrames = self.create_image(buffer)
» 19 Mar 2015 15:41:40.764 File "/var/projects/popkey-thumbor/local/lib/python2.7/site-packages/thumbor/engines/pil.py", line 52, in create_image
» 19 Mar 2015 15:41:40.764 img = Image.open(BytesIO(buffer))
» 19 Mar 2015 15:41:40.764 File "/var/projects/popkey-thumbor/local/lib/python2.7/site-packages/PIL/Image.py", line 2274, in open
» 19 Mar 2015 15:41:40.764 % (filename if filename else fp))
» 19 Mar 2015 15:41:40.764 IOError: cannot identify image file <_io.BytesIO object at 0x7f64c92cccb0>
```

**Comment by masom** [comment]
Log lines don't match the current thumbor source. Will re-investitage.
