### ISSUE TITLE
 thumbor:WARNING Module thumbor.filters.brightness could not be imported.

### ISSUE THREAD

**Issue by AizazAZ** [thumbor/thumbor#461]
[root@ip-172-31-2-176 bin]# thumbor --ip 54.255.183.121
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.brightness could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.colorize could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.contrast could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.rgb could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.round_corner could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.noise could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.watermark could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.equalize could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.fill could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.sharpen could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.frame could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.convolution could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.blur could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.saturation could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Module thumbor.filters.curve could not be imported.
2015-04-01 09:36:54 thumbor:WARNING Error importing bounding_box filter, trimming won't work
Traceback (most recent call last):
File "/usr/bin/thumbor", line 9, in 
load_entry_point('thumbor==4.12.2', 'console_scripts', 'thumbor')()
File "/usr/lib/python2.6/site-packages/thumbor/server.py", line 95, in main
server.bind(context.server.port, context.server.ip)
File "/usr/lib64/python2.6/site-packages/tornado/tcpserver.py", line 162, in bind
backlog=backlog)
File "/usr/lib64/python2.6/site-packages/tornado/netutil.py", line 104, in bind_sockets
sock.bind(sockaddr)
File "", line 1, in bind
socket.error: [Errno 99] Cannot assign requested address

**Comment by AizazAZ** [comment]
[root@ip-172-31-2-176 ~]# pip install thumbor
Collecting thumbor
  Using cached thumbor-4.12.2.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-g21rqj/thumbor

**Comment by dhardy92** [comment]
1) I suppose 54.255.183.121 is not the IP hosted by the host ...

**Comment by AizazAZ** [comment]
I have my server hosted on the cloud and this is computers public IP, which IP it should be ?

**Comment by dhardy92** [comment]
Private one hosted by the VM actually, public IP is a NAT to it.

**Comment by dhardy92** [comment]
To be sure choose "0.0.0.0" this mean listening all interface hosted on VM...

**Comment by heynemann** [comment]
Closing this as it does not seem to be a thumbor issue.
