### ISSUE TITLE
ImportError: No module named cv

### ISSUE THREAD

**Issue by jeremyjackson89** [thumbor/thumbor#464]
Installed thumbor and opencv on ubuntu 14.04.

cv2.so and cv.py are present on the system, but if I run python:

```
>>> import cv
Traceback (most recent call last):   
  File "<stdin>", line 1, in <module>
  File "cv.py", line 1, in <module>
    from cv2.cv import *
ImportError: No module named cv
>>> import cv2
>>>
```

cv2 imports, but no cv. If I try to run thumbor, local_detector.py throws

```
thumbor /etc/thumbor.conf
Traceback (most recent call last):
  File "/usr/local/bin/thumbor", line 9, in <module>
    load_entry_point('thumbor==5.0.0rc2', 'console_scripts', 'thumbor')()
  File "/usr/local/lib/python2.7/dist-packages/thumbor-5.0.0rc2-py2.7.egg/thumbor/server.py", line 58, in main
    importer.import_modules()
  File "/usr/local/lib/python2.7/dist-packages/thumbor-5.0.0rc2-py2.7.egg/thumbor/importer.py", line 48, in import_modules
    self.import_item('DETECTORS', 'Detector', is_multiple=True)
  File "/usr/local/lib/python2.7/dist-packages/thumbor-5.0.0rc2-py2.7.egg/thumbor/importer.py", line 74, in import_item
    module = self.import_class('%s.%s' % (module_name, class_name))
  File "/usr/local/lib/python2.7/dist-packages/thumbor-5.0.0rc2-py2.7.egg/thumbor/importer.py", line 33, in import_class
    module = get_module and __import__(name) or __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/thumbor-5.0.0rc2-py2.7.egg/thumbor/detectors/face_detector/__init__.py", line 11, in <module>
    from thumbor.detectors.local_detector import CascadeLoaderDetector
  File "/usr/local/lib/python2.7/dist-packages/thumbor-5.0.0rc2-py2.7.egg/thumbor/detectors/local_detector.py", line 16, in <module>
    import cv2.cv as cv
ImportError: No module named cv
```

I figure "ok, let's import cv2 instead", so I change 'import cv' to 'import cv2', but then I get these warnings:

```
thumbor /etc/thumbor.conf
2015-04-10 13:08:42 thumbor:WARNING Module thumbor.filters.brightness could not be imported.
2015-04-10 13:08:42 thumbor:WARNING Module thumbor.filters.colorize could not be imported.
2015-04-10 13:08:42 thumbor:WARNING Module thumbor.filters.contrast could not be imported.
2015-04-10 13:08:42 thumbor:WARNING Module thumbor.filters.rgb could not be imported.
2015-04-10 13:08:42 thumbor:WARNING Module thumbor.filters.round_corner could not be imported.
2015-04-10 13:08:42 thumbor:WARNING Module thumbor.filters.noise could not be imported.
2015-04-10 13:08:42 thumbor:WARNING Module thumbor.filters.watermark could not be imported.
2015-04-10 13:08:42 thumbor:WARNING Module thumbor.filters.equalize could not be imported.
2015-04-10 13:08:42 thumbor:WARNING Module thumbor.filters.fill could not be imported.
2015-04-10 13:08:42 thumbor:WARNING Module thumbor.filters.saturation could not be imported.
2015-04-10 13:08:42 thumbor:WARNING Module thumbor.filters.sharpen could not be imported.
2015-04-10 13:08:42 thumbor:WARNING Module thumbor.filters.frame could not be imported.
2015-04-10 13:08:42 thumbor:WARNING Error importing bounding_box filter, trimming won't work
```

Which I'm ok with, because I'm not currently using the filters, but as soon as I go to load a page and with this server to get a thumbnail:

```
tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 812, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/dist-packages/thumbor-5.0.0rc2-py2.7.egg/thumbor/transformer.py", line 166, in do_smart_detection
    detectors[0](self.context, index=0, detectors=detectors).detect(self.after_smart_detect)
  File "/usr/local/lib/python2.7/dist-packages/thumbor-5.0.0rc2-py2.7.egg/thumbor/detectors/face_detector/__init__.py", line 21, in __init__
    self.load_cascade_file(__file__, self.context.config.FACE_DETECTOR_CASCADE_FILE)
  File "/usr/local/lib/python2.7/dist-packages/thumbor-5.0.0rc2-py2.7.egg/thumbor/detectors/local_detector.py", line 30, in load_cascade_file
    self.__class__.cascade = cv.Load(cascade_file)
NameError: global name 'cv' is not defined
```

What am I doing wrong?

**Comment by scorphus** [comment]
@metalcro, this was an issue [OpenCV Engine](/thumbor/opencv-engine) and it's already solved – thanks to a [valuable contribution](/thumbor/opencv-engine/commit/84805f5) – but not released yet. We'll release it ASAP and keep this issue updated. Please bear with us. Thanks!

**Comment by scorphus** [comment]
Hey, @metalcro, please check out just released [OpenCV Engine 1.0.1](/thumbor/opencv-engine/releases/tag/1.0.1) and let us know if it solves your issue

**Comment by metalcro** [comment]
It didn't, though I'm wondering if it's an issue with my installation of opencv (installed with instructions from http://docs.opencv.org/doc/tutorials/introduction/linux_install/linux_install.html#linux-installation).

It's the same thing for me:

```
thumbor
2015-04-13 12:57:02 root:ERROR Could not import opencv_engine. Probably due to setup.py installing it.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/opencv_engine/__init__.py", line 9, in <module>
    from opencv_engine.engine import Engine  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/opencv_engine/engine.py", line 14, in <module>
    import cv2.cv as cv
ImportError: No module named cv
Traceback (most recent call last):
  File "/usr/local/bin/thumbor", line 9, in <module>
    load_entry_point('thumbor==5.0.0rc2', 'console_scripts', 'thumbor')()
  File "/usr/local/lib/python2.7/dist-packages/thumbor-5.0.0rc2-py2.7.egg/thumbor/server.py", line 58, in main
    importer.import_modules()
  File "/usr/local/lib/python2.7/dist-packages/thumbor-5.0.0rc2-py2.7.egg/thumbor/importer.py", line 44, in import_modules
    self.import_item('ENGINE', 'Engine')
  File "/usr/local/lib/python2.7/dist-packages/thumbor-5.0.0rc2-py2.7.egg/thumbor/importer.py", line 86, in import_item
    module = self.import_class('%s.%s' % (conf_value, class_name))
  File "/usr/local/lib/python2.7/dist-packages/thumbor-5.0.0rc2-py2.7.egg/thumbor/importer.py", line 37, in import_class
    return get_module and module or getattr(module, klass)
AttributeError: 'module' object has no attribute 'Engine'
```

**Comment by scorphus** [comment]
@metalcro yesterday I could `varant up` a machine with Ubuntu 14.04, installed OpenCV from source and got Thumbor up and running with OpenCVEngine.

I'm not really sure what the problem might be. Most likely a problem with your `$PYTHONPATH` not being correctly set. You could try changing it or placing something like the following in your `.bashrc` (or even further, `/etc/bash.bashrc`) ans see what you get:

```
export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python2.7/
export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages
export PYTHONPATH=$PYTHONPATH:/usr/lib/pyshared/python2.7/
export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages/
```

Or, you could copy OpenCV objects from system's to virtualenv's `site-packages`, something like:

`cp /usr/local/lib/python2.7/site-packages/cv* /path-to-virtualenv/lib/python2.7/site-packages/`

**Comment by metalcro** [comment]
@scorphus, I tried adding those into /etc/bash.bashrc, but no luck. Did you install opencv without issue using the link I provided or from the thumbor documentation? I can always uninstall opencv and try reinstalling again doing what you did.

**Comment by scorphus** [comment]
Yes, I installed from source, just as described in the [link you provided] (http://docs.opencv.org/doc/tutorials/introduction/linux_install/linux_install.html#linux-installation). I cloned the repository and checked out tag 2.4.10 before doing so, though. I can share the Vagrantfile with you, if you'd like.

**Comment by metalcro** [comment]
I think I'm going to remove everything I've done and start fresh. And yes, I would appreciate you sharing that with me.

**Comment by metalcro** [comment]
Hey, this was my first time installing things on a server (hell of a baptism), but I finally got everything working smoothly after starting over and having to uninstall and reinstall thumbor a few times. I've even got face detection working now.

I had to use an amalgamation of these links:

* https://github.com/thumbor/thumbor/wiki/Installing
* http://www.dadoune.com/blog/best-thumbnailing-solution-set-up-thumbor-on-aws/
* https://github.com/thumbor/thumbor/issues/256

along with googling to fix errors here and there because I didn't have some dependencies installed or I installed something before something else on accident.

**Comment by scorphus** [comment]
Nice, @metalcro! Do you mind listing things you've done or changed to get it working? It may be useful to someone facing similar problems in the future. Thanks!

**Comment by metalcro** [comment]
Sure!

1) I wiped the server so that I was starting from scratch
2) Installed nginx and supervisor (only installed, I didn't do any of the set up until thumbor was working)
3) Had issues install pycurl and numpy, but I eventually got those to work using apt-get instead of pip or easy_install
4) Installed thumbor
5) Ran thumbor, had errors. Uninstalled thumbor.
6) Then I followed [this](https://github.com/thumbor/thumbor/issues/256#issuecomment-34427721)
7) I ran python and imported cv without issue (huzzah!)
8) Ran thumbor, confirmed working.
9) Then I followed the set up nginx and supervisor [here](https://github.com/thumbor/thumbor/issues/256#issuecomment-34427721).

The funny thing is that I'm still getting the detectors to work despite not having downloaded opencv-engine or changing the engine in thumbor.conf.

**Comment by heynemann** [comment]
Detectors do not require opencv-engine... ;) Only to use OpenCV as your resizing-cropping engine.

**Comment by hayd** [comment]
I had the `from cv2.cv import *` error, when using python 3.4. Hmmm: http://stackoverflow.com/questions/25215102/installing-opencv-for-python-on-ubuntu-getting-importerror-no-module-named-cv2#comment39274137_25215102 "the old cv (or cv2.cv) module won't be there in upcoming opencv versions" ... unclear what the solution is.

**Comment by sbaechler** [comment]
OpenCV 3.0.0 does not have the cv2.cv module anymore.

**Comment by sbaechler** [comment]
I added experimental support for OpenCV 3.0.0 in the `feature_detector` module in this commit: https://github.com/sbaechler/thumbor/commit/0e2b8879ec028a113880c879a7515b1bed6f8d37. I don't now, however if I broke backwards compatibility. OpenCV stopped using the IplImage data type. It's all Mats now, which are represented in Python by numpy arrays.

One issue is with passing the image into OpenCV. The easiest way is to create an array from the Image object. (`image = np.asarray(engine.image)`). This is working fine with the PIL backend. I haven't looked into the other backends though.

**Comment by guilhermef** [comment]
We've done that on https://github.com/thumbor/thumbor/commit/c19e2b0e3ad11334f7d94aa9054a6a84246a758d

**Comment by guilhermef** [comment]
@sbaechler now the `feature_detector` on master is using cv2 too: https://github.com/thumbor/thumbor/commit/5497922565dd95ee095a9b341b24d85333070244

**Comment by hchaithanya** [comment]
While running "import cv2" inside my virtualenv, python throws me this error:

> Python 2.7.9 (default, Apr  2 2015, 15:33:21)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named cv2
I am using pip version 9.0.1 It would be great if anyone could help me figure this out.

**Comment by Savar** [comment]
@hchaithanya what's your actual setup? Mac, Linux? what packages did you install? Did you try `pip install opencv-python` ?

**Comment by YacheLee** [comment]
Great, @Savar, I try `pip install opencv-python`.
It works perfect.
