### ISSUE TITLE
Engine opencv and gif files

### ISSUE THREAD

**Issue by smagnaschi** [thumbor/thumbor#469]
After struggling to install on AWS Ubuntu 14 Thumbor + opencv I ended up having a working solution.
OpenCv seems to work ok but when I have to resize a GIF image I got this:

	2015-04-29 08:41:38 thumbor:ERROR ERROR: Traceback (most recent call last):
	File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1320, in _stack_context_handle_exception
		raise_exc_info((type, value, traceback))
	File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 302, in wrapped
		ret = fn(*args, **kwargs)
	File "/usr/local/lib/python2.7/dist-packages/thumbor/loaders/http_loader.py", line 54, in return_contents
		callback(response.body)
	File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 392, in handle_loader_loaded
		self.context.request.engine.load(buffer, extension)
	File "/usr/local/lib/python2.7/dist-packages/thumbor/engines/__init__.py", line 91, in load
		imageOrFrames = self.create_image(buffer)
	File "/usr/local/lib/python2.7/dist-packages/opencv_engine/engine.py", line 74, in create_image
		raise ValueError("opencv doesn't support gifs")
	ValueError: opencv doesn't support gifs

Doesn't Thumbor fallback on other engine if one is failing?

**Comment by heynemann** [comment]
Not really... You could help and improve OpenCV engine to work like that. Do you think that's something you'd be willing to do? Otherwise you  can use PIL engine.

**Comment by smagnaschi** [comment]
Thanks for the reply, there's something that I cannot really understand
though.
Is OpenCv necessary for smart cropping?
We basically need smart cropping and the ability to resize / resample
images in various formats (jpg / gif).
By reading the doc it seems that opencv as engine is a requirement to have
smart cropping, but I just reverted the engine to PIL and smart cropping is
working still, while at the same time, working with gifs.
Could someone please clarify it for me?
Thanks a lot for this amazing work.

2015-04-29 16:30 GMT+02:00 Bernardo Heynemann <notifications@github.com>:

**Comment by rochmad** [comment]
i have same problem, but using this "USE_GIFSICLE_ENGINE = True" make that problem solved but dont know opencv engine still working or not,
