### ISSUE TITLE
non web image formats support (psd, ai, tiff, eps...)

### ISSUE THREAD

**Issue by LukasUrban** [thumbor/thumbor#483]
What is proper way to get non-web formats working (psd, ai, tiff, eps...)?

I'm using thumbor_graphicsmagick engine. It works well for most formats, but not psd.

**Comment by guilhermef** [comment]
That's strange, because graphicsmagick supports PSD. http://www.graphicsmagick.org/formats.html
What happens when you try to load a PSD ?

**Comment by LukasUrban** [comment]
```
2015-06-01 16:16:28 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 106, in get_image
    self.context.request.extension
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 402, in _fetch
    self.context.request.engine.load(buffer, extension)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/engines/__init__.py", line 92, in load
    imageOrFrames = self.create_image(buffer)
  File "/usr/local/lib/python2.7/dist-packages/graphicsmagick_engine/engine.py", line 45, in create_image
    img = Image(blob)
RuntimeError: Magick: Too much image data in file () reported by coders/psd.c:254 (DecodeImage)
```

**Comment by guilhermef** [comment]
Can you run a "pip freeze" too ?

**Comment by LukasUrban** [comment]
```
PAM==0.4.2
Pillow==2.8.1
Twisted-Core==13.2.0
Twisted-Web==13.2.0
adium-theme-ubuntu==0.3.4
apt-xapian-index==0.45
argparse==1.2.1
backports.ssl-match-hostname==3.4.0.2
ccsm==0.9.11.3
certifi==2015.04.28
chardet==2.0.1
colorama==0.2.5
command-not-found==0.3
compizconfig-python==0.9.11.3
debtagshw==0.1
defer==1.0.6
derpconf==0.7.3
dirspec==13.10
dnspython==1.11.1
duplicity==0.6.23
futures==3.0.2
graphicsmagick-engine==0.1.1
html5lib==0.999
httplib2==0.8
libthumbor==1.1.0
lockfile==0.8
lxml==3.3.3
numpy==1.9.2
oauthlib==0.6.1
oneconf==0.3.7
pexif==0.15
pexpect==3.1
pgmagick==0.5.7
piston-mini-client==0.7.5
pyOpenSSL==0.13
pycrypto==2.6.1
pycups==1.9.66
pycurl==7.19.3
pygobject==3.12.0
pyserial==2.6
pysmbc==1.0.14.1
python-apt==0.9.3.5ubuntu1
python-debian==0.1.21-nmu2ubuntu2
python-magic==0.4.6
pyxdg==0.25
reportlab==3.0
requests==2.2.1
sessioninstaller==0.0.0
six==1.5.2
software-center-aptd-plugins==0.0.0
statsd==3.1
system-service==0.1.6
thumbor==5.0.3
tornado==4.2
unity-lens-photos==1.0
urllib3==1.7.1
wheel==0.24.0
wsgiref==0.1.2
xdiagnose==3.6.3build2
zope.interface==4.0.5
```

**Comment by guilhermef** [comment]
What happens when you run "gm convert your_psd.psd test.jpg" ?

**Comment by LukasUrban** [comment]
```
gm convert: Too much image data in file (test.psd).
```

It is 400kb 10 layers file, nothing fancy. Since it doesn't even work with gm separately, it probably isn't Thumbor issue...

**Comment by guilhermef** [comment]
@LukasUrban this looks like a common issue on GM http://stackoverflow.com/questions/7485552/need-help-to-convert-psd-to-png-in-graphicsmagick

**Comment by guilhermef** [comment]
And appears to be fixed http://sourceforge.net/p/graphicsmagick/bugs/234/
