### ISSUE TITLE
Thumbor error

### ISSUE THREAD

**Issue by vijjay29** [thumbor/thumbor#507]
Traceback (most recent call last):
  File "/usr/local/bin/thumbor", line 9, in <module>
    load_entry_point('thumbor==5.0.4', 'console_scripts', 'thumbor')()
  File "/usr/local/lib/python2.7/dist-packages/thumbor/server.py", line 98, in main
    server.bind(context.server.port, context.server.ip)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.2-py2.7-linux-x86_64.egg/tornado/tcpserver.py", line 171, in bind
    backlog=backlog)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.2-py2.7-linux-x86_64.egg/tornado/netutil.py", line 187, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

"Im new to thumbor, struggling to run it.
I dont know where do i lag,
Kindly help me to step into..
"

**Comment by lfalcao** [comment]
@vijjay29,

the port you're trying to start thumbor is already in use... check netstat -ltn

**Comment by vijjay29** [comment]
@lfalcao Thanks bro,
But still could you tell me how to fix it., Im new to thumbor and linux too

**Comment by lfalcao** [comment]
@vijjay29,

try to start thumbor using another port and dont create unnecessary and duplicates issues ;) (https://github.com/thumbor/thumbor/issues/508)

```
thumbor -p 999
```

**Comment by dhardy92** [comment]
999 will only work with root user (because <1024)
