### ISSUE TITLE
Thumbor deamon segFault on false url

### ISSUE THREAD

**Issue by TwanoO67** [thumbor/thumbor#528]
Hello,

During some of our test on thumbor, we realised that when calling the thumbor server, with an uri that is not an image (and respond with code 200), the deamon crashes without error.

You can easily reproduce that by calling:
curl -I "http://localhost:8888/unsafe/300x200/smart/google.fr"

You should get an error like:
(52) Empty reply from server

and after that the daemon is gone.

Regards,
Antoine

**Comment by masom** [comment]
Which version of thumbor are you running?

This is what I get on 5.0.x:

```
2015-08-12 11:29:02 thumbor:DEBUG STATSD: storage.miss:1|c
2015-08-12 11:29:02 thumbor:DEBUG STATSD: original_image.status.200:1|c
2015-08-12 11:29:02 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/Users/martin/venv/thumbor/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/martin/dev/os/thumbor/thumbor/handlers/__init__.py", line 86, in get_image
    self.context.request.image_url
  File "/Users/martin/venv/thumbor/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/Users/martin/venv/thumbor/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/Users/martin/venv/thumbor/lib/python2.7/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/Users/martin/dev/os/thumbor/thumbor/handlers/__init__.py", line 389, in _fetch
    self.context.request.engine.load(buffer, extension)
  File "/Users/martin/dev/os/thumbor/thumbor/engines/__init__.py", line 96, in load
    image_or_frames = self.create_image(buffer)
  File "/Users/martin/dev/os/thumbor/thumbor/engines/pil.py", line 52, in create_image
    img = Image.open(BytesIO(buffer))
  File "/Users/martin/venv/thumbor/lib/python2.7/site-packages/PIL/Image.py", line 2330, in open
    % (filename if filename else fp))
IOError: cannot identify image file <_io.BytesIO object at 0x1039cb350>
```

The process is still running but it never respond to the request ( this is a bug ).

**Comment by lfalcao** [comment]
I had this problem in the past, fixed just removing the wrong urls... 

pull request #531 fixes

**Comment by heynemann** [comment]
Closing this as it's probably fixed.
