### ISSUE TITLE
Silent ci errors

### ISSUE THREAD

**Issue by dhardy92** [thumbor/thumbor#566]
Hello running pyvows on my local repo I result in tests passes but actually some tests failed : 

(in this case I removed mongo, redis and sentry tests)
```
[...]
 ============
 Vows Results
 ============

    Max age vows
      With detection error image

       Error in setup:
      No module named fixtures.detection_error_detector
      
Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/gevent.py", line 87, in _run_setup_and_topic
    ctx_obj.setup()
        File "/usr/local/lib/python2.7/dist-packages/tornado_pyvows/context.py", line 197, in setup
    AsyncHTTPTestCase.setup(self)
        File "/usr/local/lib/python2.7/dist-packages/tornado_pyvows/context.py", line 90, in setup
    self.app = self.get_app()
        File "/home/dhardy/SOURCE/GIT/thumbor/vows/max_age_vows.py", line 91, in get_app
    return get_app(detection_error=True)
        File "/home/dhardy/SOURCE/GIT/thumbor/vows/max_age_vows.py", line 39, in get_app
    importer.import_modules()
        File "/home/dhardy/SOURCE/GIT/thumbor/thumbor/importer.py", line 52, in import_modules
    self.import_item('DETECTORS', 'Detector', is_multiple=True)
        File "/home/dhardy/SOURCE/GIT/thumbor/thumbor/importer.py", line 79, in import_item
    module = self.import_class('%s.%s' % (module_name, class_name))
        File "/home/dhardy/SOURCE/GIT/thumbor/thumbor/importer.py", line 35, in import_class
    module = get_module and __import__(name) or __import__(module_name)
ImportError: No module named fixtures.detection_error_detector

      Nested tests following this error have not been run.
      With non storaged image

       Error in setup:
      No module named fixtures.prevent_result_storage_detector
      
Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/gevent.py", line 87, in _run_setup_and_topic
    ctx_obj.setup()
        File "/usr/local/lib/python2.7/dist-packages/tornado_pyvows/context.py", line 197, in setup
    AsyncHTTPTestCase.setup(self)
        File "/usr/local/lib/python2.7/dist-packages/tornado_pyvows/context.py", line 90, in setup
    self.app = self.get_app()
        File "/home/dhardy/SOURCE/GIT/thumbor/vows/max_age_vows.py", line 71, in get_app
    return get_app(prevent_result_storage=True)
        File "/home/dhardy/SOURCE/GIT/thumbor/vows/max_age_vows.py", line 39, in get_app
    importer.import_modules()
        File "/home/dhardy/SOURCE/GIT/thumbor/thumbor/importer.py", line 52, in import_modules
    self.import_item('DETECTORS', 'Detector', is_multiple=True)
        File "/home/dhardy/SOURCE/GIT/thumbor/thumbor/importer.py", line 79, in import_item
    module = self.import_class('%s.%s' % (module_name, class_name))
        File "/home/dhardy/SOURCE/GIT/thumbor/thumbor/importer.py", line 35, in import_class
    module = get_module and __import__(name) or __import__(module_name)
ImportError: No module named fixtures.prevent_result_storage_detector

      Nested tests following this error have not been run.
    Get image result storage
      Should load gif v from result storage

       Error in topic:
      Async operation timed out after 5 seconds
      
Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/gevent.py", line 104, in _run_setup_and_topic
    topic = topic_func(*topic_list)
        File "/home/dhardy/SOURCE/GIT/thumbor/vows/handler_images_vows.py", line 585, in topic
    return self.get('/degWAAUDokT-7K81r2BXoPTbg8c=/filters:gifv()/animated_image.gif')
        File "/usr/local/lib/python2.7/dist-packages/tornado_pyvows/context.py", line 212, in get
    return self.fetch(path, method="GET", **kwargs)
        File "/usr/local/lib/python2.7/dist-packages/tornado_pyvows/context.py", line 130, in fetch
    return self.wait()
        File "/usr/local/lib/python2.7/dist-packages/tornado_pyvows/context.py", line 55, in timeout_func
    timeout
AssertionError: Async operation timed out after 5 seconds

      Nested tests following this error have not been run.
  ✓ OK » 941 honored • 0 broken (7.043127s)
```

This is not displayed whene running 
```
make ci_test
```
like in travis so noone may pay attention to this.
Am I alone in this case ?

**Comment by masom** [comment]
@heynemann Seems like a bug in PyVows ?

**Comment by heynemann** [comment]
It does... I have a branch right now where I'm converting tests to nose. I don't have enough time to dedicate to maintaining both thumbor and pyvows. So I intend to make sure thumbor has better coverage and a better test suite.

Very sorry for these issues.
