### ISSUE TITLE
5.2.0 upload.py vows tests fail

### ISSUE THREAD

**Issue by dhardy92** [thumbor/thumbor#579]
Hello there since 5.2.0 version vows tests fails mainly on vows/upload_api_vows.py
```
 dhardy@viaduc436:~/SOURCE/GIT/thumbor$ pyvows vows/upload_api_vows.py
WARNING:thumbor:Unsupported Media Type
WARNING:tornado.access:415 POST /image (127.0.0.1) 7.29ms
WARNING:thumbor:Unsupported Media Type
WARNING:tornado.access:415 PUT /image/e5bcf126-791b-4375-9f73-925ab8b9fb5g (127.0.0.1) 0.62ms
WARNING:thumbor:Image not found at the given URL
WARNING:tornado.access:404 GET /image/e5bcf126-791b-4375-9f73-925ab8b9fb5g123456 (127.0.0.1) 0.54ms
WARNING:thumbor:Unsupported Media Type
WARNING:tornado.access:415 PUT /image/e5bcf126-791b-4375-9f73-925ab8b9fb5f (127.0.0.1) 0.59ms
WARNING:thumbor:Image not found at the given URL
WARNING:tornado.access:404 GET /image/e5bcf126-791b-4375-9f73-925ab8b9 (127.0.0.1) 0.65ms
WARNING:thumbor:Unsupported Media Type
WARNING:tornado.access:415 POST /image (127.0.0.1) 0.74ms
WARNING:thumbor:Unsupported Media Type
WARNING:tornado.access:415 POST /image (127.0.0.1) 0.59ms
WARNING:thumbor:Unsupported Media Type
WARNING:tornado.access:415 POST /image (127.0.0.1) 0.56ms
WARNING:thumbor:Unsupported Media Type
WARNING:tornado.access:415 POST /image (127.0.0.1) 0.56ms
WARNING:thumbor:Unsupported Media Type
WARNING:tornado.access:415 POST /image (127.0.0.1) 0.54ms
WARNING:thumbor:Unsupported Media Type
WARNING:tornado.access:415 POST /image (127.0.0.1) 0.55ms
WARNING:thumbor:Image not found at the given URL
WARNING:tornado.access:404 DELETE /image/an/unknown/image (127.0.0.1) 0.52ms
WARNING:thumbor:Image not found at the given URL
WARNING:tornado.access:404 GET /image/an/unknown/image (127.0.0.1) 0.70ms
WARNING:thumbor:Unsupported Media Type
WARNING:tornado.access:415 POST /image (127.0.0.1) 0.60ms
WARNING:thumbor:Image is too small (Expected: %s/%s , Actual : %s/%s) % (conf.MIN_WIDTH, conf.MIN_HEIGHT, size[0], size[1])
WARNING:tornado.access:412 POST /image (127.0.0.1) 0.62ms
WARNING:thumbor:Unsupported Media Type
WARNING:tornado.access:415 POST /image (127.0.0.1) 0.57ms
WARNING:thumbor:Image is too small (Expected: %s/%s , Actual : %s/%s) % (conf.MIN_WIDTH, conf.MIN_HEIGHT, size[0], size[1])
WARNING:tornado.access:412 POST /image (127.0.0.1) 0.60ms
WARNING:thumbor:Unsupported Media Type
WARNING:tornado.access:415 POST /image (127.0.0.1) 0.68ms
WARNING:thumbor:Unsupported Media Type
WARNING:tornado.access:415 POST /image (127.0.0.1) 0.60ms
WARNING:thumbor:Unsupported Media Type
WARNING:tornado.access:415 POST /image (127.0.0.1) 0.75ms
WARNING:thumbor:Image exceed max weight (Expected : 72000, Actual : 87539)
WARNING:tornado.access:412 POST /image (127.0.0.1) 0.76ms
WARNING:thumbor:Image exceed max weight (Expected : 72000, Actual : 87371)
WARNING:tornado.access:412 POST /image (127.0.0.1) 0.64ms
WARNING:thumbor:Unsupported Media Type
WARNING:tornado.access:415 POST /image (127.0.0.1) 0.56ms

 ============
 Vows Results
 ============


    Modifying an image
      When modifying an existing image

       Error in topic:
      'Location'
      
Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/gevent.py", line 104, in _run_setup_and_topic
    topic = topic_func(*topic_list)
        File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 355, in topic
    self.location = response.headers['Location']
        File "/usr/local/lib/python2.7/dist-packages/tornado/httputil.py", line 214, in __getitem__
    return dict.__getitem__(self, _normalized_headers[name])
KeyError: 'Location'

      Nested tests following this error have not been run.
    Put longer id
      When stored w ith id over32
        Http status code
        ✗ should be 200 ok
            Expected topic(404) to equal 200
            
Traceback (most recent call last):
              File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/abc.py", line 63, in run_vow
    result = vow(ctx_obj, topic)
              File "/usr/local/lib/python2.7/dist-packages/pyvows/decorators.py", line 76, in wrapper
    ret = method(*args, **kw)
              File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 440, in should_be_200_ok
    expect(topic).to_equal(200)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 232, in _assert_topic
    return _registered_assertions[method_name](self.topic, *args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 59, in wrapper
    func(*args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 128, in test_assertion
    raise AssertionError(err_msg)
AssertionError: Expected topic(404) to equal 200


             found in /home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py at line 439 

    Posting a new image
      When posting a valid image through an html form
        Http status code
        ✗ should be 201 created
            Expected topic(415) to equal 201
            
Traceback (most recent call last):
              File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/abc.py", line 63, in run_vow
    result = vow(ctx_obj, topic)
              File "/usr/local/lib/python2.7/dist-packages/pyvows/decorators.py", line 76, in wrapper
    ret = method(*args, **kw)
              File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 304, in should_be_201_created
    expect(topic).to_equal(201)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 232, in _assert_topic
    return _registered_assertions[method_name](self.topic, *args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 59, in wrapper
    func(*args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 128, in test_assertion
    raise AssertionError(err_msg)
AssertionError: Expected topic(415) to equal 201


             found in /home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py at line 303 

        Image

         Error in topic:
        'Location'
        
Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/gevent.py", line 104, in _run_setup_and_topic
    topic = topic_func(*topic_list)
          File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 317, in topic
    response.headers['Location']).group(1)
          File "/usr/local/lib/python2.7/dist-packages/tornado/httputil.py", line 214, in __getitem__
    return dict.__getitem__(self, _normalized_headers[name])
KeyError: 'Location'

        Nested tests following this error have not been run.
        Http headers
        ✗ should contain a location header containing the filename
            Expected topic({'Date': 'Thu, 15 Oct 2015 13:37:42 GMT', 'Content-Length': '0', 'Content-Type': 'text/html; charset=UTF-8', 'Server': 'TornadoServer/4.2.1'}) to include 'Location'
            
Traceback (most recent call last):
              File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/abc.py", line 63, in run_vow
    result = vow(ctx_obj, topic)
              File "/usr/local/lib/python2.7/dist-packages/pyvows/decorators.py", line 76, in wrapper
    ret = method(*args, **kw)
              File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 311, in should_contain_a_location_header_containing_the_filename
    expect(headers).to_include('Location')
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 232, in _assert_topic
    return _registered_assertions[method_name](self.topic, *args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 59, in wrapper
    func(*args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 128, in test_assertion
    raise AssertionError(err_msg)
AssertionError: Expected topic({'Date': 'Thu, 15 Oct 2015 13:37:42 GMT', 'Content-Length': '0', 'Content-Type': 'text/html; charset=UTF-8', 'Server': 'TornadoServer/4.2.1'}) to include 'Location'


             found in /home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py at line 310 

      When posting a new image with a filename
        Http headers
        ✗ should contain a location header containing the filename
            Expected topic({'Date': 'Thu, 15 Oct 2015 13:37:42 GMT', 'Content-Length': '0', 'Content-Type': 'text/html; charset=UTF-8', 'Server': 'TornadoServer/4.2.1'}) to include 'Location'
            
Traceback (most recent call last):
              File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/abc.py", line 63, in run_vow
    result = vow(ctx_obj, topic)
              File "/usr/local/lib/python2.7/dist-packages/pyvows/decorators.py", line 76, in wrapper
    ret = method(*args, **kw)
              File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 187, in should_contain_a_location_header_containing_the_filename
    expect(headers).to_include('Location')
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 232, in _assert_topic
    return _registered_assertions[method_name](self.topic, *args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 59, in wrapper
    func(*args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 128, in test_assertion
    raise AssertionError(err_msg)
AssertionError: Expected topic({'Date': 'Thu, 15 Oct 2015 13:37:42 GMT', 'Content-Length': '0', 'Content-Type': 'text/html; charset=UTF-8', 'Server': 'TornadoServer/4.2.1'}) to include 'Location'


             found in /home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py at line 186 

        Http status code
        ✗ should be 201 created
            Expected topic(415) to equal 201
            
Traceback (most recent call last):
              File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/abc.py", line 63, in run_vow
    result = vow(ctx_obj, topic)
              File "/usr/local/lib/python2.7/dist-packages/pyvows/decorators.py", line 76, in wrapper
    ret = method(*args, **kw)
              File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 180, in should_be_201_created
    expect(topic).to_equal(201)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 232, in _assert_topic
    return _registered_assertions[method_name](self.topic, *args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 59, in wrapper
    func(*args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 128, in test_assertion
    raise AssertionError(err_msg)
AssertionError: Expected topic(415) to equal 201


             found in /home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py at line 179 

      When posting a new valid image with unknwon charset in content type
        Http status code
        ✗ should be 201 created
            Expected topic(415) to equal 201
            
Traceback (most recent call last):
              File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/abc.py", line 63, in run_vow
    result = vow(ctx_obj, topic)
              File "/usr/local/lib/python2.7/dist-packages/pyvows/decorators.py", line 76, in wrapper
    ret = method(*args, **kw)
              File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 237, in should_be_201_created
    expect(topic).to_equal(201)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 232, in _assert_topic
    return _registered_assertions[method_name](self.topic, *args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 59, in wrapper
    func(*args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 128, in test_assertion
    raise AssertionError(err_msg)
AssertionError: Expected topic(415) to equal 201


             found in /home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py at line 236 

        Http headers
        ✗ should contain a location header containing the filename
            Expected topic({'Date': 'Thu, 15 Oct 2015 13:37:42 GMT', 'Content-Length': '0', 'Content-Type': 'text/html; charset=UTF-8', 'Server': 'TornadoServer/4.2.1'}) to include 'Location'
            
Traceback (most recent call last):
              File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/abc.py", line 63, in run_vow
    result = vow(ctx_obj, topic)
              File "/usr/local/lib/python2.7/dist-packages/pyvows/decorators.py", line 76, in wrapper
    ret = method(*args, **kw)
              File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 244, in should_contain_a_location_header_containing_the_filename
    expect(headers).to_include('Location')
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 232, in _assert_topic
    return _registered_assertions[method_name](self.topic, *args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 59, in wrapper
    func(*args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 128, in test_assertion
    raise AssertionError(err_msg)
AssertionError: Expected topic({'Date': 'Thu, 15 Oct 2015 13:37:42 GMT', 'Content-Length': '0', 'Content-Type': 'text/html; charset=UTF-8', 'Server': 'TornadoServer/4.2.1'}) to include 'Location'


             found in /home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py at line 243 

        Image

         Error in topic:
        'Location'
        
Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/gevent.py", line 104, in _run_setup_and_topic
    topic = topic_func(*topic_list)
          File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 250, in topic
    response.headers['Location']).group(1)
          File "/usr/local/lib/python2.7/dist-packages/tornado/httputil.py", line 214, in __getitem__
    return dict.__getitem__(self, _normalized_headers[name])
KeyError: 'Location'

        Nested tests following this error have not been run.
      When posting a new image without filename
        Http status code
        ✗ should be 201 created
            Expected topic(415) to equal 201
            
Traceback (most recent call last):
              File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/abc.py", line 63, in run_vow
    result = vow(ctx_obj, topic)
              File "/usr/local/lib/python2.7/dist-packages/pyvows/decorators.py", line 76, in wrapper
    ret = method(*args, **kw)
              File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 270, in should_be_201_created
    expect(topic).to_equal(201)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 232, in _assert_topic
    return _registered_assertions[method_name](self.topic, *args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 59, in wrapper
    func(*args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 128, in test_assertion
    raise AssertionError(err_msg)
AssertionError: Expected topic(415) to equal 201


             found in /home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py at line 269 

        Image

         Error in topic:
        'Location'
        
Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/gevent.py", line 104, in _run_setup_and_topic
    topic = topic_func(*topic_list)
          File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 283, in topic
    response.headers['Location']).group(1)
          File "/usr/local/lib/python2.7/dist-packages/tornado/httputil.py", line 214, in __getitem__
    return dict.__getitem__(self, _normalized_headers[name])
KeyError: 'Location'

        Nested tests following this error have not been run.
        Http headers
        ✗ should contain a location header containing the filename
            Expected topic({'Date': 'Thu, 15 Oct 2015 13:37:42 GMT', 'Content-Length': '0', 'Content-Type': 'text/html; charset=UTF-8', 'Server': 'TornadoServer/4.2.1'}) to include 'Location'
            
Traceback (most recent call last):
              File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/abc.py", line 63, in run_vow
    result = vow(ctx_obj, topic)
              File "/usr/local/lib/python2.7/dist-packages/pyvows/decorators.py", line 76, in wrapper
    ret = method(*args, **kw)
              File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 277, in should_contain_a_location_header_containing_the_filename
    expect(headers).to_include('Location')
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 232, in _assert_topic
    return _registered_assertions[method_name](self.topic, *args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 59, in wrapper
    func(*args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 128, in test_assertion
    raise AssertionError(err_msg)
AssertionError: Expected topic({'Date': 'Thu, 15 Oct 2015 13:37:42 GMT', 'Content-Length': '0', 'Content-Type': 'text/html; charset=UTF-8', 'Server': 'TornadoServer/4.2.1'}) to include 'Location'


             found in /home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py at line 276 

      When posting a new image with charset in content type
        Http headers
        ✗ should contain a location header containing the filename
            Expected topic({'Date': 'Thu, 15 Oct 2015 13:37:42 GMT', 'Content-Length': '0', 'Content-Type': 'text/html; charset=UTF-8', 'Server': 'TornadoServer/4.2.1'}) to include 'Location'
            
Traceback (most recent call last):
              File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/abc.py", line 63, in run_vow
    result = vow(ctx_obj, topic)
              File "/usr/local/lib/python2.7/dist-packages/pyvows/decorators.py", line 76, in wrapper
    ret = method(*args, **kw)
              File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 211, in should_contain_a_location_header_containing_the_filename
    expect(headers).to_include('Location')
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 232, in _assert_topic
    return _registered_assertions[method_name](self.topic, *args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 59, in wrapper
    func(*args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 128, in test_assertion
    raise AssertionError(err_msg)
AssertionError: Expected topic({'Date': 'Thu, 15 Oct 2015 13:37:42 GMT', 'Content-Length': '0', 'Content-Type': 'text/html; charset=UTF-8', 'Server': 'TornadoServer/4.2.1'}) to include 'Location'


             found in /home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py at line 210 

        Image

         Error in topic:
        'Location'
        
Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/gevent.py", line 104, in _run_setup_and_topic
    topic = topic_func(*topic_list)
          File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 217, in topic
    response.headers['Location']).group(1)
          File "/usr/local/lib/python2.7/dist-packages/tornado/httputil.py", line 214, in __getitem__
    return dict.__getitem__(self, _normalized_headers[name])
KeyError: 'Location'

        Nested tests following this error have not been run.
        Http status code
        ✗ should be 201 created
            Expected topic(415) to equal 201
            
Traceback (most recent call last):
              File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/abc.py", line 63, in run_vow
    result = vow(ctx_obj, topic)
              File "/usr/local/lib/python2.7/dist-packages/pyvows/decorators.py", line 76, in wrapper
    ret = method(*args, **kw)
              File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 204, in should_be_201_created
    expect(topic).to_equal(201)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 232, in _assert_topic
    return _registered_assertions[method_name](self.topic, *args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 59, in wrapper
    func(*args, **kw)
              File "/usr/local/lib/python2.7/dist-packages/preggy/core.py", line 128, in test_assertion
    raise AssertionError(err_msg)
AssertionError: Expected topic(415) to equal 201


             found in /home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py at line 203 

    Deleting an image
      When deleting an existing image

       Error in topic:
      'Location'
      
Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/gevent.py", line 104, in _run_setup_and_topic
    topic = topic_func(*topic_list)
        File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 480, in topic
    self.location = response.headers['Location']
        File "/usr/local/lib/python2.7/dist-packages/tornado/httputil.py", line 214, in __getitem__
    return dict.__getitem__(self, _normalized_headers[name])
KeyError: 'Location'

      Nested tests following this error have not been run.
    Retrieving an image
      When retrieving an existing image

       Error in topic:
Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/gevent.py", line 104, in _run_setup_and_topic
    topic = topic_func(*topic_list)
        File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 543, in topic
    self.location = response.headers['Location']
        File "/usr/local/lib/python2.7/dist-packages/tornado/httputil.py", line 214, in __getitem__
    return dict.__getitem__(self, _normalized_headers[name])
KeyError: 'Location'

      Nested tests following this error have not been run.
    Validation
      Image size constraints
        When modifying an existing image by a too small image

         Error in topic:
        'Location'
        
Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/gevent.py", line 104, in _run_setup_and_topic
    topic = topic_func(*topic_list)
          File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 705, in topic
    self.location = response.headers['Location']
          File "/usr/local/lib/python2.7/dist-packages/tornado/httputil.py", line 214, in __getitem__
    return dict.__getitem__(self, _normalized_headers[name])
KeyError: 'Location'

        Nested tests following this error have not been run.
      Invalid image
        When modifying an existing image by an invalid image

         Error in topic:
        'Location'
        
Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/gevent.py", line 104, in _run_setup_and_topic
    topic = topic_func(*topic_list)
          File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 654, in topic
    self.location = response.headers['Location']
          File "/usr/local/lib/python2.7/dist-packages/tornado/httputil.py", line 214, in __getitem__
    return dict.__getitem__(self, _normalized_headers[name])
KeyError: 'Location'

        Nested tests following this error have not been run.
      Weight constraints
        When modifying an existing image by a too weight image

         Error in topic:
        'Location'
        
Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/gevent.py", line 104, in _run_setup_and_topic
    topic = topic_func(*topic_list)
          File "/home/dhardy/SOURCE/GIT/thumbor/vows/upload_api_vows.py", line 756, in topic
    self.location = response.headers['Location']
          File "/usr/local/lib/python2.7/dist-packages/tornado/httputil.py", line 214, in __getitem__
    return dict.__getitem__(self, _normalized_headers[name])
KeyError: 'Location'

        Nested tests following this error have not been run.
  ✗ OK » 10 honored • 11 broken (0.114648s)
```

On 5.1.0, 35 tests are OK :/ did I missed a requirement ?

**Comment by dhardy92** [comment]
seams my local changes

**Comment by masom** [comment]
@dhardy92 Good to know! 5.2.0 had a bunch of internal changes.
