### ISSUE TITLE
Statsd vows tests fails at home but not on travis 

### ISSUE THREAD

**Issue by dhardy92** [thumbor/thumbor#580]
```
    Metrics vows
      Can create context with statsd metrics
      ✗ should not fail on use
          must be string, not None
          
Traceback (most recent call last):
            File "/usr/local/lib/python2.7/dist-packages/pyvows/runner/abc.py", line 63, in run_vow
    result = vow(ctx_obj, topic)
            File "/usr/local/lib/python2.7/dist-packages/pyvows/decorators.py", line 76, in wrapper
    ret = method(*args, **kw)
            File "/home/dhardy/SOURCE/GIT/thumbor/vows/metrics_vows.py", line 63, in should_not_fail_on_use
    expect(topic.metrics.incr('test.count')).not_to_be_an_error()
            File "/home/dhardy/SOURCE/GIT/thumbor/thumbor/metrics/statsd_metrics.py", line 28, in incr
    Metrics.client(self.config).incr(metricname, value)
            File "/home/dhardy/SOURCE/GIT/thumbor/thumbor/metrics/statsd_metrics.py", line 24, in client
    cls._client = statsd.StatsClient(config.STATSD_HOST, config.STATSD_PORT, config.STATSD_PREFIX)
            File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 71, in __init__
    self._addr = (socket.gethostbyname(host), port)
TypeError: must be string, not None


           found in /home/dhardy/SOURCE/GIT/thumbor/vows/metrics_vows.py at line 62
```

Seams statsd require a host instead on None but Travis tests passes ... how is this possible ?

**Comment by dhardy92** [comment]
somebody include https://github.com/auchenberg/volkswagen ?

**Comment by masom** [comment]
Weird, looking into it.

**Comment by masom** [comment]
I'm getting a bunch of different errors with vows.

Not sure how Travis succeeds the build. @heynemann and others are currently moving the tests into nose and `PyVows` might get dropped.

There is definitely something wrong.

**Comment by dhardy92** [comment]
a simple fix would be to have "localhost" as default statsd host (but does not explain the diff in behaviours)
