### ISSUE TITLE
Source URL escaped too eagerly, preventing use of custom port

### ISSUE THREAD

**Issue by gi11es** [thumbor/thumbor#593]
I have a hard time finding what change caused this, but this used to work:

http://127.0.0.1:8888/unsafe/100x100/http://www.foo.com/bar.jpg

And now it doesn't, because it seems like the entire source URL is getting escaped:

2015-11-05 17:25:28 thumbor:WARNING ERROR retrieving image http%3A//www.foo.com/bar.jpg: Unsupported url scheme: http%3A//www.foo.com/bar.jpg

Now, if I drop the scheme part of the URL, which matches the current example in the docs, it works again:

http://127.0.0.1:8888/unsafe/100x100/www.foo.com/bar.jpg
2015-11-05 17:26:34 thumbor:WARNING ERROR retrieving image http://www.foo.com/img.jpg: HTTP 404: Not Found

But that workaround doesn't work when a custom port needs to be specified in the source URL:

http://127.0.0.1:8888/unsafe/100x100/www.foo.com:8888/bar.jpg

2015-11-05 17:27:58 thumbor:WARNING ERROR retrieving image http://www.foo.com%3A8888/bar.jpg: [Errno -2] Name or service not known

**Comment by masom** [comment]
I remember a discussion about escaping / unescaping urls.

Would you mind trying to `encodeURIComponent` the url?

ex:
`http://127.0.0.1:8888/unsafe/100x100/http%3A%2F%2Fwww.foo.com%2Fbar.jpg`
`http://127.0.0.1:8888/unsafe/100x100/www.foo.com%3A8888%2Fbar.jpg`

**Comment by gi11es** [comment]
Same deal:

http://127.0.0.1:8888/unsafe/100x100/http%3A%2F%2F127.0.0.1%3A8080/images/d/da/F%C3%A9lix_et_Gilles_m%C3%AAme_%C3%A2ge.jpg

2015-11-05 17:35:53 thumbor:WARNING ERROR retrieving image http%3A//127.0.0.1%3A8080/images/d/da/F%C3%A9lix_et_Gilles_m%C3%AAme_%C3%A2ge.jpg: Unsupported url scheme: http%3A//127.0.0.1%3A8080/images/d/da/F%C3%A9lix_et_Gilles_m%C3%AAme_%C3%A2ge.jpg

http://127.0.0.1:8888/unsafe/100x100/127.0.0.1%3A8080/images/d/da/F%C3%A9lix_et_Gilles_m%C3%AAme_%C3%A2ge.jpg

2015-11-05 17:36:08 thumbor:WARNING ERROR retrieving image http://127.0.0.1%3A8080/images/d/da/F%C3%A9lix_et_Gilles_m%C3%AAme_%C3%A2ge.jpg: [Errno -2] Name or service not known

**Comment by masom** [comment]
Are you on `master` or a tagged release?

I'll look into this ASAP.

**Comment by gi11es** [comment]
master

**Comment by masom** [comment]
@gi11es should be working in `master`. The image url must be url encoded.

**Comment by gi11es** [comment]
It's having problems with accents now. Do you want me to file a new issue?

curl -i http://127.0.0.1:8889/unsafe/100x100/127.0.0.1:8080/images/5/53/F%C3%A9lix.jpg

2015-11-11 22:33:35 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 102, in get_image
    self.context.request.image_url
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 451, in _fetch
    loader_result = yield self.context.modules.loader.load(self.context, url)
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 473, in wrapper
    future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 461, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/thumbor/loaders/http_loader.py", line 76, in load
    load_sync(context, url, callback, normalize_url_func)
  File "/usr/local/lib/python2.7/site-packages/thumbor/loaders/http_loader.py", line 94, in load_sync
    url=encode(url),
  File "/usr/local/lib/python2.7/site-packages/thumbor/loaders/http_loader.py", line 113, in encode
    return None if string is None else string.encode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 35: ordinal not in range(128)

2015-11-11 22:33:35 thumbor:ERROR [BaseHandler] get_image failed for url `127.0.0.1%3A8080/images/5/53/F%C3%A9lix.jpg`. error: `'ascii' codec can't decode byte 0xc3 in position 35: ordinal not in range(128)`
2015-11-11 22:33:35 tornado.access:ERROR 500 GET /unsafe/100x100/127.0.0.1:8080/images/5/53/F%C3%A9lix.jpg (127.0.0.1) 3.33ms
