### ISSUE TITLE
"make setup" probably shouldn't point to https://github.com/scikit-image/scikit-image/archive/master.zip

### ISSUE THREAD

**Issue by gi11es** [thumbor/thumbor#611]
On OS X:

```
Downloading/unpacking https://github.com/scikit-image/scikit-image/archive/master.zip
  Downloading master.zip (16.7MB): 16.7MB downloaded
  Running setup.py (path:/var/folders/zz/lg8gty616bg8t3pmh9t11xyc0000gp/T/pip-aWuTfI-build/setup.py) egg_info for package from https://github.com/scikit-image/scikit-image/archive/master.zip
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/var/folders/zz/lg8gty616bg8t3pmh9t11xyc0000gp/T/pip-aWuTfI-build/setup.py", line 82, in <module>
        __import__(lib)
      File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1131, in <module>
        rcParams = rc_params()
      File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 975, in rc_params
        return rc_params_from_file(fname, fail_on_error)
      File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1100, in rc_params_from_file
        config_from_file = _rc_params_in_file(fname, fail_on_error)
      File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
        with _open_file_or_url(fname) as fd:
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1000, in _open_file_or_url
        encoding = locale.getdefaultlocale()Ä1Å
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
        return _parse_localename(localename)
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
        raise ValueError, 'unknown locale: %s' % localename
    ValueError: unknown locale: UTF-8
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/var/folders/zz/lg8gty616bg8t3pmh9t11xyc0000gp/T/pip-aWuTfI-build/setup.py", line 82, in <module>

    __import__(lib)

  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1131, in <module>

    rcParams = rc_params()

  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 975, in rc_params

    return rc_params_from_file(fname, fail_on_error)

  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1100, in rc_params_from_file

    config_from_file = _rc_params_in_file(fname, fail_on_error)

  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file

    with _open_file_or_url(fname) as fd:

  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__

    return self.gen.next()

  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1000, in _open_file_or_url

    encoding = locale.getdefaultlocale()Ä1Å

  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale

    return _parse_localename(localename)

  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename

    raise ValueError, 'unknown locale: %s' % localename

ValueError: unknown locale: UTF-8

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /var/folders/zz/lg8gty616bg8t3pmh9t11xyc0000gp/T/pip-aWuTfI-build
Storing debug log for failure in /Users/gdubuc/.pip/pip.log
make: *** ÄsetupÅ Error 1
Gilles-Dubucs-MacBook-Air:thumbor gdubuc$ 
```

I see that I have scikit-image installed, not sure why "make setup" needs to install the latest master from github.

**Comment by gi11es** [comment]
This workaround did the trick: http://stackoverflow.com/questions/19961239/pelican-3-3-pelican-quickstart-error-valueerror-unknown-locale-utf-8

But I'm not sure that stability-wise (and security-wise) pointing to the github master for that project is a good idea.

**Comment by gi11es** [comment]
Additionally, it seems to cause scikit-image to be built every time "make setup" is called, regardless of the same checkout already being built and installed.

**Comment by guilhermef** [comment]
Fixed on https://github.com/thumbor/thumbor/commit/0e5a4083807d18901d28f313f4428e46faa4f505
