### ISSUE TITLE
"Get meta > With metadata" test fails

### ISSUE THREAD

**Issue by gi11es** [thumbor/thumbor#612]
Running "make test" on a fresh checkout on OS X I get this error:

```
ERROR:tornado.application:Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 82, in execute_image_operations
    self.context.request.engine.load(buffer, EXTENSION.get(mime, '.jpg'))
  File "/usr/local/lib/python2.7/site-packages/thumbor/engines/__init__.py", line 98, in load
    image_or_frames = self.create_image(buffer)
  File "/usr/local/lib/python2.7/site-packages/thumbor/engines/pil.py", line 63, in create_image
    img = Image.open(BytesIO(buffer))
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 2330, in open
    % (filename if filename else fp))
IOError: cannot identify image file <_io.BytesIO object at 0x10c47cd70>
```

When I look at what the buffer passed to PIL contains, it's this:

```
{"thumbor": {"operations": [{"top": 125, "right": 300, "type": "crop", "bottom": 275, "left": 0}, {"width": 800.0, "type": "resize", "height": 400.0}], "source": {"url": "image.jpg", "width": 300, "frameCount": 1, "height": 400}, "focal_points": [{"origin": "alignment", "height": 1, "width": 1, "y": 200.0, "x": 150.0, "z": 1.0}], "target": {"width": 800.0, "height": 400.0}}}
```
Surely PIL can't treat this as an image to be read. It looks like the wrong thing ends up being stored in that buffer parameter.

**Comment by gi11es** [comment]
I see that a similar issue on that test seems to happen in CI: https://travis-ci.org/thumbor/thumbor/jobs/92046290#L848

**Comment by guilhermef** [comment]
We have to convert this test to unit.
