### ISSUE TITLE
watermark doesn't work

### ISSUE THREAD

**Issue by joanscript** [thumbor/thumbor#620]
We are running thumbor version 5.2.1 and it's working well except for the watermark filter.

This is the error log:

2015-12-01 16:55:48 thumbor:DEBUG [RESULT_STORAGE] getting from /path/thumbor/v2/1D/IV/1DIV-C8mYXLsjvMy8iq5YqRqBdQ=/fit-in/300x300/filters:watermark(www.example.com/aNQiMVEBwd9vHFq3hfVk8zfaHWU=/fit-in/300x450/common/logo.png,0,0,0)/photopath/file1993998.jpg
2015-12-01 16:55:48 thumbor:DEBUG [RESULT_STORAGE] image not found at /path/thumbor/v2/1D/IV/1DIV-C8mYXLsjvMy8iq5YqRqBdQ=/fit-in/300x300/filters:watermark(www.example.com/aNQiMVEBwd9vHFq3hfVk8zfaHWU=/fit-in/300x450/common/logo.png,0,0,0)/photopath/file1993998.jpg
2015-12-01 16:55:48 thumbor:DEBUG METRICS: timing: result_storage.incoming_time:0
2015-12-01 16:55:48 thumbor:DEBUG METRICS: inc: result_storage.miss:1
2015-12-01 16:55:48 thumbor:DEBUG METRICS: inc: storage.miss:1
2015-12-01 16:55:48 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1401, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 487, in run_callback
    callback(future.result())
  File "/usr/local/lib/python2.7/dist-packages/thumbor/filters/watermark.py", line 55, in on_fetch_done
    self.watermark_engine.load(buffer, self.extension)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/engines/__init__.py", line 98, in load
    image_or_frames = self.create_image(buffer)
  File "/usr/local/lib/python2.7/dist-packages/opencv_engine/engine.py", line 78, in create_image
    imagefiledata = cv.CreateMatHeader(1, len(buffer), cv.CV_8UC1)
TypeError: object of type 'NoneType' has no len()

2015-12-01 16:55:48 tornado.access:ERROR 500 GET /1DIV-C8mYXLsjvMy8iq5YqRqBdQ=/fit-in/300x300/filters:watermark(www.example.com/aNQiMVEBwd9vHFq3hfVk8zfaHWU=/fit-in/300x450/common/logo.png,0,0,0)/photopath/file1993998.jpg (127.0.0.1) 13.36ms

What's wrong?

Thanks.
joanscript

**Comment by masom** [comment]
Before feeding the watermark url to the filter can you try urlencoding it?

**Comment by joanscript** [comment]
Hi @masom, same error urlencoding the watermark url as u mentioned:

http://www.example.com/N5MAUjbm9plIdBmvxfi3oJwsGnQ=/fit-in/300x300/filters:watermark(http%3A%2F%www.example.com%2FaNQiMVEBwd9vHFq3hfVk8zfaHWU%3D%2Ffit-in%2F300x450%2Fcommon%2Flogo.png,0,0,0)/photopath/file1993998.jpg

**Comment by masom** [comment]
Does the watermark load fine by itself?

Using thumbor to resize the logo is quite ingenious. Recursiveness!

**Comment by joanscript** [comment]
Well, I made several tests to check different options.
I tested the logo without modifications as well:

http://www.example.com/it1CQAA23vkCudBQfl1_fmZZRaQ=/filters:watermark(http%3A%2F%2Fwww.example.com%2FMsufWbBDiBQdcUdP6041qp2WGls%3D%2Fcommon%2Flogo.png,0,0,0)/photopath/file1993998.jpg

**Comment by masom** [comment]
What I meant by that is to ensure the generated logo URL is working.

Is the watermark url (`http://www.example.com/aNQiMVEBwd9vHFq3hfVk8zfaHWU=/fit-in/300x450/common/logo.png`) working?

**Comment by joanscript** [comment]
yes! I tested these watermark urls first, then use them as a filter.
