### ISSUE TITLE
Smart mode with OpenCV fails on certain images

### ISSUE THREAD

**Issue by doronfeldman** [thumbor/thumbor#622]
For example, this image:
http://s3.amazonaws.com/game-images/angry_birds_seasons.png
With resizing to 200x200 and smart mode

Throws an Exception:

2015-12-02 09:38:35 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib64/python2.7/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib64/python2.7/site-packages/thumbor/transformer.py", line 166, in do_smart_detection
    detectors[0](self.context, index=0, detectors=detectors).detect(self.after_smart_detect)
  File "/usr/local/lib64/python2.7/site-packages/thumbor/detectors/face_detector/__init__.py", line 28, in detect
    features = self.get_features()
  File "/usr/local/lib64/python2.7/site-packages/thumbor/detectors/local_detector.py", line 47, in get_features
    convert_mode = getattr(cv, 'CV_%s2GRAY' % mode)
AttributeError: 'module' object has no attribute 'CV_P2GRAY'

**Comment by guilhermef** [comment]
This shouldn't happen on the current master,
we're just doing a few more tests before releasing a new version.

**Comment by doronfeldman** [comment]
Thank you for the quick response,
I upgraded to master using:

pip install git+https://github.com/thumbor/thumbor.git --upgrade

now for the same image i get a completely different error:

/usr/local/lib64/python2.7/site-packages/PIL/Image.py:882: UserWarning: Palette images with Transparency   expressed in bytes should be converted to RGBA images
  'to RGBA images')
2015-12-02 13:33:26 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib64/python2.7/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib64/python2.7/site-packages/thumbor/handlers/__init__.py", line 161, in get_image
    self.filters_runner.apply_filters(thumbor.filters.PHASE_AFTER_LOAD, transform)
  File "/usr/local/lib64/python2.7/site-packages/thumbor/filters/__init__.py", line 81, in apply_filters
    callback()
  File "/usr/local/lib64/python2.7/site-packages/thumbor/handlers/__init__.py", line 159, in transform
    Transformer(self.context).transform(after_transform_cb)
  File "/usr/local/lib64/python2.7/site-packages/thumbor/transformer.py", line 89, in transform
    self.smart_detect()
  File "/usr/local/lib64/python2.7/site-packages/thumbor/transformer.py", line 138, in smart_detect
    self.do_smart_detection().result()
  File "/usr/local/lib64/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib64/python2.7/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib64/python2.7/site-packages/thumbor/transformer.py", line 166, in do_smart_detection
    detectors[0](self.context, index=0, detectors=detectors).detect(self.after_smart_detect)
  File "/usr/local/lib64/python2.7/site-packages/thumbor/detectors/face_detector/__init__.py", line 38, in detect
    self.next(callback)
  File "/usr/local/lib64/python2.7/site-packages/thumbor/detectors/__init__.py", line 28, in next
    next_detector.detect(callback)
  File "/usr/local/lib64/python2.7/site-packages/thumbor/detectors/feature_detector/__init__.py", line 39, in detect
    callback()
  File "/usr/local/lib64/python2.7/site-packages/thumbor/transformer.py", line 178, in after_smart_detect
    storage.put_detector_data(self.smart_storage_key, points)
  File "/usr/local/lib64/python2.7/site-packages/thumbor/storages/file_storage.py", line 75, in put_detector_data
    _file.write(dumps(data))
  File "/usr/lib64/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: 271.0 is not JSON serializable
/usr/local/lib64/python2.7/site-packages/PIL/Image.py:882: UserWarning: Palette images with Transparency   expressed in bytes should be converted to RGBA images
  'to RGBA images')

**Comment by guilhermef** [comment]
@doronfeldman I'll take a look at this problem.

**Comment by doronfeldman** [comment]
I also noticed that before the upgrade, 
i could get http loader to load images with '™' in them by encoding the url,

right now it doesn't work any more

**Comment by guilhermef** [comment]
We're actually changing the way thumbor's deal with url's, so we're still adapting a few things, can you post a url example with ™ ?

**Comment by guilhermef** [comment]
I couldn't reproduce the detection error on my environment,  could you print what's on the variable data,
`File "/usr/local/lib64/python2.7/site-packages/thumbor/storages/file_storage.py", line 75, 
in put_detector_data
file.write(dumps(data))`
?

**Comment by doronfeldman** [comment]
https://s3.amazonaws.com/game-screenshots/star_wars™_kotor_cover.png

**Comment by doronfeldman** [comment]
Sorry, I'm completely new to python,

how exactly do i print what you need?

**Comment by guilhermef** [comment]
@doronfeldman this should solve the unicode char issue: https://github.com/thumbor/thumbor/commit/d9ed09cf7477604e2ddc663830f18054fc4a4958 

You can just edit the source and add a `print(data)` before the line 75

**Comment by doronfeldman** [comment]
@guilhermef 
This is the data variable printed:

```
[{'origin': 'alignment', 'height': 1, 'width': 1, 'y': 271.0, 'x': 202.0, 'z': 1.0}, {'origin': 'alignment', 'height': 1, 'width': 1, 'y': 228.0, 'x': 122.0, 'z': 1.0}, {'origin': 'alignment', 'height': 1, 'width': 1, 'y': 271.0, 'x': 103.0, 'z': 1.0}, {'origin': 'alignment', 'height': 1, 'width': 1, 'y': 226.0, 'x': 203.0, 'z': 1.0}, {'origin': 'alignment', 'height': 1, 'width': 1, 'y': 255.0, 'x': 115.0, 'z': 1.0}, {'origin': 'alignment', 'height': 1, 'width': 1, 'y': 232.0, 'x': 79.0, 'z': 1.0}, {'origin': 'alignment', 'height': 1, 'width': 1, 'y': 271.0, 'x': 229.0, 'z': 1.0}, {'origin': 'alignment', 'height': 1, 'width': 1, 'y': 270.0, 'x': 134.0, 'z': 1.0}, {'origin': 'alignment', 'height': 1, 'width': 1, 'y': 271.0, 'x': 139.0, 'z': 1.0}, {'origin': 'alignment', 'height': 1, 'width': 1, 'y': 254.0, 'x': 121.0, 'z': 1.0}, {'origin': 'alignment', 'height': 1, 'width': 1, 'y': 228.0, 'x': 182.0, 'z': 1.0}, {'origin': 'alignment', 'height': 1, 'width': 1, 'y': 271.0, 'x': 55.0, 'z': 1.0}, {'origin': 'alignment', 'height': 1, 'width': 1, 'y': 230.0, 'x': 249.0, 'z': 1.0}, {'origin': 'alignment', 'height': 1, 'width': 1, 'y': 230.0, 'x': 77.0, 'z': 1.0}, {'origin': 'alignment', 'height': 1, 'width': 1, 'y': 227.0, 'x': 201.0, 'z': 1.0}, {'origin': 'alignment', 'height': 1, 'width': 1, 'y': 228.0, 'x': 75.0, 'z': 1.0}, {'origin': 'alignment', 'height': 1, 'width': 1, 'y': 262.0, 'x': 91.0, 'z': 1.0}, {'origin': 'alignment', 'height': 1, 'width': 1, 'y': 230.0, 'x': 159.0, 'z': 1.0}, {'origin': 'alignment', 'height': 1, 'width': 1, 'y': 228.0, 'x': 159.0, 'z': 1.0}, {'origin': 'alignment', 'height': 1, 'width': 1, 'y': 264.0, 'x': 99.0, 'z': 1.0}]
```

**Comment by guilhermef** [comment]
@doronfeldman That's really strange, I was able to serialize this.
Could you run 
`python -c 'import json; print json.dumps([271.0])'` 
on your environment ?

**Comment by doronfeldman** [comment]
@guilhermef 
it runs just fine, prints out [271.0]

**Comment by guilhermef** [comment]
so the TypeError doesn't make any sense now, It should raise an error too.
Can you run the dumps on the data variable you've printed ?

**Comment by doronfeldman** [comment]
just tried it, it works.
i just noticed there are actually two different behaviors:

this image http://steezo.com/wp-content/uploads/2012/12/man-in-suit.jpg causes
TypeError: 176 is not JSON serializable

and the first image, http://s3.amazonaws.com/game-images/angry_birds_seasons.png
this one just hangs with no error

**Comment by doronfeldman** [comment]
@guilhermef 
by the way both these errors happen when installing from main

**Comment by guilhermef** [comment]
I think I've solved the problem: https://github.com/thumbor/thumbor/commit/bc52ab6bb8934c08d24c89ef5e52f20744468e58

We were trying to serialize a numpy.int32 type.

**Comment by doronfeldman** [comment]
@guilhermef 

It solved both!
now it works in both cases

Thank you for the quick response

**Comment by guilhermef** [comment]
Yay! \o/
Em 02/12/2015 19:47, "doronfeldman" <notifications@github.com> escreveu:

**Comment by doronfeldman** [comment]
issue closed!
