### ISSUE TITLE
Reorient gives error

### ISSUE THREAD

**Issue by gabn88** [thumbor/thumbor#641]
>tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib64/python2.7/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib64/python2.7/site-packages/thumbor/handlers/__init__.py", line 156, in get_image
    self.filters_runner.apply_filters(thumbor.filters.PHASE_AFTER_LOAD, transform)
  File "/usr/local/lib64/python2.7/site-packages/thumbor/filters/__init__.py", line 81, in apply_filters
    callback()
  File "/usr/local/lib64/python2.7/site-packages/thumbor/handlers/__init__.py", line 154, in transform
    Transformer(self.context).transform(after_transform_cb)
  File "/usr/local/lib64/python2.7/site-packages/thumbor/transformer.py", line 87, in transform
    self.engine.reorientate()
  File "/usr/local/lib64/python2.7/site-packages/thumbor/engines/__init__.py", line 178, in reorientate
    self.rotate(180)
TypeError: rotate() takes exactly 1 argument (2 given)

The issue seems to be that rotate() is defined below as
> def rotate(self):
    pass

**Comment by guilhermef** [comment]
Which engine are you using ?

**Comment by gabn88** [comment]
Nevermind. I was mixing things up from different builds and trials.
