### ISSUE TITLE
tornado.application:ERROR Exception in callback <functools.partial object at 0x7f8597ae9520>

### ISSUE THREAD

**Issue by hus787** [thumbor/thumbor#655]
Proly specific to tornado but thumbor reported this.

```
2016-02-08 07:20:02 tornado.application:ERROR Exception in callback <functools.partial object at 0x7f8597ae9520>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 600, in _run_callback
    ret = callback()
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 343, in wrapped
    raise_exc_info(exc)
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 264, in <lambda>
    future, lambda future: callback(future.result()))
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/tcpclient.py", line 174, in connect
    server_hostname=host)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)
```

**Comment by masom** [comment]
@hus787 if you take a look at the last line of this stack trace it mentions something about an invalid SSL connection.

Can you check the SSL certificate of the image you are attempting to load?

**Comment by hus787** [comment]
I can't rely tell which which image's causing this, and whether it's reproducible or not. But SSL error that is reproducible is when fetching `https://assets.weforum.org/article/image/small_8RcmFX6vMNTyr7jDAFyFDrWEutVPqCz2d2Yqbcdd_ak.jpg`

**Comment by masom** [comment]
There seem to be an issue with the certificate in question:

![image](https://cloud.githubusercontent.com/assets/438456/12890367/54ede58a-ce51-11e5-81a1-c8bad996c7b8.png)

**Comment by hus787** [comment]
Oddly, I'm unable to get that warning in either Chrome or Firefox on both Mac and Windows. Slack's image fetcher was able to fetch the preview of the images too.

![screen shot 2016-02-08 at 18 00 47](https://cloud.githubusercontent.com/assets/1750568/12890908/59b3a4dc-ce8e-11e5-9b0d-92e7bb7405ae.png)

LinkedIn had no issue either.

**Comment by masom** [comment]
Can you try using curl/wget to download the image on the affected server?

**Comment by hus787** [comment]
Running it on docker. So

`curl http://192.168.99.100:28765/unsafe/512x512/https://assets.weforum.org/article/image/small_8RcmFX6vMNTyr7jDAFyFDrWEutVPqCz2d2Yqbcdd_ak.jpg > /dev/null`
returns:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
```
And the following in the container logs:

```
2016-02-08 16:36:13 thumbor:WARNING ERROR retrieving image https://assets.weforum.org/article/image/small_8RcmFX6vMNTyr7jDAFyFDrWEutVPqCz2d2Yqbcdd_ak.jpg: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
2016-02-08 16:36:13 tornado.access:WARNING 404 GET /unsafe/512x512/https://assets.weforum.org/article/image/small_8RcmFX6vMNTyr7jDAFyFDrWEutVPqCz2d2Yqbcdd_ak.jpg (192.168.99.1) 162.14ms
```

**Comment by masom** [comment]
Which python version are you on and are you using a virtual environment?

There are some SO threads pointing to a possible error with certs:
http://stackoverflow.com/a/30209998/1014879

Testing the python installation would probably help determining the problem. It does seem to come from the SSL stack currently used.

I've tried the following successfully on my machine:
```
Python 2.7.10 (default, Sep 23 2015, 04:34:14)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> r = requests.get('https://assets.weforum.org/article/image/small_8RcmFX6vMNTyr7jDAFyFDrWEutVPqCz2d2Yqbcdd_ak.jpg')
>>> r.headers
{'Content-Length': '21744', 'x-amz-id-2': 'poUa+1xGjr0o9AC818u7xmo4p38vUQhXvGi/TVg+O4HcyZlMvilEtbE4yXfQAz0oL0NbwnDSDZE=', 'Accept-Ranges': 'bytes', 'Expires': 'Tue, 09 Feb 2016 06:13:07 GMT', 'Server': 'AmazonS3', 'Last-Modified': 'Fri, 05 Feb 2016 13:21:02 GMT', 'Connection': 'keep-alive', 'x-amz-request-id': '0275AC4E6C4AC82C', 'Cache-Control': 'max-age=43567', 'Date': 'Mon, 08 Feb 2016 18:07:00 GMT', 'Content-Type': 'image/jpeg', 'ETag': '"f934dc54b5dfe1d219f77f9cd7805acf"'}
>>>
```

And ran this through thumbor:
```
$ thumbor -l debug -c thumbor.conf
2016-02-08 13:09:19 root:DEBUG thumbor running at 0.0.0.0:8888
2016-02-08 13:09:34 thumbor:DEBUG METRICS: inc: storage.miss:1
2016-02-08 13:09:34 thumbor:DEBUG METRICS: inc: original_image.status.200:1
2016-02-08 13:09:34 thumbor:DEBUG No image format specified. Retrieving from the image extension: .jpg.
2016-02-08 13:09:34 thumbor:DEBUG Content Type of image/jpeg detected.
2016-02-08 13:09:34 tornado.access:INFO 200 GET /unsafe/https://assets.weforum.org/article/image/small_8RcmFX6vMNTyr7jDAFyFDrWEutVPqCz2d2Yqbcdd_ak.jpg (127.0.0.1) 522.95ms
```

**Comment by hus787** [comment]
The docker that I am using to test is https://hub.docker.com/r/smarp/thumbor/

The Dockerfile in question is https://github.com/Smarp/docker-thumbor/blob/56c7f8d7fd5fbf2445d844cf2a4ec8e74d3cdf82/thumbor/Dockerfile

Not sure which python version it's using exactly.

**Comment by bf** [comment]
I am experiencing the same issue with docker-thumbor.
