### ISSUE TITLE
IOError: cannot identify image file <_io.BytesIO object at 0x7f771a5b9ad0>

### ISSUE THREAD

**Issue by hus787** [thumbor/thumbor#656]
```
2016-02-08 16:50:29 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/src/app/src/thumbor/thumbor/handlers/__init__.py", line 102, in get_image
    self.context.request.image_url
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/usr/src/app/src/thumbor/thumbor/handlers/__init__.py", line 479, in _fetch
    self.context.request.engine.load(fetch_result.buffer, extension)
  File "/usr/src/app/src/thumbor/thumbor/engines/__init__.py", line 98, in load
    image_or_frames = self.create_image(buffer)
  File "/usr/src/app/src/thumbor/thumbor/engines/pil.py", line 57, in create_image
    img = Image.open(BytesIO(buffer))
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 2330, in open
    % (filename if filename else fp))
IOError: cannot identify image file <_io.BytesIO object at 0x7f771a5b9ad0>
```

**Comment by dettier** [comment]
I have the same problem with some images (they all made on one camera).
`cannot identify image file <_io.BytesIO object at 0x...>`

For example, this one Thumbor cannot handle (browsers open it just fine):
https://s3.eu-central-1.amazonaws.com/2m2-public/thumbor_problem_image/pkhq3aixtloa3snfxevd.jpg

Thumbor link for it (which is not working):
http://thumbor.thumborize.me/unsafe/500x350/https://s3.eu-central-1.amazonaws.com/2m2-public/thumbor_problem_image/pkhq3aixtloa3snfxevd.jpg

**Comment by masom** [comment]
@dettier Seems like your image is corrupted:
``/Users/martin/venvs/testing/lib/python2.7/site-packages/PIL/JpegImagePlugin.py:737: UserWarning: Image appears to be a malformed MPO file, it will be interpreted as a base JPEG file
  warnings.warn("Image appears to be a malformed MPO file, it will be "```

**Comment by masom** [comment]
@hus787 We'll need more details than that. This error is raised when a resource is not identifiable by Pillow.

Pillow's support for images is highly dependent on the available libraries at the time of installation.

**Comment by guilhermef** [comment]
Could be related to: https://github.com/python-pillow/Pillow/pull/1350

**Comment by guilhermef** [comment]
I've update the master to the latest Pillow release, It should work now.

**Comment by hus787** [comment]
@masom Yeah, iirc, the image was probably not available. But the point is that the error should be gracefully handled. Can't recall whether it crashed down the service or not.
