### ISSUE TITLE
AttributeError in pexif.py?

### ISSUE THREAD

**Issue by tinusg** [thumbor/thumbor#672]
I ran into a problem where lots of images are not resized. I checked the logs and found errors that look like this. Anyone an idea where I might find the cause of this issue?

```
2016-02-21 19:55:35 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/dist-packages/thumbor-6.0.0b3-py2.7-linux-x86_64.egg/thumbor/handlers/__init__.py", line 177, in get_image
    self.filters_runner.apply_filters(thumbor.filters.PHASE_AFTER_LOAD, transform)
  File "/usr/local/lib/python2.7/dist-packages/thumbor-6.0.0b3-py2.7-linux-x86_64.egg/thumbor/filters/__init__.py", line 81, in apply_filters
    callback()
  File "/usr/local/lib/python2.7/dist-packages/thumbor-6.0.0b3-py2.7-linux-x86_64.egg/thumbor/handlers/__init__.py", line 175, in transform
    self.context.transformer.transform(after_transform_cb)
  File "/usr/local/lib/python2.7/dist-packages/thumbor-6.0.0b3-py2.7-linux-x86_64.egg/thumbor/transformer.py", line 100, in transform
    self.engine.reorientate()
  File "/usr/local/lib/python2.7/dist-packages/thumbor-6.0.0b3-py2.7-linux-x86_64.egg/thumbor/engines/__init__.py", line 258, in reorientate
    segment.primary['Orientation'] = [1]
  File "/usr/local/lib/python2.7/dist-packages/pexif.py", line 953, in _get_property
    raise AttributeError
```

**Comment by tinusg** [comment]
Looks like it fails when no orientation information is available ([example](http://metapicz.com/#landing?imgsrc=http%3A%2F%2Fpictures.tractorfan.nl%2Forigineel%2Fm%2Fmccormick%2F955468-meerdere-mccormick.jpg))

**Comment by tinusg** [comment]
These are my first line ever in Python so I don't know if this is worth a pull request, but I resolved the issue above with the following lines in the reorientate() function: 
`if orientation != 1 and override_exif:
            try:
                segment = self._get_exif_segment()
                if segment:
                    segment.primary['Orientation'] = [1]
                    self.exif = segment.get_data()
            except AttributeError:
                pass`

**Comment by gabn88** [comment]
This is fixed in the latest master, except for the outstanding pull request (https://github.com/thumbor/thumbor/pull/679).

**Comment by marcelometal** [comment]
Hi! I'm closing this issue because 'pexif' was replaced by 'piexif'.

Ref: 1d7f67c
