### ISSUE TITLE
Inconsistent paths upload and image processing

### ISSUE THREAD

**Issue by mprzytulski** [thumbor/thumbor#693]
When you upload image with REST API it will return location header which contains location of the resource, for example:

`/image/74c9b8688535466da795e7a379aad873/image.jpg`

but if you would like to do any transformations on that image for example scale it, you need to use only location hash and slug: 
`http://localhost:8888/unsage/300x300/d8623ce45a3d46679173bbb56b582c0b/image.jpg`

if you try concatenate value returned in location with image processing URL you will get HTTP 404, also if you remove slug parameter and try with URL like this:
`http://localhost:8888/unsafe/300x300/74c9b8688535466da795e7a379aad873``
you will get IOException:

```
2016-03-22 22:45:37 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/Users/me/projects/os/envs/thumbor/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/Users/me/projects/os/envs/thumbor/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 67, in execute_image_operations
    result = yield gen.maybe_future(self.context.modules.result_storage.get())
  File "/Users/me/projects/os/envs/thumbor/lib/python2.7/site-packages/tornado/concurrent.py", line 473, in wrapper
    future.result()
  File "/Users/me/projects/os/envs/thumbor/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Users/me/projects/os/envs/thumbor/lib/python2.7/site-packages/tornado/concurrent.py", line 461, in wrapper
    result = f(*args, **kwargs)
  File "/Users/me/projects/os/envs/thumbor/lib/python2.7/site-packages/thumbor/result_storages/file_storage.py", line 62, in get
    with open(file_abspath, 'r') as f:
IOError: [Errno 21] Is a directory: '/Users/me/projects/own/storage/results/v2/un/sa/unsafe/300x300/74c9b8688535466da795e7a379aad873'
```

**Comment by heynemann** [comment]
As I said in previous requests for uploading features, we'll probably remove uploading from thumbor to another project. As of today uploading is a very stitched version of what the actual uploading feature set should be. As such, we probably won't fix this in thumbor's codebase.
As soon as we release the uploading code in a different project, this may very well be fixed.

If you have any further questions on this issue, please reopen it.

**Comment by heynemann** [comment]
I didn't see a PR open for this. I'll check the PR soon.
