### ISSUE TITLE
Error when retreiving image metadata

### ISSUE THREAD

**Issue by qsomazzi** [thumbor/thumbor#695]
Hello,

I've got an issue since the new release of Thumbor (v6.0.1).
I try to check the smart-cropping meta-data for some image. 
I call "/unsafe/meta/220x300/smart/behat/behat_manonleft_nodelete.jpg" for the first time, it's works.
When I call it again, I've got this error : 

```
2016-03-24 14:57:03 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/home/thumbor/thumborenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/home/thumbor/thumborenv/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 86, in execute_image_operations
    self.context.request.engine.load(buffer, EXTENSION.get(mime, '.jpg'))
  File "/home/thumbor/thumborenv/local/lib/python2.7/site-packages/thumbor/engines/__init__.py", line 136, in load
    image_or_frames = self.create_image(buffer)
  File "/home/thumbor/thumborenv/local/lib/python2.7/site-packages/thumbor/engines/pil.py", line 63, in create_image
    img = Image.open(BytesIO(buffer))
  File "/home/thumbor/thumborenv/local/lib/python2.7/site-packages/PIL/Image.py", line 2295, in open
    % (filename if filename else fp))
IOError: cannot identify image file <_io.BytesIO object at 0x28a8fb0>
```

Here is my `pip freeze` : 

```
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
botocore==1.2.0
certifi==2016.2.28
colour==0.1.2
derpconf==0.7.3
docutils==0.12
futures==3.0.5
jmespath==0.7.1
libthumbor==1.3.1
numpy==1.10.4
opencv-engine==1.0.1
pexif==0.15
Pillow==3.1.1
pycrypto==2.6.1
pycurl==7.19.5.3
python-dateutil==2.5.1
python-magic==0.4.11
pytz==2016.2
redis==2.10.5
shortuuid==0.4.3
singledispatch==3.4.0.3
six==1.10.0
statsd==3.2.1
tc-aws==6.0.0
tc-core==0.3.0
tc-redis==1.0.1
tc-shortener==0.2.2
thumbor==6.0.1
tornado==4.3
tornado-botocore==1.0.2
```

And my thumbor conf : 

```
COMMUNITY_EXTENSIONS = ["tc_shortener"]
DETECTORS = ["thumbor.detectors.face_detector", "thumbor.detectors.profile_detector", "thumbor.detectors.glasses_detector", "thumbor.detectors.feature_detector"]
ENGINE = "thumbor.engines.pil"
FACE_DETECTOR_CASCADE_FILE = "haarcascade_frontalface_default.xml"
FILTERS = ["thumbor.filters.brightness", "thumbor.filters.no_upscale", "thumbor.filters.colorize", "thumbor.filters.contrast", "thumbor.filters.equalize", "thumbor.filters.format", "thumbor.filters.rotate", "thumbor.filters.quality", "thumbor.filters.fill", "thumbor.filters.saturation", "thumbor.filters.rgb", "thumbor.filters.round_corner", "thumbor.filters.quality", "thumbor.filters.sharpen", "thumbor.filters.noise", "thumbor.filters.watermark", "thumbor.filters.blur", "thumbor.filters.grayscale", "thumbor.filters.strip_icc", "thumbor.filters.convolution", "thumbor.filters.extract_focal", "thumbor.filters.max_bytes"]
JPEGTRAN_PATH = "/usr/bin/jpegtran"
LOADER = "tc_aws.loaders.s3_loader"
METRICS = "thumbor.metrics.statsd_metrics"
MIXED_STORAGE_CRYPTO_STORAGE = "tc_redis.storages.redis_storage"
MIXED_STORAGE_DETECTOR_STORAGE = "tc_redis.storages.redis_storage"
MIXED_STORAGE_FILE_STORAGE = "tc_aws.storages.s3_storage"
OPTIMIZERS = ["thumbor.optimizers.jpegtran"]
PNGQUANT_PATH = "/usr/local/bin/pngquant"
REDIS_STORAGE_SERVER_DB = 0
REDIS_STORAGE_SERVER_HOST = "localhost"
REDIS_STORAGE_SERVER_PASSWORD = ""
REDIS_STORAGE_SERVER_PORT = 6379
RESULT_STORAGE = "tc_aws.result_storages.s3_storage"
RESULT_STORAGE_STORES_UNSAFE = True
SEND_IF_MODIFIED_LAST_MODIFIED_HEADERS = True
SHORTENER_REDIS_STORAGE_SERVER_DB = 0
SHORTENER_REDIS_STORAGE_SERVER_HOST = "localhost"
SHORTENER_REDIS_STORAGE_SERVER_PORT = 6379
STATSD_HOST = "localhost"
STATSD_PREFIX = "thumbor"
STORAGE = "thumbor.storages.mixed_storage"
TC_AWS_LOADER_BUCKET = "mybucket"
TC_AWS_REGION = "eu-west-1"
TC_AWS_RESULT_STORAGE_BUCKET = "mybucket"
TC_AWS_RESULT_STORAGE_ROOT_PATH = "/results"
TC_AWS_STORAGE_BUCKET = "mybucket"
TC_AWS_STORAGE_ROOT_PATH = "/storage"
TC_AWS_STORAGE_RSS = False
```

Thanks for your help !

**Comment by masom** [comment]
Thanks for reporting this issue @qsomazzi.

It seems like thumbor is saving the result of the metadata into the result storage, breaking future requests.

**Comment by gmarchand** [comment]
+1 This feature is usefull to make our non-regression testing on smart cropping.

**Comment by heynemann** [comment]
Sorry for the long time it took to reply.

Any chance you can confirm if this is still an issue?

**Comment by heynemann** [comment]
Closing this issue since we had no activity for a while in the interest of keeping our Issues list leaner. If this is something we still need to pursue, please reopen and I'll look into it. Thanks!
