### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by paranpi** [thumbor/thumbor#782]
### Thumbor request URL
http://ec2-52-36-162-97.us-west-2.compute.amazonaws.com:8888/unsafe/640x0/test.jpg

### Expected behaviour
response 404

### Actual behaviour
response 504

### Operating system
Ubuntu

When I request invalid url , occured error.

ERROR LOG:
2016-07-18 09:31:57 thumbor:DEBUG METRICS: inc: response.count:1
2016-07-18 09:31:57 thumbor:DEBUG METRICS: inc: storage.miss:1
2016-07-18 09:31:57 thumbor:DEBUG METRICS: inc: original_image.status.404:1
2016-07-18 09:31:57 thumbor:WARNING ERROR retrieving image http://img-wishbeen.akamaized.net/plan/test.jpg: HTTP 404: Not Found
2016-07-18 09:31:57 tornado.access:WARNING 404 GET /unsafe/640x0/img-wishbeen.akamaized.net/plan/test.jpg (106.251.233.114) 21.43ms
2016-07-18 09:31:57 thumbor:DEBUG METRICS: timing: response.time:20
2016-07-18 09:31:57 thumbor:DEBUG METRICS: timing: response.time.404:20
2016-07-18 09:31:57 thumbor:DEBUG METRICS: inc: response.status.404:1
2016-07-18 09:31:57 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib64/python2.7/site-packages/thumbor/handlers/__init__.py", line 147, in get_image
    self._error(404)
  File "/usr/local/lib64/python2.7/site-packages/thumbor/handlers/__init__.py", line 85, in _error
    self.finish()
  File "/usr/local/lib64/python2.7/site-packages/tornado/web.py", line 956, in finish
    self.on_finish()
  File "/usr/local/lib64/python2.7/site-packages/thumbor/handlers/__init__.py", line 71, in on_finish
    if hasattr(self.context, 'request') and self.context.request.engine:
AttributeError: RequestParameters instance has no attribute 'engine'

2016-07-18 09:31:57 thumbor:ERROR [BaseHandler] get_image failed for url `img-wishbeen.akamaized.net/plan/test.jpg`. error: `RequestParameters instance has no attribute 'engine'`
2016-07-18 09:31:57 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib64/python2.7/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib64/python2.7/site-packages/thumbor/handlers/__init__.py", line 177, in get_image
    self._error(500)
  File "/usr/local/lib64/python2.7/site-packages/thumbor/handlers/__init__.py", line 85, in _error
    self.finish()
  File "/usr/local/lib64/python2.7/site-packages/tornado/web.py", line 923, in finish
    raise RuntimeError("finish() called twice")
RuntimeError: finish() called twice
2016-07-18 09:31:58 thumbor:DEBUG METRICS: inc: response.count:1
2016-07-18 09:31:58 thumbor:WARNING URL does not have hash or unsafe, or has both: /favicon.ico
2016-07-18 09:31:58 tornado.access:WARNING 400 GET /favicon.ico (106.251.233.114) 1.74ms
2016-07-18 09:31:58 thumbor:DEBUG METRICS: timing: response.time:1
2016-07-18 09:31:58 thumbor:DEBUG METRICS: timing: response.time.400:1
2016-07-18 09:31:58 thumbor:DEBUG METRICS: inc: response.status.400:1`

**Comment by rfloriano** [comment]
My bad @paranpi!
Fixed in Thumbor 6.1.1.
