### ISSUE TITLE
rare exception, image becomes None

### ISSUE THREAD

**Issue by phoet** [thumbor/thumbor#788]
we are running a recent version of thumbor (`f813c18bef0b7c0c73bd69572b06d3f20a8be8bd`) and once and a while we see an exception where i don't have a clue for how to debug it. unfortunately we don't see which image is causing this as we have many thousand requests on that app.

any ideas?

```
AttributeError: 'NoneType' object has no attribute 'mode'
2016-07-22 10:47:38 tornado.application:ERROR Exception in callback <functools.partial object at 0x7f3c0078f260>
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 604, in _run_callback
ret = callback()
File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
return fn(*args, **kwargs)
File "/usr/src/app/src/thumbor/thumbor/transformer.py", line 226, in inner
self.done_callback()
File "/usr/src/app/src/thumbor/thumbor/handlers/__init__.py", line 220, in after_transform
self.filters_runner.apply_filters(thumbor.filters.PHASE_POST_TRANSFORM, finish_callback)
File "/usr/src/app/src/thumbor/thumbor/filters/__init__.py", line 91, in apply_filters
exec_one_filter()
File "/usr/src/app/src/thumbor/thumbor/filters/__init__.py", line 90, in exec_one_filter
f.run(exec_one_filter)
File "/usr/src/app/src/thumbor/thumbor/filters/__init__.py", line 201, in run
callback()
File "/usr/src/app/src/thumbor/thumbor/filters/__init__.py", line 90, in exec_one_filter
f.run(exec_one_filter)
File "/usr/src/app/src/thumbor/thumbor/filters/__init__.py", line 198, in run
results.append(self.runnable_method(*self.params))
File "/usr/src/app/src/thumbor/thumbor/filters/__init__.py", line 23, in wrapper
return fn(self, *args2)
File "/usr/src/app/src/thumbor/thumbor/filters/rotate.py", line 20, in rotate
self.engine.rotate(value)
File "/usr/src/app/src/thumbor/thumbor/engines/pil.py", line 124, in rotate
self.image = self.image.rotate(degrees, expand=1)
File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 1575, in rotate
return self._new(self.im)
File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 522, in _new
new.mode = im.mode
AttributeError: 'NoneType' object has no attribute 'mode'
```

**Comment by rfloriano** [comment]
@phoet,
The "mode" attribute is setted by Pillow when an image is readed/loaded, so this seems like to be a Pillow bug, however I cannot be sure without the requested image.
I know that you have many request, but can you find that requested image to I can debug this issue?

**Comment by phoet** [comment]
i'll try to use a patched version that prints out what image is failing so we can have something to debug.

**Comment by heynemann** [comment]
@phoet is this still happening? If not, what did you do to fix it?

**Comment by phoet** [comment]
unfortunately i'm not working on this project anymore. i guess it must have been one of the largest thumbor setups with some hundred nodes running an terrabytes of cdn traffic.
