### ISSUE TITLE
ERROR Ignored error handling exif for reorientation

### ISSUE THREAD

**Issue by event15** [thumbor/thumbor#795]
I have an incredible issue.

I use thumbor for basic images operations. I use php interface for preparing data for thumbor.
This is what i send to method where i use thumbor:

```
Array
(
    [size] => {"h":51,"w":116}
    [crop] => null
    [fit] => ""
    [fill] => 
    [hash] => APC49f2K
    [layout] => brandpost
    [csrf_token] => 20813266681162e81b4f55e5d67d04b54851af50
    [name] => witcher-3-wild-hunt-the-avatar-01_f015.jpg
    [extension] => jpg
    [mime] => image/jpeg
    [md5] => c414f90784f1716481479e3cdc3c266f
    [dimensions] => Array
        (
            [width] => 600
            [height] => 600
        )

    [directory] => //my.domain/embed/A/P/APC49f2K/assets
    [path] => //my.domain/embed/A/P/APC49f2K/assets/witcher-3-wild-hunt-the-avatar-01_f015.jpg
    [relative] => /embed/A/P/APC49f2K/assets/witcher-3-wild-hunt-the-avatar-01_f015.jpg
)
```

My application have in config a special array for sizes to generate. 

```
'sizes' => [
                [ 'w' => 116, 'h' => 0 ], 
                [ 'w' => 360, 'h' => 0 ],  
                [ 'w' => 660, 'h' => 0 ],
                [ 'w' => 986, 'h' => 0 ],
                [ 'w' => 1202, 'h' => 0 ]
            ]
```

All width number works when i skip  `w => 986`. 

For example, when I have 116px width, my thumbor method returns:

```
Array
(
    [url] => /_thumbor/ASTRhL1Gmv-nAuz55wTMuJUDvXg=/0x247:600x511/116x51/embed/A/P/APC49f2K/assets/witcher-3-wild-hunt-the-avatar-01_bdf2.jpg
    [ori] => //embed.my.domain/_thumbor/XCmk4pKYCvFXrwdQ8cC-d6OkJwc=/embed/A/P/APC49f2K/assets/witcher-3-wild-hunt-the-avatar-01_bdf2.jpg
    [size] => Array
        (
            [w] => 116
            [h] => 51
        )

    [crop] => Array
        (
            [top] => 247
            [right] => 600
            [bottom] => 511
            [left] => 0
        )

)
```

When width is `986` my serwer throw a 504 Gateway Timed Out. 

This is debug info from thumbor docker: http://hastebin.com/vahosayowi.sm

Sometimes i have troubles with tornado: http://hastebin.com/epoyurivur.sm (i don't know why)

When i set `RESPECT_ORIENTATION = True` in thumbor.conf i have this error: 

```
2016-08-09 08:50:05 thumbor:ERROR Ignored error handling exif for reorientation
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thumbor/engines/__init__.py", line 229, in _get_exif_segment
    segment = ExifSegment(None, None, self.exif, 'ro')
AttributeError: 'JSONEngine' object has no attribute 'exif'
2016-08-09 08:50:05 thumbor:ERROR Ignored error handling exif for reorientation
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thumbor/engines/__init__.py", line 229, in _get_exif_segment
    segment = ExifSegment(None, None, self.exif, 'ro')
AttributeError: 'JSONEngine' object has no attribute 'exif'
2016-08-09 08:50:05 thumbor:ERROR Ignored error handling exif for reorientation
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thumbor/engines/__init__.py", line 229, in _get_exif_segment
    segment = ExifSegment(None, None, self.exif, 'ro')
AttributeError: 'JSONEngine' object has no attribute 'exif'
2016-08-09 08:50:05 thumbor:ERROR Ignored error handling exif for reorientation
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thumbor/engines/__init__.py", line 229, in _get_exif_segment
    segment = ExifSegment(None, None, self.exif, 'ro')
AttributeError: 'JSONEngine' object has no attribute 'exif'
-bash-4.2$ sudo docker exec -it docker-thumbor-server bash
```
### Operating system

```
root@3a88e68fac69:/# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
Stepping:              2
CPU MHz:               1327.500
CPU max MHz:           3200.0000
CPU min MHz:           1200.0000
BogoMIPS:              4809.37
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-7,16-23
NUMA node1 CPU(s):     8-15,24-31
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc


// https://github.com/phusion/baseimage-docker
root@3a88e68fac69:/# uname -a
Linux 3a88e68fac69 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@3a88e68fac69:/# 

```
### Your thumbor.conf

```
root@3a88e68fac69:/# cat etc/thumbor/thumbor.conf 
ALLOW_UNSAFE_URL = True
ALLOW_OLD_URLS = False
LOADER = 'thumbor.loaders.http_loader'

STORAGE_EXPIRATION_SECONDS = 60 * 60 * 24  # one day
FILE_STORAGE_ROOT_PATH = '/srv/thumbor/storage/original'

RESULT_STORAGE = 'thumbor.result_storages.file_storage'
RESULT_STORAGE_EXPIRATION_SECONDS = 60 * 60 * 24 * 30  # one month
RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '/srv/thumbor/storage/processed'

DETECTORS = [
    'thumbor.detectors.face_detector',
    'thumbor.detectors.feature_detector',
]

OPTIMIZERS = [
    'thumbor.optimizers.jpegtran',
]

JPEGTRAN_PATH = '/usr/bin/jpegtran'
PROGRESSIVE_JPEG = True

OPTIPNG_PATH = '/usr/bin/optipng'
OPTIPNG_LEVEL = 5

LOADER = 'thumbor.loaders.file_loader'
FILE_LOADER_ROOT_PATH = '/data/http'

# base security
ALLOWED_SOURCES = ['..............']
SECURITY_KEY = "........"
ALLOW_UNSAFE_URL = False
ALLOW_OLD_URLS = False

# imaging config
AUTO_WEBP = True
RESPECT_ORIENTATION = True

# size restrictions
MAX_WIDTH = 5000
MAX_HEIGHT = 5000
MIN_WIDTH = 50
MIN_HEIGHT = 50
UPLOAD_MAX_SIZE = 5120 # Kb = 5Mb

# redis queue
REDIS_QUEUE_SERVER_HOST = 'pc-redis-server'
REDIS_QUEUE_SERVER_PORT = 6379
REDIS_QUEUE_SERVER_DB = 14
REDIS_QUEUE_SERVER_PASSWORD = None

```

Sorry for my English, I still learning this language :)

**Comment by event15** [comment]
Oh, i forgot. This is image which i try upload: https://cdn.pbrd.co/images/7GXjuZt71.jpg

**Comment by heynemann** [comment]
Sorry for the long wait. Do you know if this is still an issue?

**Comment by heynemann** [comment]
Closing this issue since we had no activity for a while in the interest of keeping our Issues list leaner. If this is something we still need to pursue, please reopen and I'll look into it. Thanks!
