### ISSUE TITLE
AttributeError: 'cv2.cv.iplimage' object has no attribute 'tobytes'

### ISSUE THREAD

**Issue by fmunteanu** [thumbor/thumbor#817]
While running Thumbor, I encounter this error:

```
2016-10-13 04:09:42 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 270, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/thumbor/handlers/__init__.py", line 362, in finish_request
    callback=inner,
  File "/usr/lib64/python2.7/site-packages/thumbor/context.py", line 284, in queue
    self._execute_in_foreground(operation, callback)
  File "/usr/lib64/python2.7/site-packages/thumbor/context.py", line 272, in _execute_in_foreground
    callback(result)
  File "/usr/lib64/python2.7/site-packages/thumbor/handlers/__init__.py", line 355, in inner
    self._write_results_to_client(context, results, content_type)
  File "/usr/lib64/python2.7/site-packages/thumbor/handlers/__init__.py", line 394, in _write_results_to_client
    self.finish()
  File "/usr/lib64/python2.7/site-packages/tornado/web.py", line 955, in finish
    self.on_finish()
  File "/usr/lib64/python2.7/site-packages/thumbor/handlers/__init__.py", line 78, in on_finish
    len(self.context.request.engine.image.tobytes())
AttributeError: 'cv2.cv.iplimage' object has no attribute 'tobytes'
```

Can you please let me know how to address this until is fixed into a release?

**Comment by Arthien** [comment]
Are you using the base version of openCV that thumbor provides, or are you using a different build?

Also, what are your steps to reproduce aside from "running thumbor"?

**Comment by fmunteanu** [comment]
Hi @Arthien,

I'm using the version provided by CentOS7, 2.4.5. Whould you recommend me to use a different version? I have thumbor and opencv_engine Python packages working properly, images are served with a security key.

```
$ cat /etc/thumbor.conf
ALLOW_OLD_URLS = False
ALLOW_UNSAFE_URL = False
ENGINE = 'opencv_engine'
HTTP_LOADER_MAX_CLIENTS = 1024
STATSD_HOST = 'statsd.domain.com'
STATSD_PORT = 8125
STATSD_PREFIX = 'thumbor'
STORAGE = 'thumbor.storages.file_storage'
STORAGE_EXPIRATION_SECONDS = 3600
```

**Comment by wangbaifeng** [comment]
@fmunteanu   
**I also met this problem，this problem solved?**  
Please help me！
Please help me！
Please help me！

**Comment by wangbaifeng** [comment]
@masom  
Using the "opencv_engine" there will be this problem， this problem is bug？

**Comment by masom** [comment]
@wangbaifeng Please no need to repeatedly ask for help or ping people on issues to get things resolved. #830 should fix this by using the output buffer length instead of calling a method on the engine.

**Comment by wangbaifeng** [comment]
Thanks @masom

**Comment by Savar** [comment]
can this ticket be closed?

**Comment by wangbaifeng** [comment]
@Savar ok

**Comment by Savar** [comment]
@fmunteanu can you close this issue in case you don't have any question anymore?

**Comment by fmunteanu** [comment]
Thank you for your support.
