### ISSUE TITLE
tornado.application:ERROR Exception in callback <functools.partial object at 0x7f0a87b7f578>

### ISSUE THREAD

**Issue by hus787** [thumbor/thumbor#818]
### Thumbor request URL

/unsafe/full-fit-in/500x500/smart/filters:max_bytes(2621440)/https%3A%2F%2Fdeveloper-content.emc.com%2Fecn%2FUX%2Fimage%2Fsearch2.jpg
### Expected behaviour

Fetch the image
### Actual behaviour

Can't fetch the image

The logs:

```
2016-10-21 08:22:13 thumbor:WARNING ERROR retrieving image https://developer-content.emc.com/ecn/UX/image/search2.jpg: HTTP 599: Timeout
2016-10-21 08:22:13 tornado.access:ERROR 504 GET /unsafe/full-fit-in/500x500/smart/filters:max_bytes(2621440)/https%3A%2F%2Fdeveloper-content.emc.com%2Fecn%2FUX%2Fimage%2Fsearch2.jpg (172.17.0.1) 5067.48ms
2016-10-21 08:22:13 tornado.general:WARNING SSL Error on 9 ('137.69.115.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
2016-10-21 08:22:13 thumbor:WARNING URL does not have hash or unsafe, or has both: /favicon.ico
2016-10-21 08:22:13 tornado.access:WARNING 400 GET /favicon.ico (172.17.0.1) 9.80ms
2016-10-21 08:22:13 tornado.application:ERROR Exception in callback <functools.partial object at 0x7f0a87b7f578>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 600, in _run_callback
    ret = callback()
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 343, in wrapped
    raise_exc_info(exc)
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 264, in <lambda>
    future, lambda future: callback(future.result()))
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/tcpclient.py", line 174, in connect
    server_hostname=host)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```
### Operating system
- Docker ( https://github.com/Smarp/docker-thumbor/tree/7b456daf26e50fc165a7f96335b23eef007d1645/thumbor)
### Your thumbor.conf

In the path above

**Comment by masom** [comment]
Python was unable to validate the SSL certificate used on the image host.

**Comment by masom** [comment]
It also appears like the URL is double encoded.

**Comment by hus787** [comment]
@masom nope, it's not doubled encoded. Can be confirmed from: http://meyerweb.com/eric/tools/dencoder/

**Comment by masom** [comment]
@hus787 my bad, I must have copied it wrong.

**Comment by Savar** [comment]
@hus787 is there still a question from your side or can this issue be closed?

**Comment by heynemann** [comment]
If you have any further questions on this issue, please reopen it.

**Comment by cloudfee** [comment]
make sure config: HTTP_LOADER_VALIDATE_CERTS = False
work for me
