### ISSUE TITLE
AttributeError: 'module' object has no attribute 'DecompressionBombWarning'

### ISSUE THREAD

**Issue by gonzalezlopezjm** [thumbor/thumbor#828]
Hi,

I'm trying to start a Thumbor service, I'm installing a fresh server in AWS a linux server and all are installed right. But when I try to start Thumbor I get this error:

Traceback (most recent call last):
  File "/usr/local/bin/thumbor", line 9, in <module>
    load_entry_point('thumbor==6.1.5', 'console_scripts', 'thumbor')()
  File "/usr/local/lib64/python2.7/site-packages/thumbor/server.py", line 128, in main
    with get_context(server_parameters, config, importer) as context:
  File "/usr/local/lib64/python2.7/site-packages/thumbor/server.py", line 88, in get_context
    importer=importer
  File "/usr/local/lib64/python2.7/site-packages/thumbor/context.py", line 36, in __init__
    self.modules = ContextImporter(self, importer)
  File "/usr/local/lib64/python2.7/site-packages/thumbor/context.py", line 213, in __init__
    self.engine = importer.engine(context)
  File "/usr/local/lib64/python2.7/site-packages/thumbor/engines/pil.py", line 55, in __init__
    warnings.simplefilter('error', Image.DecompressionBombWarning)
AttributeError: 'module' object has no attribute 'DecompressionBombWarning'

I'm not confidence in Python but I think that is a dependency problem, I'm not sure if is an installation problem or a bug

### Expected behaviour
That Thumbor starts

### Actual behaviour
Thumbor throws an exception

### Operating system
Linux version 4.4.23-31.54.amzn1.x86_64

### Your thumbor.conf
I have the default conf except for AWS

**Comment by masom** [comment]
Which version of Pillow/python are you using?
