### ISSUE TITLE
Thumbor not working.

### ISSUE THREAD

**Issue by vanbinh91** [thumbor/thumbor#922]
[root@connect360 bin]# thumbor
Traceback (most recent call last):
  File "/usr/bin/thumbor", line 9, in <module>
    load_entry_point('thumbor==6.3.2', 'console_scripts', 'thumbor')()
  File "/usr/lib64/python2.6/site-packages/thumbor-6.3.2-py2.6-linux-x86_64.egg/thumbor/server.py", line                                                                124, in main
    importer = get_importer(config)
  File "/usr/lib64/python2.6/site-packages/thumbor-6.3.2-py2.6-linux-x86_64.egg/thumbor/server.py", line                                                                58, in get_importer
    importer.import_modules()
  File "/usr/lib64/python2.6/site-packages/thumbor-6.3.2-py2.6-linux-x86_64.egg/thumbor/importer.py", lin                                                               e 51, in import_modules
    self.import_item('ENGINE', 'Engine')
  File "/usr/lib64/python2.6/site-packages/thumbor-6.3.2-py2.6-linux-x86_64.egg/thumbor/importer.py", lin                                                               e 95, in import_item
    module = self.import_class('%s.%s' % (conf_value, class_name))
  File "/usr/lib64/python2.6/site-packages/thumbor-6.3.2-py2.6-linux-x86_64.egg/thumbor/importer.py", lin                                                               e 43, in import_class
    return import_class(name, get_module)
  File "/usr/lib64/python2.6/site-packages/thumbor-6.3.2-py2.6-linux-x86_64.egg/thumbor/importer.py", lin                                                               e 19, in import_class
    module = get_module and __import__(name) or __import__(module_name)
  File "/usr/lib64/python2.6/site-packages/thumbor-6.3.2-py2.6-linux-x86_64.egg/thumbor/engines/__init__.                                                               py", line 12, in <module>
    from xml.etree.ElementTree import ParseError
ImportError: cannot import name ParseError

Help me!!!!!!!!!!!!

**Comment by masom** [comment]
It seems like python 2.6 does not have ElementTree.ParseError and we do not test on that version.

ParseError is only used for SVG support and we might be able to release a patch. Meanwhile you could update your python version to 2.7 using either virtualenv or some other mechanism.

**Comment by masom** [comment]
@vanbinh91 Python 2.6 support was dropped ~2 years ago. Please use virtualenv to setup python 2.7 instead of relying on the system installed version.

**Comment by vanbinh91** [comment]
Thanks you. I use python 2.7 runing thumbor v6.3.2 .

2017-05-11 20:22 GMT+07:00 Martin Samson <notifications@github.com>:

**Comment by masom** [comment]
@vanbinh91 You've upgraded your python version to 2.7 and it works?

Otherwise the stacktrace you posted mentions python 2.6.

**Comment by vanbinh91** [comment]
I update python version 2.7 but i can't remove python 2.6 because i  python
setup.py install with thumbor. Help me. :(

2017-05-11 21:31 GMT+07:00 Martin Samson <notifications@github.com>:

**Comment by vanbinh91** [comment]
[root@connect360 thumbor-6.3.2]# ls
build  dist  MANIFEST.in  PKG-INFO  setup.cfg  setup.py  thumbor
 thumbor.egg-info
[root@connect360 thumbor-6.3.2]# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    from setuptools import setup, Extension
ImportError: No module named setuptools
[root@connect360 thumbor-6.3.2]#


2017-05-12 8:46 GMT+07:00 bình nguyễn văn <nguyenvanbinh1191@gmail.com>:

**Comment by vanbinh91** [comment]
[root@connect360 thumbor-6.3.2]# python --version
Python 2.7.8


2017-05-12 8:47 GMT+07:00 bình nguyễn văn <nguyenvanbinh1191@gmail.com>:

**Comment by masom** [comment]
Usually Thumbor is installed through `pip`.

`pip install thumbor` should install all the required dependencies.

**Comment by vanbinh91** [comment]
Show me the solution. Pls.

2017-05-12 20:17 GMT+07:00 Martin Samson <notifications@github.com>:
