### ISSUE TITLE
Cannot start Thumbor with a socket

### ISSUE THREAD

**Issue by fmunteanu** [thumbor/thumbor#929]
I use Supervisor to create a socket:
```
# cat /etc/supervisord.d/thumbor.ini
[fcgi-program:thumbor]
command=/usr/bin/%(program_name)s -c /etc/%(program_name)s.conf -f /run/supervisor/%(program_name)s.sock
socket=unix:///run/supervisor/%(program_name)s.sock
socket_owner=h2o
process_name=%(program_name)s-%(process_num)s
autostart=true
autorestart=true
numprocs=4
startretries=3
stopsignal=TERM
user=h2o
stdout_logfile=/var/log/supervisor/%(program_name)s-%(process_num)s-stdout.log
stderr_logfile=/var/log/supervisor/%(program_name)s-%(process_num)s-stderr.log

# ls -lah /run/supervisor/thumbor.sock
srwx------. 1 h2o root 0 Jun  5 14:49 /run/supervisor/thumbor.sock

# /usr/bin/thumbor -c /etc/thumbor.conf -d -f /run/supervisor/thumbor.sock
Traceback (most recent call last):
  File "/usr/bin/thumbor", line 11, in <module>
    load_entry_point('thumbor==6.3.2', 'console_scripts', 'thumbor')()
  File "/usr/lib64/python2.7/site-packages/thumbor/server.py", line 130, in main
    run_server(application, context)
  File "/usr/lib64/python2.7/site-packages/thumbor/server.py", line 102, in run_server
    with open(context.server.fd, 'r') as sock:
IOError: [Errno 6] No such device or address: '/run/supervisor/thumbor.sock'
```
Can you please let me know what I'm missing? I also tried /tmp/thumbor.sock with same results.

**Comment by masom** [comment]
@fmunteanu Are you trying to run Thumbor as a FastCGI process?

Thumbor is based on Tornado, providing an HTTP interface. You can use supervisor to manage thumbor but AFAIK it will not work as a FastCGI process.

**Comment by fmunteanu** [comment]
@masom my goal was to use H2O proxy, instead of Nginx. Unfortunately, latest H2O version does not support load balancing and I was hoping to use a socket, which after all, might be more efficient assigning processes. If Thumbor has set `--fd /run/supervisor/thumbor.sock`, then all I do is define the `proxy.reverse.url: https://[unix:/run/supervisor/thumbor.sock]` variable in H2O.

**Comment by masom** [comment]
Is it possible the socket does not yet exist when thumbor is launched? The `-fd` option should be working.

**Comment by fmunteanu** [comment]
The socket exists, note the manual start, without success:
```
# ls -lah /run/supervisor/thumbor.sock
srwx------. 1 h2o root 0 Jun  5 14:49 /run/supervisor/thumbor.sock

# /usr/bin/thumbor -c /etc/thumbor.conf -d -f /run/supervisor/thumbor.sock
Traceback (most recent call last):
  File "/usr/bin/thumbor", line 11, in <module>
    load_entry_point('thumbor==6.3.2', 'console_scripts', 'thumbor')()
  File "/usr/lib64/python2.7/site-packages/thumbor/server.py", line 130, in main
    run_server(application, context)
  File "/usr/lib64/python2.7/site-packages/thumbor/server.py", line 102, in run_server
    with open(context.server.fd, 'r') as sock:
IOError: [Errno 6] No such device or address: '/run/supervisor/thumbor.sock'
```

**Comment by masom** [comment]
@fmunteanu reading http://supervisord.org/configuration.html points to:

```
Note

The socket manager in Supervisor was originally developed to support FastCGI processes but it is not limited to FastCGI. Other protocols may be used as well with no special configuration. Any program that can access an open socket from a file descriptor (e.g. with socket.fromfd in Python) can use the socket manager. Supervisor will automatically create the socket, bind, and listen before forking the first child in a group. The socket will be passed to each child on file descriptor number 0 (zero). When the last child in the group exits, Supervisor will close the socket.
```

I think you should just be able to pass `-f 0` to thumbor instead of the socket path?

**Comment by fmunteanu** [comment]
@masom that's neat, sorry I missed that! Now, on with the H2O debugging, as images are not served through the proxy. :)

**Comment by masom** [comment]
@fmunteanu All good! I learned something :D
