### ISSUE TITLE
can not extract the first frame from an animated GIF

### ISSUE THREAD

**Issue by nukc** [thumbor/thumbor#956]
http://localhost:8888/unsafe/filters:extract_cover()/http://img.hchezhu.com/img/toutiao/2017-06-24/2a350002c680a5f649bb

### Thumbor request URL
http://img.hchezhu.com/img/toutiao/2017-06-24/2a350002c680a5f649bb
http://img.ycwb.com/news/attachement/gif/site2/20160921/507b9d762551194c19be5f.gif

### Expected behaviour
extract the first frame from an animated GIF

### Actual behaviour
see log

### Operating system
OSx

### Your thumbor.conf
Your config file (WARNING: replace your SECURITY_KEY key with a dummy key or your key will become public)

```sh
thumbor --port=8888 --conf=thumbor.conf
```

### LOG
```sh

thumbor:WARNING Module thumbor.filters.distributed_collage could not be imported: No module named cv2
thumbor:WARNING URL does not have hash or unsafe, or has both: /robots.txt
tornado.access:WARNING 400 GET /robots.txt (127.0.0.1) 1.68ms

thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 138, in get_image
    self.context.request.image_url
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 623, in _fetch
    fetch_result.buffer = self.context.request.engine.read(extension)
  File "/usr/local/lib/python2.7/site-packages/thumbor/engines/__init__.py", line 76, in read
    extension)
  File "/usr/local/lib/python2.7/site-packages/thumbor/engines/pil.py", line 279, in read_multiple
    popen = Popen(command, stdout=PIPE)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

thumbor:ERROR [BaseHandler] get_image failed for url `http%3A//img.hchezhu.com/img/toutiao/2017-06-24/2a350002c680a5f649bb`. error: `[Errno 2] No such file or directory`
tornado.access:ERROR 500 GET /unsafe/filters:extract_cover()/http://img.hchezhu.com/img/toutiao/2017-06-24/2a350002c680a5f649bb (127.0.0.1) 3331.77ms
thumbor:WARNING URL does not have hash or unsafe, or has both: /robots.txt
tornado.access:WARNING 400 GET /robots.txt (127.0.0.1) 3.78ms
thumbor:WARNING URL does not have hash or unsafe, or has both: /favicon.ico
tornado.access:WARNING 400 GET /favicon.ico (127.0.0.1) 8.40ms


```

**Comment by kkopachev** [comment]
try installing `gifsicle`

**Comment by nukc** [comment]
thanks
