### ISSUE TITLE
ImportError: No module named redis_storage

### ISSUE THREAD

**Issue by bothwellw** [thumbor/thumbor#999]
I am running on Ubuntu lsb_release -a shows:

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

in my configure file i have 

STORAGE = 'thumbor.storages.redis_storage'

when I do
thumbor -c /etc/thumbor.conf

i get:

Traceback (most recent call last):
  File "/usr/local/bin/thumbor", line 11, in <module>
    load_entry_point('thumbor==6.3.3rc0', 'console_scripts', 'thumbor')()
  File "/usr/local/lib/python2.7/dist-packages/thumbor-6.3.3rc0-py2.7-linux-x86_64.egg/thumbor/server.py", line 146, in main
    importer = get_importer(config)
  File "/usr/local/lib/python2.7/dist-packages/thumbor-6.3.3rc0-py2.7-linux-x86_64.egg/thumbor/server.py", line 68, in get_importer
    importer.import_modules()
  File "/usr/local/lib/python2.7/dist-packages/thumbor-6.3.3rc0-py2.7-linux-x86_64.egg/thumbor/importer.py", line 54, in import_modules
    self.import_item('STORAGE', 'Storage')
  File "/usr/local/lib/python2.7/dist-packages/thumbor-6.3.3rc0-py2.7-linux-x86_64.egg/thumbor/importer.py", line 95, in import_item
    module = self.import_class('%s.%s' % (conf_value, class_name))
  File "/usr/local/lib/python2.7/dist-packages/thumbor-6.3.3rc0-py2.7-linux-x86_64.egg/thumbor/importer.py", line 43, in import_class
    return import_class(name, get_module)
  File "/usr/local/lib/python2.7/dist-packages/thumbor-6.3.3rc0-py2.7-linux-x86_64.egg/thumbor/importer.py", line 19, in import_class
    module = get_module and __import__(name) or __import__(module_name)
ImportError: No module named redis_storage

I installed redis:
redis-server --version
Redis server v=3.2.1 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=8ab9de078b62748e

and the python packages:

 pip install redis
Requirement already satisfied: redis in /usr/local/lib/python2.7/dist-packages

The file storage but from the documentation on 
https://media.readthedocs.org/pdf/thumbor/latest/thumbor.pdf

I cant seem to see what I should change.

**Comment by kkopachev** [comment]
docs probably outdated. Redis storage is available as a plugin: https://github.com/thumbor-community/redis

**Comment by bothwellw** [comment]
many thanks

**Comment by mrmachine** [comment]
Docs should probably be updated then. Instead of just closing this issue, can we update its title/description and re-open (or make a new issue)?

I just went through this discovery myself after diligently reading all of the docs and setting up my config, only to find the docs are wrong.
